### ISSUE TITLE
Possibility to set page title and menu item separately

### ISSUE THREAD

**Issue by kmergen** [luyadev/luya#1004]
This is an enhancement request.
The page title and menu item name should be entered separately in the Admin UI, because they are not the same thing. This is also important for seo reasons.

e.g. 
- menu item name : Contact
- page title: Contact - Contactform and phone numbers of our company

**Comment by nadar** [comment]
The feature is now implemented in RC2-DEV. Do not forget to run the migrate command if you want to try it out.
