### ISSUE TITLE
Hardcoded text in admin views

### ISSUE THREAD

**Issue by JDL747** [luyadev/luya#1009]
Hardcoded german texts in different admin views

![screen-shot-2016-10-09-at-17 29 36](https://cloud.githubusercontent.com/assets/3844254/19221587/85af5fae-8e46-11e6-80fb-84a8d75b510c.png)
![screen-shot-2016-10-09-at-17 10 55](https://cloud.githubusercontent.com/assets/3844254/19221599/dfaa3f88-8e46-11e6-82b7-886e3f4de10d.png)

**Comment by JDL747** [comment]
The text `Uhr` is not translated in :

- [ ] luya-module-admin/src/views/layouts/main.php
- [ ] luya-module-cms/src/admin/views/default/index.php

**Comment by nadar** [comment]
@JDL747 line number?

**Comment by JDL747** [comment]
276 and 362
