### ISSUE TITLE
Page versions popup disappears on Firefox

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#1080]
### What steps will reproduce the problem?

Hover over a page version's label in Firefox (tested with Firefox 49 on Mac) and try to click on the edit or delete button.

### What is the expected result?

The popup should stay open so that the buttons can be clicked.

### What do you get instead? (A Screenshot can help us a lot!)

The popup disappears when trying to click these buttons:

![versions-popup-in-firefox](https://cloud.githubusercontent.com/assets/3786245/20356024/9f2e5764-ac23-11e6-8761-e89ffc9a0f82.gif)

| Q                | A
| ---------------- | ---
| LUYA Version     | RC1 and RC2-dev
| PHP Version      | 7
| Platform         | Several
| Operating system | tested on OSX

**Comment by TheMaaarc** [comment]
Can't solve the problem. It seems that the tooltip is only visible but not available to click or hover events.

**Comment by TheMaaarc** [comment]
@rolandschaub Do you have an idea?

**Comment by nadar** [comment]
This view does not longer exists with new admin ui #1292, so i am going to close this issue.
