### ISSUE TITLE
Improve Checkbox Relations in Admin Interface

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1083]
It would be nice to have some sorting or nesting options.

For example:

3 Main Categories ( Parents, marked with numbers 1 to 3 )

6 Sub Categories ( Childs, two of them have the same name but different Parents )

1.) Anna

- Tom
- Ira

2.) Bella

- Jan
- Tom

3.) Lena

- Mia
- Lia

In the example above only childs should be selectable.

How it is possible to sort depending on "parents" in the Admin interface ?

existing code: 

```
public function ngrestExtraAttributeTypes()
    {
        return [

            'mediation_type' => [
                'checkboxRelation',
                'model' => MediationType::className(),
                'refJoinTable' => 'kmb_mediation_package_type_ref',
                'refModelPkId' => 'package_id',
                'refJoinPkId' => 'type_id',
                'labelFields' => ['title'],
                'labelTemplate' =>  '%s',
            ],
        ];

    }
```

**Comment by nadar** [comment]
Add ability to load relation getter data from the $model property.
