### ISSUE TITLE
The online demo username & password does not work

### ISSUE THREAD

**Issue by saidbakr** [luyadev/luya#1092]
### What steps will reproduce the problem?
Go to: http://demo.luya.io/en/admin/login
use demo@luya.io as username and demoluya as a password

### What is the expected result?
Opening the administration section of LUYA.

### What do you get instead? (A Screenshot can help us a lot!)
Get "Wrong user or password." error message.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by mushahidh** [comment]
yes getting the same error.

**Comment by nadar** [comment]
Thanks for the report. I just rested the demo application, this is because people are going to change the password as its one instance. I will limit the permissions to not beeing able of chaning the user password!

ps: The demo will reset each hour.

**Comment by nadar** [comment]
@saidbakr Thanks for the Report. Now i changed the the permission of the demo@luya.io user to not change password and/or remove users and/or groups. Good to know that LUYA have good permission settings ;-)

But unfortunately people still can destory the demo application, if they want to...
