### ISSUE TITLE
Ngrest-plugin - Custom plugin can't set property of class via array config

### ISSUE THREAD

**Issue by vuongminh** [luyadev/luya#1104]
### What steps will reproduce the problem?

I config ngattribute like that:

    public function ngRestExtraAttributeTypes()
    {
        return [
            'items' => [
                'class' => InputRelation::class,
                    'model' => Item::class,
                    'refJoinTable' => 'order_item',
                    'refModelPkId' => 'id_order',
                    'refJoinPkId' => 'id_product',
                    'labelFields' => ['name', 'price'],
                    'labelTemplate' => '%s (%s)'
                ]
           
        ];
    }

### What is the expected result?

In InputRelation class can not get custom property:

public function init(){
var_dump($this->refJoinTable); // NULL VALUE
}

### What do you get instead?

Var_dump result must be string 'order_item'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.0RC2
| PHP Version      | 7.0.9
| Platform         | Window 10/ IIS

**Comment by nadar** [comment]
Thank you!
Pull requested is merged you can access the dev-master of the admin module in approx 60min after the subsplit process.
