### ISSUE TITLE
Position of input form for LinkInjectors in Blocks

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1116]
Injectors are a great extension.

Sadly there isn`t an option to sort the input fields in the admin view.
LinkInjectors are always placed on the top of the admin form which is a leck of usability ( especially for huge menus).

Any ideas?

**Comment by nadar** [comment]
Now you can use `'append' => true` when configure the injector.

**Comment by dev7ch** [comment]
and where???

**Comment by nadar** [comment]
Example from the commit above: https://github.com/luyadev/luya/commit/8f85ca415ccf147eeface937e318de356db8cb89#diff-aadfafbb62bda3498da3b5a45999900aR60

**Comment by rolandschaub** [comment]
It would be helpful to be able to define the position of the injected element even more specific to place it within the context of other fields.

**Comment by dev7ch** [comment]
public function injectors()
    {
        return [
            'link' => new \luya\cms\injectors\LinkInjector(['append' => true]),
        ];
    }
