### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by ASYOU99** [luyadev/luya#1122]
### What steps will reproduce the problem?

When I install module into RC2 i have a problem:
 The requested package luyadev/luya-module-news 1.0@dev exists as luyadev/luya-module-news[1.0.0-RC1, 1.0.0-RC2, 1.0.0-beta6, 1.0.0-beta7, 1.0.0-beta8, dev-master, 1.0.x-dev] but these are rejected by your constraint. 
All module write this I think this is due to the fact that the modules are inappropriate to the new version.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
Cold you please show me your composer.json file?

**Comment by ASYOU99** [comment]
{
    "name": "luyadev/luya-kickstarter",
    "description": "The kickstarter for a new LUYA application project.",
    "type": "project",
    "license":"MIT",
    "require": {
        "luyadev/luya-core" : "1.0.0-RC2",
        "luyadev/luya-module-admin" : "1.0.0-RC2",
        "luyadev/luya-module-cms" : "1.0.0-RC2"
    },
    "require-dev": {
        "yiisoft/yii2-gii" : "~2.0.0",
        "yiisoft/yii2-debug" : "~2.0.0"
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
			"setPermission": [
				{
					"public_html/assets": "0777",
					"public_html/storage": "0777"
				}
			]
		},
		"asset-pattern-skip-version": "(-build|-patch)",
        "asset-installer-paths": {
            "bower-asset-library": "vendor/bower"
        },
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        }
    }
}

**Comment by ASYOU99** [comment]
This file created afte default install luya

**Comment by ASYOU99** [comment]
maybe you want see composer.loc?

**Comment by nadar** [comment]
add to the require section:

```
"require": {

        "luyadev/luya-module-news" : "1.0.0-RC2",

}
```

and run `composer update`. This should work.

**Comment by ASYOU99** [comment]
ok senks this way a inderstood for all modules because in your guide write another way

**Comment by nadar** [comment]
If you like to install the dev master you could use 

`"luyadev/luya-module-news" : "^1.0@dev"`

After the 1.0.0 release we are going to update the readme files of all modules.

**Comment by nadar** [comment]
I assume your problem has been solved and i can close this issue.
