### ISSUE TITLE
Problem with NgRest plugin SelectModel when use with relation data.

### ISSUE THREAD

**Issue by vuongminh** [luyadev/luya#1125]
I have a column customer_id in **order** table relation with **customer** table and i config customer_id is plugin **SelectModel** and when show table list i want to show more info of customer address, phone, email... i can not get data via relation because customer_id replaced on **Plugin Event** of Plugin

My **ngRestConfig**:

```
    public function ngRestConfig($config)
    {
        $this->ngRestConfigDefine($config, 'list', ['customerName', 'customerPhone', 'customerAddress', 'model_id', 'vin_plate', 'license_plate', 'color_code', 'km']);
        $this->ngRestConfigDefine($config, ['update', 'create'], ['customer_id', 'model_id', 'type_id', 'vin_plate', 'license_plate', 'color_code', 'km']);
        $config->delete = true;
        return $config;
    }
```
My **getCustomer**

```
    public function getCustomer()
    {
        return $this->hasOne(Customer::className(), [
            'id' => 'customer_id'
        ]);
    }
```
I think problem on some event of **\luya\admin\ngrest\base\Plugin** when init:

```
    public function init()
    {
        // call parent initializer
        parent::init();
        
        if ($this->name === null || $this->alias === null || $this->i18n === null) {
            throw new Exception("Plugin attributes name, alias and i18n must be configured.");
        }
        
        $this->addEvent(NgRestModel::EVENT_BEFORE_VALIDATE, 'onSave');
        $this->addEvent(NgRestModel::EVENT_AFTER_FIND, 'onFind');
        $this->addEvent(NgRestModel::EVENT_AFTER_NGREST_FIND, 'onListFind');
        $this->addEvent(NgRestModel::EVENT_AFTER_NGREST_UPDATE_FIND, 'onExpandFind');
        $this->addEvent(NgRestModel::EVENT_SERVICE_NGREST, 'onCollectServiceData');
    }
```

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.2RC
| PHP Version      | 7.0.9
| Platform         |  IIS 10
| Operating system | Windows 10

**Comment by nadar** [comment]
Hi @vuongminh as the admin interface is based on rest you must provide your additional data as extraFields to the rest API read this section about extra fields: https://luya.io/guide/ngrest-model#extra-fields.

Then the yii\base\Object Getter/Setter behavior will find your extra defined fields as attribute defined in extraFields.

in your case it could look like this 

```php
public function getCustomerPhone()
{
    return $this->customer->phone;
}

public function getCustomerAddress()
{
    return $this->customer->city . ' ' . $this->customer->street; // just guessing here
}

public function extraFields()
{
    return ['customerPhone', 'customerAddresse']; // now the extra fields are registered and read to use, and uses the getter method of yii "customerPhone" equals "getCustomerPhone()"
}

// define the fields you have as extra attributes.
// For examle when having a time() value you can just assigned the `datetime` plugin and it will be parsed on the client side, like the other plugins are used too.
public function ngrestExtraAttributeTypes()
{
    return [
        'customerPhone' => 'text',
        'customerAddresse' => 'text',
    ];
}

// now everything is setup, let your config know about your files:

public function ngRestConfig($config)
{
    // ...
    $this->ngRestConfigDefine($config, ['list'], ['customerPhone', 'customerAddresse', '.... all other list fields']);
    // ...
}
```

The extra field behavior is basically a yii 2 mechanism. http://www.yiiframework.com/doc-2.0/guide-rest-resources.html#overriding-extra-fields

I hope this helps, otherwise let me know.

**Comment by vuongminh** [comment]
Thank you for help @nadar ! I know that, but it not work when my customer_id is SelectModel plugin.

```
    public function ngRestAttributeTypes()
    {
        return [
            'customer_id' => [
                'class' => SelectModel::className(),
                'modelClass' => Customer::className(),
                'valueField' => 'id',
                'labelField' => 'info'
            ],
            'vin_plate' => 'text',
            'license_plate' => 'text',
            'machine_code' => 'text',
            'machine_type' => 'text',
            'machine_type_version' => 'text',
            'color_code' => 'text',
            'km' => 'text',
        ];
    }

    public function getCustomer()
    {
        return $this->hasOne(Customer::className(), [
            'id' => 'customer_id'
        ]);
    }
```

My test code:

```
    public function init()
    {
        parent::init();
        $this->on(static::EVENT_AFTER_FIND, function(){
             var_dump($this->customer_id); /// it's string ""
        });
    }

``

**Comment by nadar** [comment]
Ok, to understand correctly: you want to collect the customer relation data on `EVENT_AFTER_FIND`? But in the database you would have a value for `customer_id` field on the current record?

**Comment by nadar** [comment]
So you would expect:

```php
  public function init()
    {
        parent::init();
        $this->on(static::EVENT_AFTER_FIND, function(){
             var_dump($this->customer_id); /// data from the database, like an integer value
        });
    }
```

**Comment by nadar** [comment]
is the field i18n casted?

**Comment by vuongminh** [comment]
I had found the problem in class **\luya\admin\ngrest\plugins\Select** [https://github.com/luyadev/luya/blob/master/modules/admin/src/ngrest/plugins/Select.php#L39-L47](#L39-L47) it overwrite a value of customer_id => can not detect customer via id.

**Comment by vuongminh** [comment]
`     
public function onAfterListFind($event)
    {
        $value = StringHelper::typeCast($event->sender->getAttribute($this->name));
        $ngRestConfig = $event->sender->getNgRestConfig();
        foreach ($this->data as $item) {
            if ($item['value'] === $value && isset($ngRestConfig['list'][$this->name])) {
                $event->sender->setAttribute($this->name, $item['label']);
            }
        }
    }
`

It can solved my problem but isn't good solution.

**Comment by nadar** [comment]
But this is another case, its the https://github.com/luyadev/luya/blob/master/modules/admin/src/ngrest/base/Plugin.php#L82 event (which is an event only trigger for the ngrest list) I am going to make a unit test to check your problem! Thanks for your investigations!

**Comment by vuongminh** [comment]
Thank you @nadar ! I am waiting ...

Happy holiday !!!!

**Comment by nadar** [comment]
hi @vuongminh, now i was able to reproduce your problem. The `customer_id` value has already been set from the plugin, therefore the relation definition won't work anymore (as the customer_id value is now a string you have define trough the SelectModel plugin).

So now one thing is clear: The customer_id value can only have

a.) The value from the database without the after_event triggered
or
b.) the observed value from the ngrest plugin.

But not both (As far as i can see at least).

Do you have a good idea to solve the problem?

**Comment by nadar** [comment]
Your suggestion in the previous comment was 

> Abort the after find event when the field is not in the `list` pointer section of the config. 

Well this would work in this case, but what if both should be possible. What i also have to mention is that since 1.0.0 development build its possible to provide different fields to display ($labelField) and how they should be rendered ($labelTemplate) but its still not a grid view output (which can be usefull when using the export button).

https://github.com/luyadev/luya/blob/master/modules/admin/src/ngrest/plugins/SelectModel.php#L42-L65

**Comment by nadar** [comment]
@vuongminh One solution which could at least temporarly solve the problem would be:

```php
public function getOriginalCustomerId()
{
    	return $this->getOldAttribute('customer_id');
}
    
public function getCustomer()
{
    	return $this->hasOne(Customer::className(), ['id' => 'originalCustomerId']);
}
```

Or maybe just for the admin list use case:

```php
public function getCustomerName()
{
    Customer::findOne($this->getOldAttribute('customer_id'))->firstname;
}
```

**Comment by vuongminh** [comment]
@nadar I think your solutions is good but need more document for newbie! Thanks for your enthusiasm!

**Comment by nadar** [comment]
@vuongminh i am going to add a section in the guide. Thank you for the Report, its very important for us to understand what other people think and expect from the system. We hope you like LUYA and you can build your application easy.

Lets us know if we can help.
