### ISSUE TITLE
[JS] How to create Depdrop directive

### ISSUE THREAD

**Issue by vuongminh** [luyadev/luya#1129]
Hi Luya developers team! I want to create Depdrop plugin for my project like [Kartik-Depdrop](http://plugins.krajee.com/dependent-dropdown). Could you help me?

**Comment by nadar** [comment]
This is a lot of work and maybe its going to be hard to write the angular directive, but this is hard to guess as was not looking deep in the depdrop js code.

+ Create a module (if you like that other people can use it, maybe direct a new repo, so i can i fork and help if i have time. `luya-plugin-depdrop` or something like this)
+ Create the plugin environment: https://luya.io/guide/ngrest-plugins#create-a-custom-project-plugin
+ Wirte the directive ;-) I just google very quick, maybe this helps: http://henriquat.re/directives/advanced-directives-combining-angular-with-existing-components-and-jquery/angularAndJquery.html

**Comment by vuongminh** [comment]
```
zaa.directive("customer", function ($timeout) {
    return {
        link: function (scope) {   
            
             
        }
    }
}

zaa.directive("vehicle", function ($timeout) {
    return {
        link: function (scope) {   
              // How can i access customer scope
             
        }
    }
}
```

**Comment by nadar** [comment]
Well, i am not sure but i guess i would make just one directive. An pass the data of the containers to the directive.

A directive like this:

```js
zaa.directive("myDirective", function() {
    return {
        restrict: "E",
        scope : {
            'model' : '=',
            'data' : '=',
        },
        controller: function($scope, $filter) {
            $scope.$watch(function() { return $scope.model }, function(n, o) {
                console.log(n, o);
            });
        },
        template : function() {
            return '<div>{{data | json }} - {{ model }} - <input type="text" ng-model="model" /></div>';
        }
    }
});
```

Now you can pass the configured depdrop option containers (the different select droddowns) via the service data:

```php
public function serviceData()
    {
        return [
            'data' => [
                // some data we always want to expose to the directive,
            ],
        ];
    }
```

So in otherwords, you always should pass the data trough the service. If you want to share data between two directives you have to create an angular service: https://docs.angularjs.org/guide/services

**Comment by vuongminh** [comment]
I had try your solution before create issue but it have a problem with CSS and it will be done when i add some CSS (margin-top) because 2 fields in 1 div rows.

![untitled](https://cloud.githubusercontent.com/assets/13974585/21603684/accd0d7e-d1d1-11e6-8576-bb7e61840cd5.png)

My directive template:

```
        template: function () {
            return '<div class="input input--select" ng-class="{\'input--hide-label\': i18n}">' +
                '<label class="input__label" for="{{id}}">Khách hàng</label>' +
                '<div class="input__select-wrapper">' +
                '<select><option></option></select>' +
                '</div>' +
                '</div>' +
                '<div class="input input--select" ng-class="{\'input--hide-label\': i18n}">' +
                '<label class="input__label" for="{{id}}">Khách hàng</label>' +
                '<div class="input__select-wrapper">' +
                '<select><option></option></select>' +
                '</div>' +
                '</div>';
        }
```

**Comment by nadar** [comment]
We just discussed internal, we gonna provide a solution for this. But for now just add `style="margin-top:20px,"` for the second input div.

**Comment by vuongminh** [comment]
Thank you very much @nadar 👍

**Comment by TheMaaarc** [comment]
@vuongminh You should be able to remove the inline style after you updated to the most recent luya-module-admin version.

**Comment by vuongminh** [comment]
Thank you @TheMaaarc 👍

**Comment by nadar** [comment]
@vuongminh if you need further help let me know. If you can port the depdrop plugin into luya, we would love to see this.

**Comment by vuongminh** [comment]
@nadar Of course! I will port some luya plugins in my project for communicate :D!

**Comment by nadar** [comment]
@vuongminh This seems to be somewhat closed. So i am going to close this issue. If there is any further to do, please create a new issue. thank you
