### ISSUE TITLE
[JS] Directive SelectModel need call typeCast when model value is numeric like initValue.

### ISSUE THREAD

**Issue by vuongminh** [luyadev/luya#1131]
### What steps will reproduce the problem?

When ngRestCallType update response:

```
{"id_staff":"1","id_cus_vehicle":"1"}

```

Directive zaaSelect can not detect selected value because value is string

### What is the expected result?

Directive zaaSelect must be detect selected item.

### What do you get instead? (A Screenshot can help us a lot!)

Directive zaaSelect can not detect seleected item

### Additional infos

Must use typeCast when model value is numeric.

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.2RC
| PHP Version      | 7.0.9
| Platform         | IIS 10
| Operating system | Windows 10

**Comment by nadar** [comment]
Could you please provide me an example of how i can configure the plugin in order to reproduce your problem? Is it related to the notation https://luya.io/guide/app-block-type-select#selects-in-blocks 

> Take care with the data types, do not use "1" when dealing with numeric values, use 1 instead otherwhise the type cast will change your values.

So i could reproduce it. Cause maybe it would make sense i am going to type cast the php response instead of implementing the type casting on each directive.

**Comment by vuongminh** [comment]
When column in database is bigint it can not convert to php int [https://github.com/yiisoft/yii2/issues/2211](https://github.com/yiisoft/yii2/issues/2211)

**Comment by vuongminh** [comment]
I think we should convert all to string type

**Comment by nadar** [comment]
But i could parse the rest output with https://luya.io/api/luya-helpers-ArrayHelper#typeCast()-detail This would maybe solve other problems too.

**Comment by vuongminh** [comment]
I don't know but when i change my column data type to int, it's int.

**Comment by nadar** [comment]
But then your output of the above example should be:

```json
{"id_staff":1, "id_cus_vehicle":1}
```

instead of

```jons
{"id_staff":"1", "id_cus_vehicle":"1"}
```

**Comment by vuongminh** [comment]
Yes when I change column data type (bigint unsigned to int unsigned) rest result correct data type:

```
{"id_staff":1, "id_cus_vehicle":1}
```

**Comment by nadar** [comment]
So your problem would be fixed?

I merged your pull request, but i still think it would be better to ensure that the api response is correctly typecasted.

**Comment by vuongminh** [comment]
I agree with you! I think it should be solve in rest api

**Comment by nadar** [comment]
@vuongminh Its been a while, i guess we can close this. If we do have any further problems, we create a new one?
