### ISSUE TITLE
[Feature] SelectModel should accept custom attribute label field

### ISSUE THREAD

**Issue by vuongminh** [luyadev/luya#1133]
I see in **SelectModel** we use method **getAttribute** to general label field but sometime i want to use custom attribute via **getter**. It can be done via **labelTemplate** but it will duplicate code

Example:

I already have method

```
function getCustomerName(){
         return $this->first_name . ' ' . $this->last_name;
}

```

And when i use SelectModel plugin i just need config **labelField** is **customerName**:

```
[
     'labelField' => 'customerName'
]
```

But now:

```
[
    'labelField' => ['first_name', 'last_name'],
    'labelTemplate' => '%s %s'
]

```

It will break **DRY** design

**Comment by nadar** [comment]
So you mean we should change from:

```php
$model->getAttribute($field);
```

to:

```php
$model->$field;
```

In order to access getter methods?

**Comment by vuongminh** [comment]
Yes and I think we should deprecate labelTemplate and accept use closure for labelField

```
[
     'labelField' => function($model){
           return $model->getCustomerName();
     }

]

```

**Comment by nadar** [comment]
Allowing closure is a good idea indeed, but i would not deprecate labelTemplate, so user can choose whether he is used to closures or not.

**Comment by nadar** [comment]
Would you like to send a PR?
