### ISSUE TITLE
Icons overlay on small screen.

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1139]
If a few modules are registered and the screen is small, the icon toolbar overlaps the content container.

![image](https://cloud.githubusercontent.com/assets/3417221/21751053/db8498ba-d5c0-11e6-8baa-c504b22d0762.png)

**Comment by dev7ch** [comment]
i gonna fix it

**Comment by nadar** [comment]
Should be part of #1292, therefore i am going to close this issue.
