### ISSUE TITLE
Greek Translation

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1158]
In order to translate the most important modules:

- [x] https://github.com/luyadev/luya/tree/master/modules/admin/src/messages
- [x] https://github.com/luyadev/luya/tree/master/modules/cms/src/frontend/messages
- [x] https://github.com/luyadev/luya/tree/master/modules/cms/src/admin/messages
- [x] https://github.com/luyadev/luya/tree/master/envs/kickstarter/messages

"Optional" modules which are not part of the default installation:

- [ ] https://github.com/luyadev/luya/tree/master/modules/crawler/src/admin/messages
- [ ] https://github.com/luyadev/luya/tree/master/modules/errorapi/src/messages
- [ ] https://github.com/luyadev/luya/tree/master/modules/news/src/admin/messages
- [ ] https://github.com/luyadev/luya/tree/master/modules/gallery/src/admin/messages

Thank you for help us translating LUYA, if you have any questions, let us know.

**Comment by gvasilopulos** [comment]
Ok will do everything asap

**Comment by gvasilopulos** [comment]
all the important modules are translated now, will do the extras and js asap

**Comment by nadar** [comment]
I just merged the pull request, thank you!

**Comment by nadar** [comment]
https://github.com/luyadev/luya/pull/1160

**Comment by nadar** [comment]
@gvasilopulos Do you think its possible to provide the rest of the translations until next 2 weeks? So it will be part of 1.0.0 release.

**Comment by gvasilopulos** [comment]
until next two weeks 99% yes

**Comment by nadar** [comment]
Perfect!

**Comment by gvasilopulos** [comment]
I think everything is ok

**Comment by nadar** [comment]
well done @gvasilopulos. Thanks!
