### ISSUE TITLE
closable root directory

### ISSUE THREAD

**Issue by kimonaris** [luyadev/luya#1163]
A block where you can close and open the root directory.
page selecting ( at the internal page selecting tool ) should be closable.

**Comment by nadar** [comment]
@TheMaaarc I just implemented a very basic toggler, though it looks a bit ugly when closed. Any ideas?

**Comment by nadar** [comment]
<img width="345" alt="bildschirmfoto 2017-01-31 um 21 43 55" src="https://cloud.githubusercontent.com/assets/3417221/22483642/6620597e-e7fe-11e6-8dbd-2ee502fdff2a.png">

@TheMaaarc @dev7ch What would you suggest to improve the "meaning" of this icon? Maybe it should not stand above?

**Comment by TheMaaarc** [comment]
![image](https://cloud.githubusercontent.com/assets/3450438/24156404/b75d273a-0e56-11e7-8c47-7c1242d78bf5.png)

**Comment by nadar** [comment]
@TheMaaarc :+1: great
