### ISSUE TITLE
Problem when upload file without PHP fileinfo ext.

### ISSUE THREAD

**Issue by vuongminh** [luyadev/luya#1173]
Can not upload file without php fileinfo ext.

API send error:

```
{upload: false, message: "Error while storing your image in the storage component."}
```

Problem in FileHelper because when server haven't fileinfo ext Yii will use extension of file name to detect mimeType

I use IIS server and my tmp upload file like: "C:\tmpdir\aaaa.tmp" => extension is "tmp" and "tmp" is not in list magic mineType of Yii => mineType empty => can't validate in **StorageContainer** component => this issue.

See StorageContainer: [#L384-L400](https://github.com/luyadev/luya/blob/master/modules/admin/src/components/StorageContainer.php#L384-L400)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1
| PHP Version      | 7.0.9
| Platform         | IIS 10
| Operating system | Windows 10

**Comment by nadar** [comment]
So you mean this extensions is not installed and enabled by default on your IIS System? http://www.php.net/manual/en/fileinfo.installation.php

**Comment by vuongminh** [comment]
Yes! On my on my server and plesk hosting service in my country fileinfo ext not enabled by default

**Comment by vuongminh** [comment]
I think  when FileHelper can not get mime type we should use tmp_name in $_SERVER

**Comment by nadar** [comment]
You mean in $_FILES? What would be the output from $_FILES in your case for the aaaaa.tmp file?

**Comment by vuongminh** [comment]
We use $_FILES['model']['name']

**Comment by nadar** [comment]
what would be var_dump of $_FILES['model']

**Comment by vuongminh** [comment]
+ name
+ size
+ tmp_name
....

**Comment by nadar** [comment]
yes and what would be the value for tmp_name?

**Comment by vuongminh** [comment]
![Uploading IMG_2031.PNG…](Must be config php.ini)

**Comment by nadar** [comment]
Oopps something seems wrong with your file upload? ;-) Maybe waiting longer until press Comment.

**Comment by vuongminh** [comment]
aaa.tmp when FileHelper can not get mime type of tmp_name we use name to detect it...

**Comment by vuongminh** [comment]
'''
Windows users: just edit php.ini and uncomment this line:

extension=php_fileinfo.dll

Remember to restart Apache for new php.ini to take effect.
'''

**Comment by nadar** [comment]
1. I can not see your file upload! Please upload again.
2. I need to see your output from a file upload $_FILES array for your current file (aaaa.tmp).
3. We can not determine the mime type from a `aaaa.tmp` file name, as far as i know. But maybe its contained in the $_FILES original name. So therefore i need (.2)

**Comment by nadar** [comment]
@vuongminh See the commit above, this should fix the problem as well but its not recommend to ensure the mime type from a file name as it can contain ANYTHING... Rename `hacker.exe` to `file.jpg` and mime type will be jpg but should be exe - U know what i mean?

**Comment by vuongminh** [comment]
I know it. So dangerous but in this case upload file only use by admin user i think this solution no problem on backend admin.

**Comment by nadar** [comment]
Please test the changes in your environment, and if it works you can close this issue.

**Comment by vuongminh** [comment]
Thank for your help @nadar !

**Comment by nadar** [comment]
#1391 i have to revert back this commit, as it can be to dangerous. If this problem appears again @vuongminh i am going to add an option to disable secure uploads.
