### ISSUE TITLE
Non-existent page

### ISSUE THREAD

**Issue by ASYOU99** [luyadev/luya#1174]
After creating a newsletter I want to add it to the page and click the settings when the content of the news unit get this:
![screenshot_2](https://cloud.githubusercontent.com/assets/12735688/22148249/a6057fa2-df15-11e6-8056-f988d4560afe.jpg)
Here there are pages and templates (some duplicated) which I no longer exist.

**Comment by nadar** [comment]
True, i think we have to improve this block a bit (and translate for message file).

https://github.com/luyadev/luya/blob/master/modules/news/src/admin/blocks/LatestNews.php#L21

When the news module is registered as module block, its currently not possible to find those pages - thats why there are just all pages listed.

**Comment by ASYOU99** [comment]
That is, when you delete pages \ templates they like Undelete fully what that information about them in the database and that it is drawn into the unit instead of topical news pages that exist now. Do I understand?

**Comment by nadar** [comment]
I think we will drop the default blocks of modules as you can not configure the views. #1274

**Comment by nadar** [comment]
@ASYOU99 Thanks for the report. I am going to close this issue as we will drop those default blocks of this module.
