### ISSUE TITLE
Checkbox Relation selection problem

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1187]
````
public function injectors()
    {
        return [
            'publications' => new ActiveQueryCheckboxInjector([
                'query' => Publication::find()->select(['title', 'subtitle']),
            ]),
        ];
    }
````
This Example above is referrs to a NgRest model. 

If you select one checkbox in the admin backend, all checkboxes getting selected.

Any ideas?

**Comment by nadar** [comment]
I am unable to reproduce this problem, my test config:

```php
'test' => new ActiveQueryCheckboxInjector([
    'query' => NavItem::find(),
]),
```

I could select the items from the nav item table, and print them in the block view.

Whats does your model look like?

**Comment by dev7ch** [comment]
````    public function ngRestConfig($config)
    {
        $config->list->field('title', 'Titel')->text();
        $config->list->field('subtitle', 'Untertitel')->text();

        $config->update->copyFrom('create');

        $config->delete = true;

        return $config;
    }
```

**Comment by nadar** [comment]
The ngRestConfig is not related to the ActiveQueryCheckboxInjector

**Comment by nadar** [comment]
What happens if you choosen another `query`? Is this `If you select one checkbox in the admin backend, all checkboxes getting selected.` a problem from the UI? What will be display in the view?

**Comment by dev7ch** [comment]
If i use  `'query' => NavItem::find()` or `'query' => Publication::find()` all works fine.

**Comment by dev7ch** [comment]
It looks like the `select`() option of the lablefield causes this error.

`'query' => Publication::find()->select(['title', 'subtitle']`

**Comment by nadar** [comment]
But then only those fields will be displayed? But the selection wont work anymore? What if you choose a not i18n casted field in the select? I tryed the select() as well and it worked fine, hmm. 

my test case:
```php
'test' => new ActiveQueryCheckboxInjector([
    'query' => NavItem::find()->select(['title']),
]),
```

**Comment by dev7ch** [comment]
ok maybe i am miss understanding the use of selection ... 
So selection is for field restriction only ?

In my case was used to limit the labels from the checkboxes but not the output in the view

**Comment by nadar** [comment]
Currently it does affect both them (the select checkbox and the models extra data in the view file). Maybe it should only affect the select checkbox in the administration view, but this is not related to your problem - cause you where "unable to select a checkbox, cause it selected all of them then"?

**Comment by dev7ch** [comment]
![bildschirmfoto 2017-01-26 um 15 23 31](https://cloud.githubusercontent.com/assets/15183757/22334579/971a12ee-e3db-11e6-988d-43e0ba9ab3b9.png)

Without select()

**Comment by dev7ch** [comment]
![bildschirmfoto 2017-01-26 um 15 26 55](https://cloud.githubusercontent.com/assets/15183757/22334690/eda3ddac-e3db-11e6-8d83-ed6544fd52d2.png)

with select and i18n field ( only one checkbox was clicked )

**Comment by nadar** [comment]
so the problems appears only when `select` is used with an *i18n casted field*?

**Comment by dev7ch** [comment]
probably yes

**Comment by nadar** [comment]
@dev7ch I just added new option `label` in order to provide custom labels:

see: https://github.com/luyadev/luya/blob/master/modules/cms/src/injectors/ActiveQueryCheckboxInjector.php#L47-L59

Don't forget to remove the `select()` in your active query. Please let me know if i18n fields are displayed correctly.

**Comment by dev7ch** [comment]
Yes, the new implementation works great with i18n fields. Cheers & Thanks :)
