### ISSUE TITLE
define the "main layout" for a cms page

### ISSUE THREAD

**Issue by agaplus** [luyadev/luya#1188]
### What is the expected result?

Proposal: define a different "main layout" for a cms page. For Example: Sidebar.php(cmslayout folder) extends Page.php(layouts folder) and Homepage.php(cmslayouts fodler) extends Main.php(layouts folder).

Thank you.

### Additional infos

| LUYA Version  1.0.0RC2  
| PHP Version  5.6   
| Platform   WAMP   
| Operating system Windows

**Comment by nadar** [comment]
@agaplus Great idea, as it also allows you to render pages with ajax without any body and head structure.

**Comment by rolandschaub** [comment]
+1
