### ISSUE TITLE
[Design] Chosen Plugin Styling Bug

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1195]
<img width="275" alt="bildschirmfoto 2017-02-06 um 10 56 47" src="https://cloud.githubusercontent.com/assets/3417221/22642482/26800434-ec5b-11e6-8a70-89bf2e7097d0.png">

Sometimes the chosen plugin dropdown design is "broken".

How to reproduce:

System -> User Groups -> Edit a Group -> Klick on the User Relation Modal -> Add new User -> Title Dropdown.

**Comment by nadar** [comment]
@dev7ch

**Comment by nadar** [comment]
@TheMaaarc Maybe check the problem with @dev7ch

**Comment by dev7ch** [comment]
![bildschirmfoto 2017-02-06 um 11 16 53](https://cloud.githubusercontent.com/assets/15183757/23020155/f433052e-f445-11e6-8946-9de19be70698.png)

**Comment by dev7ch** [comment]
![bildschirmfoto 2017-02-16 um 12 47 02](https://cloud.githubusercontent.com/assets/15183757/23020179/13fc32a4-f446-11e6-8ea4-9865b6669cde.png)

**Comment by dev7ch** [comment]
Tested in Chrome

**Comment by nadar** [comment]
Wired :-/

**Comment by dev7ch** [comment]
i was not able to find the place where this action takes place ( in about 25min) ... i guess there are people out there who needs a few seconds ;) 

Could you provide me a lInk where to find this?
Wich browser do you use?

**Comment by nadar** [comment]
I was unable to reproduce as well. (With the described way from the start topic). Lets close the issue, and open a new one if the problem appears again. 

Maybe its about the size of the window in the moment the admin is initialized? i dunno

**Comment by dev7ch** [comment]
ok fine, i dunno neighter
