### ISSUE TITLE
Copy language page with versions

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1201]
### What steps will reproduce the problem?

Create a new language for an existing page with existing versions.

### What is the expected result?

New page translation will be created from newest version.

### What do you get instead? (A Screenshot can help us a lot!)

New page will be created from a random versione (maybe the oldest)

**Comment by nadar** [comment]
@rolandschaub I was not able to reproduce the issue. Could you please make an example? Thanks!

**Comment by nadar** [comment]
@rolandschaub Please provide more informations, otherwise close the issue as its not a bug.

**Comment by rolandschaub** [comment]
Can't reproduce the problem either. Maybe the problem (which was reported by a customer) existed in an older version of Luya.
