### ISSUE TITLE
LinkInjector: Strange twig output in block admin

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1202]
````
    public function injectors()
    {
        return [
            'link' => new \luya\cms\injectors\LinkInjector(['append' => true])
        ];
    }
````

If i would like to show the href string of the link i am getting ``` [object Object]  ``` instead of the href value.

{{ dump(extras.link)}} works fine

{{ extras.link }} should return the href value

**Comment by nadar** [comment]
@dev7ch @rolandschaub Now the object data should be available for link injector data. In your case @dev7ch  its `{{ link.href }}` inside the twig.js view. Please test and let me know, so you can close this issue afterwards.

**Comment by dev7ch** [comment]
```
public function admin()
    {
        return '<b>{{vars.title}}:</b>
                {% if vars.links not empty %}
                    <ul>
                        {% for link in vars.links %}
                            <li>{{link.text}} - {{link.href}}</li>
                        {% endfor %}                
                    </ul>
                {% else %}
                    <ul>
                        <li>Es wurden keine Links angeben.</li>
                    </ul>
                {% endif %}';
    }
```

**Comment by nadar** [comment]
Your output is not related to the topic question, as its seems not to be build with the LinkInjector.
