### ISSUE TITLE
File storage thumb image not showing

### ISSUE THREAD

**Issue by vuongminh** [luyadev/luya#1206]
I had upgrade my web app to 1.0 dev and after that i have an issue with thumb image of file storage

![untitled](https://cloud.githubusercontent.com/assets/13974585/22773731/3cf81c1a-eed6-11e6-9cd9-be255c53f223.png)

**Comment by nadar** [comment]
What do you get when you inspect the element with the developer element insprector? Maybe the image is there but wrong path or something. 

What type of browser?

**Comment by vuongminh** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13974585/22776400/12a42be6-eee2-11e6-9944-63bc763cee83.png)

I use firefox 50.0

**Comment by nadar** [comment]
Could check if the file item retuns true for `isImage`? https://luya.io/api/luya-admin-file-Item#getIsImage()-detail Cause maybe its related to the mime type of your image?

https://github.com/luyadev/luya/blob/master/modules/admin/src/file/Item.php#L227-L230

**Comment by vuongminh** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13974585/22778143/6fc85f1c-eee8-11e6-8e83-9d0a5a436679.png)

My images mime type...

**Comment by nadar** [comment]
Could you please post me the response of the data-files api for this image? I am wondering if the `thumbnail` object exists in the response:

![image](https://cloud.githubusercontent.com/assets/3417221/22778407/1ee5bed6-eeb7-11e6-93b8-0e3839130ce3.png)

btw: maybe run: `./vendor/bin/luya import` and `./vendor/bin/luya admin/storage/process-thumbnails`

**Comment by nadar** [comment]
(btw: i don't have any problems with the thumbnails, even in firefox)

**Comment by vuongminh** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13974585/22778798/c4496994-eeea-11e6-94fe-8fdd6cc6ec7e.png)

:(

**Comment by nadar** [comment]
Are you sure the files can be generated? Cause the thumbnails are file versions with a filter. The folder and the existing file are writeable and readable? 

Cause the thumbnails will be generated on the first request, maybe this process fails? 

https://github.com/luyadev/luya/blob/62d641ed6fa0bd8c4fbf222ce6e6203b6d7cc8b6/modules/admin/src/apis/StorageController.php#L80-L97

Maybe also flush your cache in order to ensure the api response is not cached.

**Comment by vuongminh** [comment]
I had found my problem on [\luya\admin\models\StorageFilterChain#105](https://github.com/luyadev/luya/blob/62d641ed6fa0bd8c4fbf222ce6e6203b6d7cc8b6/modules/admin/src/models/StorageFilterChain.php#L105). Because yii2-imagine extension require extension **gd2** or **imagick** or **gmagick** to work but my vps haven't.

**Comment by vuongminh** [comment]
Thank for support me @nadar

**Comment by nadar** [comment]
Maybe the health command should check if one of the extensions exists? https://github.com/luyadev/luya/blob/master/core/console/commands/HealthController.php

**Comment by vuongminh** [comment]
Yes! Good idea 👍
