### ISSUE TITLE
luya migrate got : PHP Fatal error:  Class 'luya\Boot' not found in luya\vendo r\luyadev\luya-core\bin\luya on line 18

### ISSUE THREAD

**Issue by wahono77** [luyadev/luya#1207]
### What is the expected result?
D:\acosys5server\www\luya\vendor\bin>luya migrate
PHP Fatal error:  Class 'luya\Boot' not found in D:\acosys5server\www\luya\vendo
r\luyadev\luya-core\bin\luya on line 18
PHP Stack trace:
PHP   1. {main}() D:\acosys5server\www\luya\vendor\luyadev\luya-core\bin\luya:0

Fatal error: Class 'luya\Boot' not found in D:\acosys5server\www\luya\vendor\luy
adev\luya-core\bin\luya on line 18

Call Stack:
    0.0007     123952   1. {main}() D:\acosys5server\www\luya\vendor\luyadev\luy
a-core\bin\luya:0

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.0-RC2
| PHP Version      | 5.6
| Platform         | XAMPP
| Operating system | Windows

**Comment by nadar** [comment]
Its cause you are in the bin folder. Go into the public_html folder and run the commands like this:

```
php index.php migrate
```

https://github.com/luyadev/luya/blob/master/docs/guide/install-windows.md

**Comment by wahono77** [comment]
Thanks, it's OK now, maybe it's should ibe in documentation

**Comment by nadar** [comment]
It will be published in the luya.io docs after the 1.0.0 release. Hope your luya application works well.
