### ISSUE TITLE
Hidden Menu Items are shown useing getLevelContainer() Method

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1210]
```
Yii::$app->menu->getLevelContainer(3)
```

Shows hidden items which shouldn't be there

**Comment by nadar** [comment]
I was unable to reproduce this problem.

My navigation:

<img width="510" alt="bildschirmfoto 2017-02-18 um 22 48 36" src="https://cloud.githubusercontent.com/assets/3417221/23097120/53d292dc-f62c-11e6-8d37-ad922f636707.png">

My sites setup: (you can see `test` is blanked out, which means *hidden*):

<img width="297" alt="bildschirmfoto 2017-02-18 um 22 49 20" src="https://cloud.githubusercontent.com/assets/3417221/23097123/6bfefcd8-f62c-11e6-907e-e21964aea5ae.png">

And it was not display in the frontend navigation, as expected. Could you please show me your setup? (without exposing sensitive data)
