### ISSUE TITLE
Deselect selected internal link

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#1211]
### What steps will reproduce the problem?

Select a page as a target for an internal link in a form (block or CRUD). Then try to deselect it (without selecting another page).

### What is the expected result?

That there is a way to do so.

### What do you get instead? (A Screenshot can help us a lot!)

It's not possible to deselect the previously selected page for an internal link.

<img width="561" alt="link" src="https://cloud.githubusercontent.com/assets/3786245/23104133/570d37bc-f6c8-11e6-9f31-e903538a4dbd.png">

**Comment by nadar** [comment]
This makes only sense for page selectors where the selection is not required. So i think there should be an argument to pass to the directive in order to add ability to reset the model value to null.
