### ISSUE TITLE
Getting numbers of Item content

### ISSUE THREAD

**Issue by alponso** [luyadev/luya#1227]
### What steps will reproduce the problem?
controller:
```php
namespace app\modules\news\frontend\controllers;
class DefaultController extends \luya\web\Controller
{
    public function actionIndex()
    {
        $model = Yii::$app->menu->findAll(['depth' => 1, 'container' => 'news']);
        return $this->render('index', [
            'model' => $model
        ]);
    }
}
```

view: index.php
```php
<?php foreach ($model as $item): ?>
    <h3><?= $item->title ?></h3>
    <p>
        <?= \luya\helpers\StringHelper::truncate($item->getModel()->activeLanguageItem->getContent(), 200, "<a href=\"$item\">Read more...</a>", null, true) ?>
    </p>
<?php endforeach; ?>
```
### What is the expected result?
I know this is expected behavior. But maybe it will produce minimal query if the `Item` object has `getContent()` method that returning content from `$itemArray['content']`

### What do you get instead? (A Screenshot can help us a lot!)
Multiple query

![image](https://cloud.githubusercontent.com/assets/4850108/23704290/b3b4711c-0436-11e7-8095-12fbf5f45b96.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev-master
| PHP Version      | 5.6.30
| Platform         | Apache/2.4.23 (Win32) OpenSSL/1.0.2h mod_fcgid/2.3.9 Server
| Operating system | Windows 10 x64

**Comment by nadar** [comment]
@alponso I just added an ability to preload all models for a given menu query, this should reduce your sql requests. You can use it like this:

change 
`$model = Yii::$app->menu->findAll(['depth' => 1, 'container' => 'news']);` 
to 
`$model = Yii::$app->menu->findAll(['depth' => 1, 'container' => 'news'], true);`
