### ISSUE TITLE
News module  error 500 

### ISSUE THREAD

**Issue by neurobug** [luyadev/luya#1234]
### What steps will reproduce the problem?

I've installed  news module, create command, migrate and then import
I've opened the admin panel, set permissions and then open news module
I clicked in categories and  ok, I clicked in news and I got 500 error

### What do you get instead? (A Screenshot can help us a lot!)

![screen shot 2017-03-14 at 7 50 40 pm](https://cloud.githubusercontent.com/assets/1685789/23928741/8cf1b482-08ef-11e7-82a3-b5b146be642b.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.0-RC2
| PHP Version      | PHP 5.6.30
| Platform         | Apache
| Operating system | OSX

**Comment by neurobug** [comment]
I was comparing the luya files against the downloaded files using:

"composer create-project luyadev/luya-kickstarter:1.0.0-RC2"

Seems like some files are missing...

![image](https://cloud.githubusercontent.com/assets/1685789/23934020/58ef03b2-0910-11e7-97f8-9ac639f68f79.png)

**Comment by nadar** [comment]
@neurobug What version of the news module have you chosen? It the core, admin and cms are rc2 you have to use rc2 as well for the news. We have made some significant changes in the next release and renamed and reorganized a lot of classes and files, so i assume this is why you get this exception.

**Comment by neurobug** [comment]
I did a fresh install last night, using the latests versions of everything..

**Comment by nadar** [comment]
ok, so it works now? (otherwise show me please your composer.json).

**Comment by neurobug** [comment]
Ok, I've recently run the composer tool, and now the error 500 is gone
