### ISSUE TITLE
Page properties values unset

### ISSUE THREAD

**Issue by JDL747** [luyadev/luya#1239]
Page properties are being unset if I change view in the admin… for ex. if I go the system page and return back to page content, my page properties are no longer there...

### What steps will reproduce the problem?
1. Set page properties in cms admin
2. Save
3. Navigate to another view. For ex. System
4. Return to page properties

### What is the expected result?
Showing Page properties values

### What do you get instead? (A Screenshot can help us a lot!)
Page properties values are being reset

![screen shot 2017-03-18 at 18 41 14](https://cloud.githubusercontent.com/assets/3844254/24074517/a07c8fb8-0c0a-11e7-9b31-9074a304602f.png)

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))
1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] '1'
3: [ini_get('error_reporting')] '22519'
4: [phpversion()] '5.6.25'
5: [php_ini_loaded_file()] '/Applications/AMPPS/php/etc/php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.23 (Unix) PHP/5.6.25 mod_wsgi/3.5 Python/3.5.2 OpenSSL/1.0.1p'

### Additional infos
| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.0-dev
| PHP Version      | 5.6
| Platform         | Apache/Ampps
| Operating system | OSX

**Comment by nadar** [comment]
@JDL747 Please run composer update within the next minutes to check if your bug is fixed. thanks for the report
