### ISSUE TITLE
Admin Interface rendering problem when using the Portuguese language.

### ISSUE THREAD

**Issue by rodzadra** [luyadev/luya#1242]
### What steps will reproduce the problem?
Enter the administrative interface, click on your profile and change the language to "Portuguese".

### What is the expected result?
The interface was expected to render normally.

### What do you get instead? (A Screenshot can help us a lot!)
![luya_problema_interface](https://cloud.githubusercontent.com/assets/936497/24109899/d41e0af6-0d70-11e7-9e41-8daac76bd906.png)

### Additional infos
This error only happens when we pass the interface to Portuguese. The other languages are correct.

| Q                | A
| ---------------- | ---
| LUYA Version |  ^1.0@dev  
| PHP Version   |  5.6.12 
| Platform         | Apache 2.4.16/MariaDB 5.5.43
| Operating system | GNU/Linux Slackware 14.0

**Comment by nadar** [comment]
@rodzadra True, i can confirm this strange behavior. I am going to investigate on this! Thanks

**Comment by nadar** [comment]
@rodzadra Take a look at the commit above, there was a problem with the html from the translation. thanks for the report.

**Comment by rodzadra** [comment]
@nadar You did it. Thank you!
