### ISSUE TITLE
The CMS is not displaying the icons with the flags signaling some languages.

### ISSUE THREAD

**Issue by rodzadra** [luyadev/luya#1243]
### What steps will reproduce the problem?
Access "System" -> "Languages" and add new languages:

Name: Portuguese
Short Code: pt

Name: Spanish
Short Code: es
.... 

### What is the expected result?
When you register a language in the CMS, icons with their flags should be displayed. However, the languages below are not:

- Portuguese;
- Spanish;
- Ukrainian;
- Greek;
- Vietnamese;

### What do you get instead? (A Screenshot can help us a lot!)
You get the description name instead of the flag icon.

![luya_problema_bandeiras](https://cloud.githubusercontent.com/assets/936497/24124709/cbea763e-0da3-11e7-9cb8-7b5ef5c14e51.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | ^1.0@dev 
| PHP Version      | 5.6.12
| Platform         | Apache 2.4.16/MariaDB 5.5.43
| Operating system | GNU/Linux Slackware 14.0

**Comment by nadar** [comment]
@TheMaaarc I think it would make sense to integrate the flags for all default admin languages.

**Comment by rodzadra** [comment]
@nadar Don't you think it would make more sense to integrate all the flags? For example, I can use the admin interface in one language (eg English) and have multiple versions of my page in others languages (eg Chinese, German, Arabic, etc).

**Comment by TheMaaarc** [comment]
@rodzadra I enabled all flags. If one is still missing we need to add it, open a new issue if thats the case. Thanks. 👍

**Comment by rodzadra** [comment]
@TheMaaarc Thank you! :+1:
