### ISSUE TITLE
Error on move menu items

### ISSUE THREAD

**Issue by rodzadra** [luyadev/luya#1247]
### What steps will reproduce the problem?

On admin interface, create two (or more) pages at root level and try to move one of them.

### What is the expected result?

The menu is expected to be rearranged.

### What do you get instead? (A Screenshot can help us a lot!)

An 500 internal error:

`GET http://anpec_new.dev/luya-kickstarter/public_html/admin/api-cms-navitem/move-to-child?droppedOnItemId=13&moveItemId=15 422 (Found URL alias duplication in drop target "".)
`

![luya_move_menu_2](https://cloud.githubusercontent.com/assets/936497/24245864/6029d64a-0fa3-11e7-8295-f6aaa5c46437.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | ^1.0@dev
| PHP Version      | 5.6.12
| Platform         | Apache 2.4.16/MariaDB 5.5.43
| Operating system | GNU/Linux Slackware 14.0

**Comment by rodzadra** [comment]
@nadar, this fix the problem, but i can't move one child menu to root. Is this the correct behavior?

**Comment by nadar** [comment]
@rodzadra i assume this is fixed as well since yesterday, please run composer update. If not please create an issue with the error message. thanks for you reports, this is very important for us.

**Comment by nadar** [comment]
(it should be possible to move items back to the root)

**Comment by rodzadra** [comment]
Oops! Yes, it was fixed after updating. Sorry! Thank you again!
