### ISSUE TITLE
Link Type radio button not showing selection

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#1249]
### What steps will reproduce the problem?

Click on a radio button to define a link as internal or external.

### What is the expected result?

The radio button should show the selection.

### What do you get instead? (A Screenshot can help us a lot!)

The radio button not showing the selection:

<img width="320" alt="link" src="https://cloud.githubusercontent.com/assets/3786245/24335215/8bc5aec2-1279-11e7-8263-e6c674e8fa34.png">

**Comment by nadar** [comment]
latest build? inside the modal?

**Comment by rolandschaub** [comment]
Yes, 1.0.0-dev, and yes, both inside and outside the modal.
