### ISSUE TITLE
Error in CheckboxRelation when using getter function and labelTemplate

### ISSUE THREAD

**Issue by martinpetrasch** [luyadev/luya#1250]
### What steps will reproduce the problem?
Create Two Models
Create CheckboxRelation between both models with a labelField-Array:
```'labelFields' => ['title', 'targetName']```
and a labelTemplate:
```'labelTemplate' =>  '%s (%s)'```

Create your own Getter in the other Relation Model:

```
public function getTargetName()
{
   return $this->target->title;
}
    
public function getTarget()
{
  return $this->hasOne(MediationTarget::class, ['id' => 'target_id']);
}
```

### What is the expected result?

You should get the specified labels *title* and *targetName* (via defined getter)

### What do you get instead? (A Screenshot can help us a lot!)

Server 500 Error.
If you remove the *TargetName* in the labelTemplate (second *%s*), you will get a response again. The error seems to be originated in the CheckboxRelation line 206 from the "vsprintf":
```
message:	vsprintf(): Too few arguments
file:	vendor/luyadev/luya-module-admin/src/ngrest/plugins/CheckboxRelation.php
line:	206
requestUri:	/admin/api-kmb-mediationpackage/services
serverName:	kunstmuseumbasel.ch
date:	30.03.2017 09:56
```

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
@martinpetrasch We have dropped the ActiveQuery and replace with an Array only response, therefor you where unable to access the getter method of the ActiveRecord Object. You can achieve the same output by using the closure ability, from the docs:

```php
'labelFields' => function($model) {
     return $model->firstname . ' ' . $model->lastname;
}
```

this will replace using the labelTemplate attribute.

**Comment by TheMaaarc** [comment]
@nadar Shouldn't that be documented in the https://github.com/luyadev/luya/blob/master/UPGRADE.md Markdown?
Or did I just don't see it?

**Comment by nadar** [comment]
@TheMaaarc you are right, usually i am going to write the upgrade document short before the next release.
