### ISSUE TITLE
Group permission. Modal window empty

### ISSUE THREAD

**Issue by rodzadra** [luyadev/luya#1253]
### What steps will reproduce the problem?

Go to System -> Groups menu. Click on the "Permissions" button of the Administrator user.

### What is the expected result?

A modal window to manage permissions.

### What do you get instead? (A Screenshot can help us a lot!)

An empty modal window.
![luya_permissions](https://cloud.githubusercontent.com/assets/936497/24523740/7b7969a2-156a-11e7-86c7-f446c92d5e5b.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | ^1.0@dev
| PHP Version      | 5.6.12
| Platform         | Apache 2.4.16/MariaDB 5.5.43
| Operating system | GNU/Linux Slackware 14.0

**Comment by nadar** [comment]
Can confirm this, the wrong hash is used for the active window object or wrong calculated. Thanks!
