### ISSUE TITLE
Problems with luya-module-news

### ISSUE THREAD

**Issue by nandes2062** [luyadev/luya#1256]
### What steps will reproduce the problem?
After installing Module-News from
Https://github.com/luyadev/luya-module-news, after creating the view and creating the page of the module news, I get error.

### What is the expected result?
To enter news entry button

### What do you get instead? (A Screenshot can help us a lot!)
![enter image description here](http://i65.tinypic.com/2mzirs7.jpg)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | RC2
| PHP Version      | 7.1
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
Have you run the migrate command? Could you please send me a screenshot of the XHR response (which throws the 500 internal server).

**Comment by nandes2062** [comment]
I followed the steps of the installation, the migration and the import of the module.
Here the internal error:
![enter image description here](http://i64.tinypic.com/r0bjug.png)

**Comment by nandes2062** [comment]
![enter image description here](http://i67.tinypic.com/f1cxzp.png)

**Comment by nadar** [comment]
it seems like the news module or the admin, cms, core are not the same version, use the RC2 version for news module as well, or upgrade your project to the latest dev-master for all packages. After the first stable release this will not be a problem anymore.

**Comment by nandes2062** [comment]
Thank you very much Nadar, I worked correctly.
