### ISSUE TITLE
Does not display the Htmlblock preview

### ISSUE THREAD

**Issue by nandes2062** [luyadev/luya#1269]
### What steps will reproduce the problem?
The use of HtmlBlock, does not render the view of the html, only shows its html code.
This problem was generated after upgrading to version RC3

### What is the expected result?
A preview of the html generated in the HtmlBlock block.

### What do you get instead? (A Screenshot can help us a lot!)
You do not get a preview of the generated html.
![enter image description here](http://i67.tinypic.com/1zd0ryc.jpg)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | RC3
| PHP Version      | 7.0.15
| Platform         | Apache
| Operating system | Ubuntu 16.4

**Comment by nadar** [comment]
@nandes2062 We have disabled the rendering inside the admin - as its intended to be used for the frontend and not the admin part. What is your use case? Maybe we could make a config variable to allow rendering in the admin.

**Comment by nandes2062** [comment]
For example, when I generate a map with Google Map made with JavaScript API, I add it with an object tag, to add it in an html block and admin users can interact on their map, both frontend and admin.

**Comment by nadar** [comment]
Ok. I am going to reenable the rendering of the html block with an option to disable. Sorry for breaking your work.

**Comment by nandes2062** [comment]
muchas gracias @nadar
