### ISSUE TITLE
Admin UI Design Workshop

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1292]
Ideas and communication details for admin ui design workshop (May 2017).

Give the UI Components a name, with a screenshot in order to talk about "the same thing". (Main Navigation, Context Menu, Sidebar, etc.)

Ideas/Inputs:

+ Context Menu could be clickable, like the main menu on YouTube, so its like an overlay menu and does not takes space on smaller screens.
+ Main Navigation on the left Side, Context Menu next to the Main Navigation: http://wrapbootstrap.com/preview/WB0696K5S or http://yima-v1.0.1.s3-website-us-east-1.amazonaws.com/angular/index.html#/widgets/panel
+ Material Design Inputs: http://byrushan.com/templates/material-admin/1.8.1/angular2/

Changes:
+ Remove Materialize
+ Move to Bootstrap 4

**Comment by dev7ch** [comment]
https://carrd.co/

A clean and very pretty website builder from html5up with a smart admin interface
