### ISSUE TITLE
Number of entries displayed in CRUD list view

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#1304]
### What steps will reproduce the problem?

Display a CRUD list view with active paging in LUYA administration:

![crud entries](https://cloud.githubusercontent.com/assets/3786245/25939627/c5635dc2-3633-11e7-867b-47fee40e73fd.png)

### What is the expected result?

Above the list it should display the total number of records, or something like:  
entries 1-100 of 2'438

### What do you get instead? (A Screenshot can help us a lot!)

The number of entries displayed per page.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.0RC3

**Comment by nadar** [comment]
@rolandschaub Well, in your case this is true as it should display the total count, but also the row count of the current table. Maybe it should be 100/1000 ?

**Comment by rolandschaub** [comment]
Or, as I suggested: 1-100 of 2'438. The "1-100" part gives you an idea on what page you are,

**Comment by nadar** [comment]
But how would you display the current row count when typing?

**Comment by rolandschaub** [comment]
When typing, the row count is reset as typing results in new data that is displayed from page 1.

Example:
Search term: "mil", after switching to page 2:
101-200 of 478

Extending search term to: "miller":
1-100 of 132

**Comment by nadar** [comment]
i believe tha pagination information is less intresting, so i made something in between it shows now 

X of Y (100 of 1000) 

when typing the left number always returns the current amount of rows the right number displays the total count.
