### ISSUE TITLE
URLManager does not set menu item as active in CMS context

### ISSUE THREAD

**Issue by jkabat** [luyadev/luya#1315]
### What steps will reproduce the problem?
I have created several module pages, but none is selected in menu when I access it. It may be some misunderstanding on my side.

- Yii2 url manager route: site/account/update-profile
- in CMS admin I have created following structure:
root module page: account (navigation contains link to /account)
child module page: update-profile (navigation contains link to /account/update-profile)
... more childs
- without urlRules set in module, I see content of "site/default/index"
- with following urlRules, Im not browsing pages in CMS context and therefore menu is not handled correctly:
```
        ['pattern' => 'account', 'route' => 'site/account/index'],
        ['pattern' => 'account/update-profile', 'route' => 'site/account/update-profile'],
        ['pattern' => 'account/change-password', 'route' => '/site/account/change-password'],
```

### What is the expected result?

When I go to /account, account menu item will be selected in appropriate menu container.

### What do you get instead? (A Screenshot can help us a lot!)

Home page is preselected, current menu is not detected correctly and I cant reach account childs.

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))
```
1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] ''
3: [ini_get('error_reporting')] '22527'
4: [phpversion()] '5.6.13-1~dotdeb+7.1'
5: [php_ini_loaded_file()] '/etc/php5/apache2/php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.2.22 (Debian)'
```

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  master
| PHP Version      | 5.6
| Platform         | Apache
| Operating system | Debian

**Comment by nadar** [comment]
hi @jkabat - I am not sure to understand what you are trying to do. Are those pages

+ account
+ account/profile

Modules? Do they contain the module block? 

Cause you could just create a page controlled by a module (a module page) and add url rules to this module, so you don't have to create sub pages like `profile` within the cms.

**Comment by jkabat** [comment]
As I said - It was my misunderstanding... module blocks were exactly what I was looking for. Haven't tried them before - I thought setting page as module will be enough.

What is the purpose of module page? Its only for modules which contain one default controller and action?

Closing.

**Comment by nadar** [comment]
When you have your own module you can either choose to use the module block or define a page as module. Difference:

Module block

> If you're using the module block to render the frontend module, you can place other blocks above and below because you're in the CMS context. This is most useful for simple modules which have only one view (i.e. a simple form). If you're linking a details view inside the module view, you'll not leave the page and detail view will get rendered in the same block. Another disadvantage is the static URL to the page. No matter what you're doing in the module block view, the site URL won't change as you're still in the context of the CMS page where you've placed the module block.

Define page as Module

> Using a Frontend Module offer all possibilities: you can define your own layout, you've full control of the URL routes and you've control over the whole page not just a part of it (from setting the page title tag to defining all detail views).

Ref: https://github.com/luyadev/luya/blob/master/docs/guide/lesson-module.md

For us its very important to get feedback from you, if something is not clear just ask me so i can extend the guide. Or of course you can extend the guide by yourself by sending a Pull Request.

**Comment by jkabat** [comment]
Thanks for the link. Lessons are not yet available in guide on the main site.

**Comment by nadar** [comment]
Yes, the guide is currently synced according to the current release candidate, after the final release 1.0.0 the guide will be always sync with the github docs.
