### ISSUE TITLE
Suspicious lines in test

### ISSUE THREAD

**Issue by samdark** [luyadev/luya#1316]
### What steps will reproduce the problem?

- https://github.com/luyadev/luya/blob/master/tests/core/HookTest.php#L113
- https://github.com/luyadev/luya/blob/master/tests/core/HookTest.php#L118

### What is the expected result?

No idea.

### What do you get instead? (A Screenshot can help us a lot!)

Value with the key `test` is overwritten immediately.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
This is what the test is testing `testIterationOverrideKey` but i could i assume it would be enough to have only 1 an array on each function. Thanks

**Comment by samdark** [comment]
That's regular PHP behavior. Does it make sense to test it?

**Comment by nadar** [comment]
As the HookEvent object implements ArrayAccess i just wanted to make sure the overriding works. I think it does not hurt :-)
