### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by tomoat** [luyadev/luya#1335]
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by nadar** [comment]
hi @tomoat, seems to be a dependency from fabpot/goutte, i will upgrade the package to the latest version. thanks for the report

**Comment by nadar** [comment]
This is a require-dev only dependency problem from the coveralls php coverage tool: https://github.com/php-coveralls/php-coveralls/issues/203

So if they fix it (create new release), it will be fixed here too :-)

**Comment by globian** [comment]
i clone new release, unfortunatly i have alway dependecy error:  Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by nadar** [comment]
hi @globian - its just a warning right? not an error? could you show me your composer.json? thanks for the report

**Comment by globian** [comment]
Hi nadar it was warning, but i see this warning if i run that: **composer -vvv require luyadev/luya-module-cms:~1.0.0**

**Comment by nadar** [comment]
What if you also add `--no-dev`?
