### ISSUE TITLE
CMS Admin: Toggleable Sidebars

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya#1336]
On my notebook i have less space for the content editing, because the two sidebars on the left and right take much space. 
What do you think about a toggle button for it? Maybe with an automatic toggle when i hover to the side of the page?
Also i have 3 scrollbars (2 for each sidebar and 1 for page), wich takes valuable space too.

regards
boehsermoe

**Comment by nadar** [comment]
Hi @boehsermoe, we are currently working on the new admin interface. If you like you can take an early look at the new-admin-ui branch (https://github.com/luyadev/luya/tree/new-admin-ui) and give us feedback. The menubar's should be toggleable when finished and save the state in the user settings (maybe also the browser storage so you can have the settings independent on your device).

So lets keep the issue open and take as "requirement" for admin ui redesign. Thanks for the feedback!

**Comment by boehsermoe** [comment]
Hi @nadar, the new interface look great! Will it be released with the version 1.0 of luya?

**Comment by nadar** [comment]
Yes, maybe we will add a quick release before 1.0 in order to get feedback and find latest bug on new admin ui.

**Comment by dev7ch** [comment]
The toggle feature for the mainnav is now available the new admin ui

**Comment by nadar** [comment]
i am going to close this issue, if there are any further ideas regarding responsive / layout / mobile / small screens, please create a new issue based on the new admin UI.
