### ISSUE TITLE
Console: Proxy sync throws error

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1343]
I wanted to enjoy the super cool admin/sync command but i didn't get satisfied ;)
Any ideas?

Exception 'yii\base\InvalidParamException' with message 'Syntax error.'

in /Users/silvan/Sites/_luya/kmb-neu/vendor/yiisoft/yii2/helpers/BaseJson.php:132

Stack trace:
#0 /Users/silvan/Sites/_luya/kmb-neu/vendor/yiisoft/yii2/helpers/BaseJson.php(106): yii\helpers\BaseJson::handleJsonError(4)
#1 /Users/silvan/Sites/_luya/kmb-neu/vendor/luyadev/luya-module-admin/src/commands/ProxyController.php(183): yii\helpers\BaseJson::decode('<!DOCTYPE HTML ...')
#2 [internal function]: luya\admin\commands\ProxyController->actionSync()
#3 /Users/silvan/Sites/_luya/kmb-neu/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /Users/silvan/Sites/_luya/kmb-neu/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#5 /Users/silvan/Sites/_luya/kmb-neu/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#6 /Users/silvan/Sites/_luya/kmb-neu/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#7 /Users/silvan/Sites/_luya/kmb-neu/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('admin/proxy', Array)
#8 /Users/silvan/Sites/_luya/kmb-neu/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('admin/proxy', Array)
#9 /Users/silvan/Sites/_luya/kmb-neu/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#10 /Users/silvan/Sites/_luya/kmb-neu/vendor/luyadev/luya-core/base/Boot.php(170): yii\base\Application->run()
#11 /Users/silvan/Sites/_luya/kmb-neu/vendor/luyadev/luya-core/bin/luya(21): luya\base\Boot->applicationConsole()
#12 {main}

**Comment by nadar** [comment]
I assume u have entered a wrong admin proxy url. Https? with/without www?

**Comment by nadar** [comment]
or you are not running the same version as the version (make sure u run composer install first).

**Comment by dev7ch** [comment]
ok thx, composer install done ... i ll check the urls later

**Comment by nadar** [comment]
And keep in mind its just the server url like: https://yourproxywebsite.com without /admin ;-)

**Comment by nadar** [comment]
and you should also be able to run the command in verbose mode, so u got more details on what went wrong while connecting to the proxy

**Comment by dev7ch** [comment]
finally after admin/proxy/clear and new setupfor proxy sync all went fine ...
its fixed so far, thx
