### ISSUE TITLE
Define 'self' model for plugin 'selectModel' return error

### ISSUE THREAD

**Issue by dven84** [luyadev/luya#1356]
### What steps will reproduce the problem?
```
public function ngRestAttributeTypes()
    {
        return [
            'title' => 'text',
            'parent_id' => [
                'selectModel',
                'modelClass' => self::className(),
                'valueField' => 'id',
                'labelField' => 'title',
            ],
        ];
    }
```
### What do you get? 
error 500
![error](https://user-images.githubusercontent.com/10542161/28288807-e3612b82-6b59-11e7-9929-895c29ddc8c5.png)

###
Adding `if (isset($this-> data))` to `luya\admin\ngrest\plugins\Select` `onAfterListFind($event)` solves the problem

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.0-RC3

**Comment by TheMaaarc** [comment]
Thanks for reporting, we will look into your issue as soon as possible.

**Comment by nadar** [comment]
@dven84 I have fixed this problem when using the same model as target class, there was also another problem with this kind of use case! thank you
