### ISSUE TITLE
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.

### ISSUE THREAD

**Issue by bumbumpaw07** [luyadev/luya#1378]
- Installing luyadev/luya-module-remoteadmin (1.0.0-RC3): Downloading (100%)         
Package herrera-io/version is abandoned, you should avoid using it. No replacement was suggested.
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files

| LUYA Version     | RC3
| PHP Version      | 5.6.29
| Platform         | XAMP
| Operating system | CentOs

**Comment by nadar** [comment]
i am not sure which packages has this depencie.

**Comment by nadar** [comment]
Maybe its related to #1335 but i don't think so. @bumbumpaw07 could you please remove the vendor folder and run composer install again and copy the whole installation log.
