### ISSUE TITLE
Users: Checkbox "Send account information to user"

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#1381]
Add a checkbox "Send account information to user". If checked, automatically send a mail with user, password and URL Information to the created user.

![image](https://user-images.githubusercontent.com/3450438/28878819-bd374e7a-77a0-11e7-9395-37135d0db595.png)

**Comment by TheMaaarc** [comment]
Oder ein Button in der Übersicht (CRUD View)?

**Comment by nadar** [comment]
Good idea with the checkbox! I think the CRUD view button would have another function like: send reset token ... something like this
