### ISSUE TITLE
Invalid URL generation with offline pages in path

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#1382]
### What steps will reproduce the problem?

Make a web page with children offline. URLs to the child pages won't be formed correctly – LUYA will omit all path segments except the one for the target page. Example:

www.testsite.com/abc/def/ghj  
will turn to the following when the page with the path segment "def" is offline:  
www.testsite.com/ghj

### What is the expected result?

The URL should include all path segments, including the ones of offline pages:  
www.testsite.com/abc/def/ghj

Of course, the URL www.testsite.com/abc/def/ should still throw a 404 error, but www.testsite.com/abc/def/ghj should work and be generated correctly.

**Comment by nadar** [comment]
This is because offline pages wont be load into the menu component in order to reduce memory usage. Maybe those pages could be loaded too when your are logged in as admin, or what also would be the use case to have those urls - Most of the time you will use the preview button which generates a preview url.

**Comment by rolandschaub** [comment]
If you want to test the cross-linking between offline/new pages, it would be necessary to have the correct URLs generated. I would prefer to always get the correct URLs, but at least when logged in as an admin, as you proposed.

**Comment by nadar** [comment]
@rolandschaub I am still thinking about this. Are you sure this is really something we should investigate on? In your case you should just make the parent page invisible but not offline. Or could you make a valid use case where it makes sense to make a page offline but allow users to see its children pages? Cause then my proposed solution wont change anything.

**Comment by rolandschaub** [comment]
I think this is still an important topic: The URL of a page should not be dependent on the activity state of its parents. If a parent page for some reason has to be deactivated, its childrens URLs should not change.
