### ISSUE TITLE
Filter not applied when returning to CRUD view

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#1392]
### What steps will reproduce the problem?

Select a filter in a CRUD view, go to different view and return to CRUD view.

### What is the expected result?

The selected filter should be remembered and applied.

### What do you get instead? (A Screenshot can help us a lot!)

The filter is still selected but no applied anymore:

![filter-problem](https://user-images.githubusercontent.com/3786245/29404198-b85c1f70-833a-11e7-9223-a88e027e6212.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | Dev Master
| PHP Version      | 7.0.20
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
Apply filter after $timeout in order to ensure digest lifecycle
