### ISSUE TITLE
Multiple Inputs - Sorting affect button caption

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1401]
If the multiple input group contain file upload field there is a little bug with the caption of the file upload button after sorting the input groups.

![multi_inputs_file_btn_caption_bug](https://user-images.githubusercontent.com/15183757/29658188-5d0524a2-88ba-11e7-8d79-9504c37f345d.gif)

It doesnt affect the file after save, its just what you see while editing isnt correct.

**Comment by nadar** [comment]
i am not sure what you mean, i can not see what happens? what is expect, what happens instead? sorry

**Comment by dev7ch** [comment]
have a look at the last button, it should remain "Datei auswählen" but it takes the caption from above

**Comment by nadar** [comment]
The empty file upload ability should not be sortable.
