### ISSUE TITLE
iPad Chrome Overflow(?) Issues

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1409]
iPad Chrome: We have experience very strange behaviors on iPad with chrome: sometimes it scrolles inside the curd, sometimes not, sometimes the mobile nav is static on top, sometimes not... maybe test with a real device. flexbox related?

I assume its a problem with the overflow:hidden. This should be disabled on mobile devices as you can make touch gestures every where.

**Comment by dev7ch** [comment]
its moved to Done, can we close it @nadar ?

**Comment by nadar** [comment]
The project ist closed, the issues still exists. therefore: no
