### ISSUE TITLE
Filter remembered but not applied when returning to CRUD view

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#1429]
### What steps will reproduce the problem?

Select a filter in a CRUD view. Klick on another menu item in the navigation and get back to the CRUD view.

### What is the expected result?

The filter is still selected and applied.

### What do you get instead? (A Screenshot can help us a lot!)

The filter is still selected but not applied any more.

Selecting filter:
![filter 1](https://user-images.githubusercontent.com/3786245/29963540-84bb3902-8f07-11e7-9b9f-b2102ee23505.png)

Returning to CRUD view:
![filter 2](https://user-images.githubusercontent.com/3786245/29963547-8d3bb958-8f07-11e7-8359-3b41c6922d41.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  Dev Master
| PHP Version      | 7
| Platform         | MAMPP
| Operating system | OSX

**Comment by nadar** [comment]
duplicated https://github.com/luyadev/luya/issues/1429
