### ISSUE TITLE
Suggestion: Improve admin mobile view of main nav and module nav

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1439]
In the mobile admin view:
- It would be helpful if the module nav is open by default (maybe not in all cases) and the mainnav closed (as it is).

- whats about putting the icons before the left title of current location in the mobile main nav?

**Comment by dev7ch** [comment]
![image](https://user-images.githubusercontent.com/15183757/30002372-0335f1e0-90a8-11e7-8f8b-c93ad014e521.png)

**Comment by dev7ch** [comment]
or what great would be to have and html storage save for the toggle state.

icons ideas: for toggle open could a tack (not found on material icons :( )

**Comment by nadar** [comment]
I am not sure what you mean. From your screenshot: you would like to have the dashboard icon next to the Dashboard title?

**Comment by dev7ch** [comment]
next to "Account" i would be nice to have thethe account icon from the mainnav
