### ISSUE TITLE
In new admin UI mouse scrolling in Mozilla Firefox does not work

### ISSUE THREAD

**Issue by dven84** [luyadev/luya#1454]
In new admin UI mouse scrolling in Mozilla Firefox does not work

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | RC4
| Mozilla Firefox Version     | 55
| Operating system | Windows

**Comment by nadar** [comment]
Everywhere? Or just in a special context? The scrollbars are hidden, but you sould still be able to scroll.

**Comment by nadar** [comment]
@dven84 I can confirm this behavior on OSX Version 55.
