### ISSUE TITLE
Grouping fields in the form is missing

### ISSUE THREAD

**Issue by dven84** [luyadev/luya#1455]
### What steps will reproduce the problem?

![image](https://user-images.githubusercontent.com/10542161/30097638-0b237ccc-92f8-11e7-87c9-aac41e9ba902.png)

### What is the expected result?

![image](https://user-images.githubusercontent.com/10542161/30097607-da6f0a06-92f7-11e7-9ee7-114619de3ef6.png)

### What do you get instead? 
![image](https://user-images.githubusercontent.com/10542161/30097653-19dfeb56-92f8-11e7-9a9f-4b2a209363aa.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  RC4

**Comment by nadar** [comment]
Thanks @dven84

**Comment by nadar** [comment]
@TheMaaarc old code: https://github.com/luyadev/luya/blob/old-admin-ui/modules/admin/src/views/ngrest/crud.old.php#L171
