### ISSUE TITLE
Admin: Login screen autofill ( Chrome)

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1460]
if ur login data is provided from stored data, autofill ( in Google Chrome ) the label of the password field doesnt move above the input field.

![image](https://user-images.githubusercontent.com/15183757/30170015-436fefc4-93ee-11e7-9967-7789dd3e884b.png)

**Comment by vishub** [comment]
same issue in firefox

**Comment by dev7ch** [comment]
sorry, but it isn´t working properly, Firefox and Opera nothing works nothing anymore ;)

![image](https://user-images.githubusercontent.com/15183757/30297357-d093e8fe-9747-11e7-94d0-81eaae64e191.png)

i am working on a fix for that.

**Comment by nadar** [comment]
I can confirm, it still does not work, see https://github.com/luyadev/luya/pull/1481 but this PR does not fix the problem as well.
