### ISSUE TITLE
Admin: Extend page width for drag 'n drop area

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1462]
There are cases where the drag n drop area width is to small, e.g. if you open 2 translations on a mac book its quite uncomfortably to use and edit blocks.

There for i would like to suggest the implementation of a toggle function similar to the main nav on the left side for the blockholder.

![image](https://user-images.githubusercontent.com/15183757/30182832-85ec1d9e-9418-11e7-97bc-32e0d02c0761.png)

**Comment by nadar** [comment]
yes, i was thinking of something like this as well, the main question is: would it still be possible to drag blocks from the blockholder or not?

**Comment by dev7ch** [comment]
yes, it would be possible to drag ´n drop also if only icons are visible.

What i am not sure about is the implementation of a tooltip, but there is a way i guess.
