### ISSUE TITLE
Suggestion: tide up buttons and infos above drag 'n drop area

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1463]
![image](https://user-images.githubusercontent.com/15183757/30185728-f98aff04-9422-11e7-9979-9d9f61053067.png)

If i look at this section it appears unsorted to me, at least a little bit.

The following arragement could help and improve the usability and design:
![image](https://user-images.githubusercontent.com/15183757/30185967-e950e882-9423-11e7-8037-d6576d1fe837.png)

Any ideas or inputs?

**Comment by nadar** [comment]
@dev7ch this wont work as its a different level of "information". 

settings button on top right: contains nav settings
settings button next to language: contains nav item settings (which is a relation item between language and nav) so this is why the button (etc.) must be place in the foreach of the admin languages.

**Comment by dev7ch** [comment]
mmh, ok i see. Actually i don´t have an better idea for now, i will carry this with me. 

You could close this issue or wait for a better input.
I still think this section could be done a bit more clear.
