### ISSUE TITLE
Admin: List dropdown position of right toggler chevron

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1464]
![luya_list_dropdown](https://user-images.githubusercontent.com/15183757/30187065-62299ce6-9428-11e7-9353-aa7625132f80.gif)

In my opinion its not correct, that the X replaces the chevron after the selection.

**Comment by nadar** [comment]
what would you suggest then? do we have already a similar use case?

**Comment by dev7ch** [comment]
I suggest that the chevron should remain on its position, the close X left next to it, not right, quick fix.

A prime solution would be to bound the X the the selected term, e.g. 2spalten. 
This would open us the opportunity to use this nice list dropdown for checkbox arrays ( multiple selection) in future.

**Comment by dev7ch** [comment]
and yes we have used this dropdown list often, which is haveing the same behaviour

**Comment by nadar** [comment]
i thinking switching X and chevron would be a good a solution. i am not even sure how comfortable it would be to have the X to the current selected list, assume u have a list with 50 entries.

**Comment by dev7ch** [comment]
the icon positions are fixed in the pending PR, i assume the multiple selections is an other issue, this could be closed;

**Comment by nadar** [comment]
Thanks for fix but it still looks the same...

![image](https://user-images.githubusercontent.com/3417221/30313148-a258ac90-979c-11e7-8422-9b45f1a1f2dc.png)
