### ISSUE TITLE
Luya Executable Symlink

### ISSUE THREAD

**Issue by rainerCH** [luyadev/luya#1465]
Corrupt on my Installation

![image](https://user-images.githubusercontent.com/12884243/30210398-d4935f0a-949c-11e7-8f16-dc116b183413.png)

**Comment by nadar** [comment]
The symlink is created when luya composer plugin is installing the package, maybe i have to drop this feature as it wont work when the file is commited (like in your case). Only git ignore could fix that problem temporary.

**Comment by nadar** [comment]
closing this issue as the luya bin file is now on the ignore liste
