### ISSUE TITLE
UX Improvement - Logout Option

### ISSUE THREAD

**Issue by leninhasda** [luyadev/luya#1467]
Right now I have to go to profile page to logout, which isn't very user friendly. Logout button should be easy to find and not to far away.

### What is the expected result?
Here is how bitbucket does it without increasing the number of icon in left menu bar. 
![expect](https://user-images.githubusercontent.com/3797647/30214412-35ae1736-94ce-11e7-8d67-478936e158ff.jpg)

### What do you get instead? (A Screenshot can help us a lot!)

![current](https://user-images.githubusercontent.com/3797647/30214396-224c62d8-94ce-11e7-81d2-518ab50ccd12.png)

**Comment by nadar** [comment]
i like that idea a lot! what do you think @luyadev/coredev?

**Comment by dev7ch** [comment]
i agree too, we going to keep this input for our next improvements for the main nav.

Thanks for reporting!

**Comment by TheMaaarc** [comment]
I like it too. I guess we could show the gravatar image of the user or if there is none just the default user icon. For now we would have, like @leninhasda suggested, the buttons "Profile" and "Log out".

**Comment by nadar** [comment]
So lets take this into the next relase. Regarding the profile image see #1472 :-)

**Comment by dev7ch** [comment]
![image](https://user-images.githubusercontent.com/15183757/30654852-827f20d6-9e2f-11e7-89b7-564b3f8a1bc8.png)

So, lets clearify what we gonna do here:

- implementing a profile image into the user profile?
- moving profile related menu items into big tooltip? lets make a list below
- open big tooltip on hover?
- regarding "Online Users" tooltip in tooltip? really?

**Comment by nadar** [comment]
Its good idea to make a mockup first, thanks @dev7ch - lets talk about the look in the look&feel section below

## Function

+ user image: no we are skipping this idea, as long its not possible to upload the image in the admin self, it would expose data from an admin url to other servers (like gravatar) we should avoid this. Maybe once we introduce luyadev.io where you can register, upload image etc. like on gravatar. until then: no user image
+ User Menu contain: Change Password, Update Infos (or sth like this), Logout
+ on hover, like the users online as well.
+ Users Online will remain as it is, but will have the same still as the new "context menu".

## Look & Feel of new Context Menu

+ Maybe not black, as it has nothing to do with tooltips
+ Creating a new generic "context menu" we can also for "Users Online" (without clicking, but displaying data.)

Ideas for the look and feel? Mockups?

**Comment by nadar** [comment]
@luyadev/coredev We should progress in this issue, in order to have enough time to test the new context menu and find bugs.

**Comment by dev7ch** [comment]
Beginning with this User menu items:

- Online Users
- Preferences ( link to current user profile admin page)
- Logout ( remove from current user profile admin page)

I believe it could be a bit overloaded if we create a 2 level context menu here

**Comment by dev7ch** [comment]
![user_panel](https://user-images.githubusercontent.com/15183757/31856203-b6f4ef7c-b6bb-11e7-97f7-1c922acf58f5.gif)

Or just let the user online panel where it is now.

What you think?

**Comment by dev7ch** [comment]
I think as well we could get rid of the icons inside the user profile panel.

**Comment by nadar** [comment]
@dev7ch i like your preview, and yes: account preferences and logout is enough for the moment.

could you please send a PR? We should trigger a class in order to display the context menu then we can use:

ng-click (for mobile usage)
ng-mouseover and ng-mouseout

**Comment by dev7ch** [comment]
Ok, fine.

we should use as well a `ng-class` for the parent mainnav item "Profile"  if `templateUrl` is `admin/account/dashbboard` is active.

Do you have a hint for this?

Because now its not a link anymore any `ui-sref-active` option cann´t ne used anymore.

**Comment by nadar** [comment]
Ok, i will take care of this then.

**Comment by dev7ch** [comment]
Further sth about the style architecture:

for "Users Online" and "Profile" the element "mainnav-tooltip-big" is used, so its related to `mainnav`.

Now I think it might be better to move this into in more independent element like `context-menu` so that it safely used everywhere in the admin interface ( in direction of the idea you mentioned above).

**Comment by nadar** [comment]
Feel free to change, a more element based structure makes sense, i assume.

**Comment by nadar** [comment]
What i think is way more important: document such elements in the admin guide or they must be bootstrap4 components. Does boostrap does not provide such a component?

**Comment by dev7ch** [comment]
It doesn´t like like thats it´s provided from bootstrap, yes there is the `dropdown` but its not satisfying for a multi level context  usage.

https://github.com/twbs/bootstrap/issues/21026 

Anyhow in case this would be a new issue. 

I ll send the PR quickly.

**Comment by nadar** [comment]
@dev7ch changes looks good to me, thanks! i assume we will need to improve the mobile menu experience in future.

**Comment by dev7ch** [comment]
@nadar sure, i think too, its a basic implementation.

maybe for mobile just as a collapsed item with a chevron.

**Comment by nadar** [comment]
agree, yes good solution. or maybe on mobile just display the logout button, as it's quite important.
