### ISSUE TITLE
trying to access /admin/group/index

### ISSUE THREAD

**Issue by hdushku** [luyadev/luya#1469]
### What steps will reproduce the problem?
trying to access:
https://domain.com/luya-kickstarter/public_html/admin/group/index

and the same error goes when I try to access:
Users
Groups
Languages
Tags

### What is the expected result?

and shows 500 internel server error

Error: [$compile:tpload] http://errors.angularjs.org/1.6.7-build.5456+sha.3651e42/$compile/tpload?p0=admin%2Fgroup%2Findex&p1=500&p2=Internal%20Server%20Error
    at main.js:7
    at main.js:161
    at main.js:136
    at m.$digest (main.js:147)
    at m.$apply (main.js:150)
    at l (main.js:102)
    at K (main.js:107)
    at XMLHttpRequest.A.onload (main.js:108)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
what luya version? Did you login sucessfull? what webserver are u using? could you post me a screenshot of the xhr request (like from the developer toolbar in chrome, i assume the bearer token is missing, but i am not sure). What Browser are u using?

**Comment by hdushku** [comment]
Latest version from:
https://luya.io/guide/install
On
c9.io
Yes I installed and loged in succesfully 
![screenshot_1](https://user-images.githubusercontent.com/8830905/30240017-66967524-9568-11e7-8a58-f31f510c54e8.jpg)

**Comment by nadar** [comment]
ok i assume what could happen there. Is it possible that you set YII_DEBUG to true in your config and also change the error report to display everything or do you get any response from this 500 internal pages?

Thanks for the report!

(btw: are you developing inside c9 env and this is a preview of the site or are using it as a host?)

**Comment by nadar** [comment]
i just teste to run on c9.io as well, its a problem with php short open tag which is not enabled by default on your apache, but of course this should not be a required. So i pushed a fix for this problem. 

Change your composer json to require latest dev-master

```json
"require": {
        "luyadev/luya-core" : "^1.0@dev",
        "luyadev/luya-module-admin" : "^1.0@dev",
        "luyadev/luya-module-cms" : "^1.0@dev"
},
```

and run composer update in 10 minutes (after that the subsplit has pushed to latest code to all repos).

**Comment by nadar** [comment]
@hdushku i tested on my c9 ide and it works fine after the update. Thanks for the report!
