### ISSUE TITLE
Admin UI action columns breaking in crud table

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1470]
Inside a CRUD view with 3 buttons (the active window has a label) the buttons a breaking the row. 

Maybe we could use a dropdown on a "small" screen? Any other idea?

<img width="1032" alt="bildschirmfoto 2017-09-09 um 20 22 44" src="https://user-images.githubusercontent.com/3417221/30242754-bb842e08-959c-11e7-91cd-bfa664e18e7f.png">

**Comment by nadar** [comment]
Any inputs @luyadev/coredev ?

**Comment by martinpetrasch** [comment]
Good idea! Maybe something like this?

![](https://pre03.deviantart.net/707b/th/pre/f/2013/112/b/6/comet_admin_interface_v2_by_eggzy-d62m4ur.png)

**Comment by dev7ch** [comment]
@martinpetrasch looks like very clean and clear inferface to me.

but we have table cells with long text.

Generally i would suggest: stop using html tables to avoid styling mess ;) 

In this case we could also move the "Description" behind an icon wich shows desc up on hover. 
So it would prevent the table get broken by different sizes of desc.

What u think? replace Desc with icon and button? desc shows on hover?

**Comment by nadar** [comment]
@dev7ch we can talk about not using tables, but thats another topic i assume.

@martinpetrasch i like the idea, this would also work for tables with even more buttons.

**Comment by dev7ch** [comment]
Whats about move the "Description" behind an icon and label wich shows desc up on hover.

**Comment by nadar** [comment]
you mean using tooltips?

**Comment by dev7ch** [comment]
Yes

**Comment by TheMaaarc** [comment]
I feel like @martinpetrasch's idea/example was the best so far. I guess we should implement it like that.

We need to use tables or we will have problems with width and flexible columns. Maybe we could solve those issues with flexbox, but for now it works perfectly fine like it is. It's still worth looking into for the future.

**Comment by dev7ch** [comment]
yes, ok fine let´s go :)

but please have a look at the image, a quick visualization what i meant before:
![image](https://user-images.githubusercontent.com/15183757/30290681-8e126d78-9730-11e7-9809-9353d1e8d03d.png)

I still believe it is needed to move the description into a tooltip, so thatr we never have two lines inside a table row.

**Comment by nadar** [comment]
@dev7ch i don't think this is a good solution. And we are in crud context, so what columns would you hide when having 10 columns? makes no sense to me. Lets take @martinpetrasch idea. The more important question for me is: based on what rules can we apply such a "buttons toggler"? on specific screen size? check if there is enough space? see if there is a line break, if yes, how?

**Comment by TheMaaarc** [comment]
I think we should just always have that toggler and let it expand on hover. 
**IF** we only want to show it under certain circumstances, I would vote for the "not enough space" condition.

**Comment by dev7ch** [comment]
ok

**Comment by dev7ch** [comment]
@marc i think as well always having a toggler is most clean solution

@nadar but:
> so what columns would you hide when having 10 columns? 

I don´t think that we have 10 colums with **10 description** fields.
Usually there is always one short info in a table field, execpt from descriptions.

if we would store descriptions always in tooltips it could help to tide up the table in the admin UI

anyhow, maybe i am missing sth, i am exicted we we are going to have here in future.

**Comment by nadar** [comment]
@dev7ch your proposed solution is not possible with a generic system like ngrest crud, we can not just hide things if they are "descriptions". We are looking for a system wide generic solution as mentioned in the topic of this issue, therefore @martinpetrasch solution fits perfect.

@TheMaaarc i dont think we should ALWAYS make a "dropdown"/"toggler" button, this would be a pain for users, as they have to click/hover twice as much on every action.

**Comment by dev7ch** [comment]
![image](https://user-images.githubusercontent.com/15183757/30340136-ccebb51a-97f1-11e7-8b5d-2003afbeaa78.png)

i guess the plus icon in the pic above is a expand all options.

maybe we could use click instead of hover toger with the expand all option

**Comment by nadar** [comment]
no, i think the plus icon shows you the form to add a new row/record.

**Comment by dev7ch** [comment]
ok, yes but there would be space for an expand all option

**Comment by nadar** [comment]
i don't think there is need for just another icon. hovering over the expand button allow you to trigger the action buttons.

**Comment by nadar** [comment]
dev master standpoint:

Maybe the dark background is to heavy, maybe no background required at all:
<img width="589" alt="bildschirmfoto 2017-10-01 um 10 54 14" src="https://user-images.githubusercontent.com/3417221/31053154-ff8b13ae-a696-11e7-83cc-1eb1f524e84f.png">

The example from @dev7ch does the same.
![image](https://user-images.githubusercontent.com/15183757/30340136-ccebb51a-97f1-11e7-8b5d-2003afbeaa78.png)

I assume the problem on the "on hover" state is, the div does not know the height of the row in order to make a smooth overlay?
<img width="338" alt="bildschirmfoto 2017-10-01 um 10 54 24" src="https://user-images.githubusercontent.com/3417221/31053153-ff8acf3e-a696-11e7-892b-817276f6c99e.png">

**Comment by nadar** [comment]
@TheMaaarc On mobile devices we could maybe use: https://docs.angularjs.org/api/ngTouch
