### ISSUE TITLE
Admin UI: Dropdown select overlay z-index

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1480]
### What steps will reproduce the problem?

open 2 dropdown selections

### What is the expected result?

close other open dropdowns ( i guess its easier then deal with the z-indexes)

### What do you get instead? (A Screenshot can help us a lot!)
![dropdown_selections](https://user-images.githubusercontent.com/15183757/30290583-256465ec-9730-11e7-903f-60173a5c3e0c.gif)

**Comment by nadar** [comment]
@luyadev/coredev How can we fix this problem?

**Comment by dev7ch** [comment]
close other open dropdowns is a new dropdown is going to be open

**Comment by nadar** [comment]
maybe this could be a solution, yes. But this would be general, as we have no "form" context, the form input directives have no context to where they are currently used.

**Comment by nadar** [comment]
@dev7ch i just pushed a fix, please update to the latest dev-master and test if the solution works. If your problem is fixed please close this issue.

**Comment by dev7ch** [comment]
I can confirm it´s resolved, now other open dropdown are closing, tested on latest chrome.
