### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#1489]
Style the checkboxes to match the radio boxes.

Fix the error on the group edit page.  
![image](https://user-images.githubusercontent.com/3450438/30313118-840dc02c-979c-11e7-9940-30b4d9ad01d7.png)

**Comment by martinpetrasch** [comment]
I guess this also covers the error with the checkbox relations?

![bildschirmfoto 2017-09-18 um 14 15 37](https://user-images.githubusercontent.com/6354795/30541538-2fe20492-9c7c-11e7-887f-53ac53c31204.png)

**Comment by TheMaaarc** [comment]
Yes
