### ISSUE TITLE
Log dashboard $first and $last line

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1491]
Check with angular for $first and $last and modify the LINE as it should stop on the icon. I mean it should have a start and an end. :-)

![image](https://user-images.githubusercontent.com/3417221/30318094-66e105ee-97ac-11e7-9735-26eb2ed60bab.png)

**Comment by TheMaaarc** [comment]
Personally I like it without a start and an end. Time has no start or end either - so why should our timeline have one?

**Comment by nadar** [comment]
For me it looks like its not finished and for this time period (day) there is a start and end.

@luyadev/coredev inputs?

**Comment by martinpetrasch** [comment]
I think with a defined start point it would look better:

![](https://i.pinimg.com/736x/78/59/2d/78592d97f2980dd9bc3bc4cfafc85536--design-timeline-interface-design.jpg)

But I also think it would make more sense to not show a defined start point unless there is one (only visible when there are a few entries).

The last log entry could be highlighted by making the point a little bit bigger?
