### ISSUE TITLE
Filemanager tables in modal not responsive, wrong table headers

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1498]
### What steps will reproduce the problem?

Add file or img in block.

![image](https://user-images.githubusercontent.com/15183757/30389860-6b447540-98b4-11e7-93c0-1af7f9ec174c.png)

### What is the expected result?

- table not cutted, table scrollable
- table head captions of should match whats it says

And i think the link or set file should not only be first colums.

better would be if it works on **checkbox, image, name and type**

### What do you get instead? (A Screenshot can help us a lot!)

see above image.

**Comment by nadar** [comment]
1. maybe apply table-responsive would do the trick?
2. clickable: since @TheMaaarc has made the image preview on hover, i agree with you but before it was a pain to see the image in large.

**Comment by dev7ch** [comment]
i am working on a fix for that
