### ISSUE TITLE
Using general cards group styles in search bar

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1508]
Please use the styles from the crud card toggler inside the search panel as this is then a generic element and provides a consitent look and feel.

old

![image](https://user-images.githubusercontent.com/3417221/30634476-87f1d1a2-9def-11e7-8914-2618631e9ea7.png)

cards block element

![image](https://user-images.githubusercontent.com/3417221/30634536-bbb287e8-9def-11e7-9696-24b834091069.png)

**Comment by dev7ch** [comment]
i would like to mention to have a look at the[ reverted PR](https://github.com/luyadev/luya/pull/1485).

the code quality needs to be improved. 
It would make sense to take that reverted PR as  starting point.

**Comment by nadar** [comment]
@dev7ch we have cards, we should use them, this allows use to have a persistent look and feel. Please lets NOT discuss about old and reverted PR.

**Comment by dev7ch** [comment]
it was a mention, nothing to discuss
