### ISSUE TITLE
Optimize responsive tables

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1509]
### What steps will reproduce the problem?
In Luya Admin navigate to News > Categories and open e.g. Chrome inspect element toolbar

this happens on a 15" screen (macbook), if page width is less then 1280px

### What is the expected result?

![image](https://user-images.githubusercontent.com/15183757/30636812-c30543f8-9df6-11e7-97df-caa1ce4690f1.png)

### What do you get instead? (A Screenshot can help us a lot!)

![image](https://user-images.githubusercontent.com/15183757/30636623-50567318-9df6-11e7-9a0b-84b875ebb914.png)

This comes from the bs4 css class `table-responsive` usually its haves an effect under breakpoint sm ( less then 768px )

In compiled luya css we have 

```css
@media (max-width: 1280px) {
    .table-responsive {
     ...
    }
}
```

Why do we have this up to 1280px @luyadev/coredev ? is bootstrap overwritten for this case?

### Suggested Solution

We should wrap tables into a div like:

```html
<div class="table-scrollable">
    <table class="table"></table>
</div>
```

and add a styling like:

```css
.table-scrollable {
    width: 100%;
    overflow-x: scroll;
}
```

This would give us a much more suitable control to responsive tables.

If it tables would be wrapped we could use the style `display: inline-table` for  `table` to fix this issue.

The table wrapper could be also applied via js, just instead of add it manually in every html files.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev-master

**Comment by nadar** [comment]
@dev7ch As far as i can see, we should keep the table="table-responsive" and optimize this class instead of adding something new. this way developers does not have to find some *misc luya bs4 features* somewhere.

+ optimize the table-responsive class
- do not add new wrapping class (we also would have to add them everywhere!)

**Comment by dev7ch** [comment]
the bs4 `table-responsive`isn´t the best solution for responsive tables, if u search a bit on the web u ll quickly get it.

1. actually its not more optimizable, we could only reduce the breakpoint, but i guess there is a reaseon why the breakpoint was changed

2. wrapping could be done via js or jquery, so developers use this feature just on the flow

**Comment by nadar** [comment]
+ we will *not* work with additional wrappers, this should work out of the box according to bs4 usage guide
+ we are using angular, maybe you can watch all tables which habe the class table-responsive and wrap them but currently i am not sure how to watch all tables without creating an directive you have to apply on all tables.

**Comment by dev7ch** [comment]
- ok, but the case i meant is *not* at Bootstrap tutorial, and does *not* work out of the box (tested on bs4 docs website)

- sure, agree we have to check properly

explanation:

if we have a `table-responsive` wich contents are less then 100% width the table isn´t stretched as it should.

This can be only done with a wrapper as a far i can see.

**Comment by nadar** [comment]
@TheMaaarc so we should take care of this problem, maybe we can only use this wrapping div for the CRUD table?

**Comment by nadar** [comment]
@TheMaaarc Please add this table-responsive wrapper informations to the docks.

**Comment by nadar** [comment]
@dev7ch @TheMaaarc keep the issue open for a while so we can test the changes and see if some unexpected behaviors appear.

**Comment by nadar** [comment]
Chromium, Ubuntu: Now i have a scrollbar on each ngrest crud table

![screenshot from 2017-10-05 15-59-20](https://user-images.githubusercontent.com/3417221/31231109-2f2be500-a9e6-11e7-871e-606c18e3db8d.png)

**Comment by dev7ch** [comment]
👍
