### ISSUE TITLE
Admin UI: Page tree is not clickable

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1510]
### What steps will reproduce the problem?

1. create a new page in luyadev 
2. try to click a new created, not published page in the page tree

### What is the expected result?

should be selectable.

### What do you get instead? (A Screenshot can help us a lot!)

![page_tree_issue](https://user-images.githubusercontent.com/15183757/30713763-acbc80dc-9f10-11e7-9ca6-2620618c9550.gif)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev master

**Comment by nadar** [comment]
@dev7ch this is due to your cms permission restrictions ;-)

**Comment by dev7ch** [comment]
Oh, upps.
