### ISSUE TITLE
Firefox: Drag'n'Drop doesn't work

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#1512]
Firefox version: 55.0.3
Mac OS: macOS Sierra 10.12
LUYA Version: dev-master

![drag_n_drop_ff_55](https://user-images.githubusercontent.com/3450438/30743051-4cfb59ca-9f9c-11e7-8c25-474ef963aaad.gif)

**Comment by nadar** [comment]
@TheMaaarc Please try latest dev-master and close the issue if its fixed. thanks

**Comment by TheMaaarc** [comment]
Works for me.
