### ISSUE TITLE
Block CLI generation: Adding multiple Inputs field, improve readability of var types

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1516]
### What steps will reproduce the problem?

1.) generate a block with the command `./vendor/bin/luya cms/block/create`

2.) adding vars and try to find the very usefull `multiple-input` field type

### What is the expected result?

haveing sth like `multiple-input` in the variable type list

### What do you get instead? (A Screenshot can help us a lot!)

![image](https://user-images.githubusercontent.com/15183757/30785457-3357958e-a167-11e7-9de1-6cbd344e8232.png)

### Additional infos

i am still unhappy with the readability and selection of the variable types, we really should improve that.

https://github.com/yiisoft/yii2-app-advanced/blob/master/init#L29

![image](https://user-images.githubusercontent.com/15183757/30785691-0fc5a576-a16b-11e7-8bfb-98e430052114.png)

i am pretty sure we could make var types selectable via numbers as they do in the yii2-advanced-template.

typing the name of the variable type is definately not user friendly.

| Q                | A
| ---------------- | ---
| LUYA Version     | dev master

**Comment by nadar** [comment]
I just added the missing types.

Unfortunaly the http://www.yiiframework.com/doc-2.0/yii-helpers-baseconsole.html#select()-detail select console helper would then display only the numbers. So it would be

Variable Type [1,2,3,4,5,6,7,?]:

What is definitely less user friendly then current solution.

**Comment by dev7ch** [comment]
Thanks for adding.

ok, agree... i ll keep looking around for better possible solution

**Comment by dev7ch** [comment]
https://github.com/luyadev/luya/blob/0ccb97105e5aace05921f64efa780cf7e6055add/modules/cms/src/frontend/commands/BlockController.php#L175

i guess there is a misspelling: `multiple-inpus`

**Comment by nadar** [comment]
I saw it directly after that commit, its already fixed.

**Comment by dev7ch** [comment]
good, maybe it wasn´t referenced.

But please reopen this issue, its not properly fixed and i found a solution.

**Comment by dev7ch** [comment]
1: `radios` looks like a double entry
https://github.com/luyadev/luya/blob/master/modules/cms/src/frontend/commands/BlockController.php#L132

**Comment by dev7ch** [comment]
2: `multiple-inputs`should also be in the `getVariableTypesOptions()` function

https://github.com/luyadev/luya/blob/master/modules/cms/src/frontend/commands/BlockController.php#L179

**Comment by dev7ch** [comment]
3: make variable type selectable via number

**Comment by dev7ch** [comment]
![block_cli_2](https://user-images.githubusercontent.com/15183757/30826445-f0f432ee-a236-11e7-8fbe-d705c8a84a50.gif)

@nadar Bääm ;)

**Comment by nadar** [comment]
Helper: This requires a whole new way of defining config variables otherwise the helper class would not help anything. Its still an array with defintion, so its nothing which would make creating those inputs faster.

**Comment by dev7ch** [comment]
1: good
2: please add default/ example value as its done with other

3: make the Helper helpful

I think its not closed this issue, please reopen

**Comment by dev7ch** [comment]
@luyadev what do you think?

**Comment by nadar** [comment]
2. see my answer above
3. add another issue which determines only this problem.

**Comment by dev7ch** [comment]
ok i ll split the issue and reopen them as new ones
