### ISSUE TITLE
FileHelper::ClassInfo() regex not coping with windows newlines with XAMPP

### ISSUE THREAD

**Issue by tskodaw** [luyadev/luya#1517]
### What steps will reproduce the problem?
* have windows7 and xampp 7.1.8
* get luya-kickstarter and deps from master via composer with min-stability : "dev"
* apply config to config-files
* on cli do **php luya migrate**
* on cli do  **php luya import** or **php index.php import**

### What is the expected result?
correct program termination.

### What do you get instead? (A Screenshot can help us a lot!)

```
F:\xampp7\htdocs\luyacomposertest\public_html>php index.php import
Exception 'ReflectionException' with message 'Class \AudioBlock does not exist'

in F:\xampp7\htdocs\luyacomposertest\vendor\yiisoft\yii2\di\Container.php:424

Stack trace:
#0 F:\xampp7\htdocs\luyacomposertest\vendor\yiisoft\yii2\di\Container.php(424): ReflectionClass->__construct('\\AudioBlock')
#1 F:\xampp7\htdocs\luyacomposertest\vendor\yiisoft\yii2\di\Container.php(364): yii\di\Container->getDependencies('\\AudioBlock')
#2 F:\xampp7\htdocs\luyacomposertest\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('\\AudioBlock', Array, Array)
#3 F:\xampp7\htdocs\luyacomposertest\vendor\yiisoft\yii2\BaseYii.php(348): yii\di\Container->get('\\AudioBlock', Array, Array)
#4 F:\xampp7\htdocs\luyacomposertest\vendor\luyadev\luya-module-cms\src\admin\importers\BlockImporter.php(105): yii\BaseYii::createObject(Array)
#5 F:\xampp7\htdocs\luyacomposertest\vendor\luyadev\luya-module-cms\src\admin\importers\BlockImporter.php(63): luya\cms\admin\importers\BlockImporter->createBlockObject('\\AudioBlock')
#6 F:\xampp7\htdocs\luyacomposertest\vendor\luyadev\luya-module-cms\src\admin\importers\BlockImporter.php(92): luya\cms\admin\importers\BlockImporter->saveBlock('\\AudioBlock')
#7 F:\xampp7\htdocs\luyacomposertest\vendor\luyadev\luya-module-cms\src\admin\importers\BlockImporter.php(38): luya\cms\admin\importers\BlockImporter->saveBlockByPath('F:\\xampp7\\htdoc...')
#8 F:\xampp7\htdocs\luyacomposertest\vendor\luyadev\luya-core\console\commands\ImportController.php(157): luya\cms\admin\importers\BlockImporter->run()
[...]
```
## Comment
basic problem:
in luya-core FileHelper::ClassInfo() line 82, the regex 
```
if (preg_match('#^namespace\s+(.+?);$#sm', $phpCode, $m)) {
```
does not match windows newlines (CRLF), at least on my xampp-installation , 
changing it to:
```
if (preg_match('#^namespace\s+(.+?);\r?$#sm', $phpCode, $m)) {
```
solved the situation and worked fine on linux too, 

additionally:
perhaps in luya-module-cms\BlockImporter::saveBlock
an error handling could be fine when BlockImporter::saveBlockByPath calls it with insufficient class name?
```protected function saveBlock($fullClassName)
    {
        // ensure all classes start with trailing slash class name definition like `\foo\bar\Class`
        $fullClassName = '\\'  . ltrim($fullClassName, '\\');
        $model = Block::find()->where(['class' => $fullClassName])->one();
        
        $blockObject = $this->createBlockObject($fullClassName);
...
```

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | master-branch
| PHP Version      | 7.1.8
| Platform         |  XAMPP 7.1.8
| Operating system | Windows7

**Comment by nadar** [comment]
thank you @tskodaw this is a very good input. I am going to add some test cases and add your fix thank you!

What would be an example for insufficient class name?

**Comment by nadar** [comment]
@tskodaw i just pushed a fix, could you please try again with the latest dev-master on luya-core?

**Comment by tskodaw** [comment]
@nadar works fine for me under win7 "Importer run successfully" :)

for BlockImporter::saveBlock($fullClassName) -> insufficient as testcase would be just `\AudioBlock` , without the namespace, which lead to the Exceptions

**Comment by nadar** [comment]
I think this could be dangerous as its possible to have such a namespace and is therefore not invalid.

**Comment by tskodaw** [comment]
hmm good point, 
perhaps in a future version handling the exception in saveBlock and saying Importer run unsuccessfull on class xyz please check you configuration at package abc

**Comment by nadar** [comment]
I know what you mean. The problem is that every module or application can attache classes to the importer process as its very common routine, so therefore we can not stop, but maybe adding a hint "block importer has warning(s) XYZ" or sth like this. I am waiting for the yii2 console table output helper (which should released soon) then i will rewrite things anyway.

Thanks again for your report.
