### ISSUE TITLE
Encoding problem when editing page title

### ISSUE THREAD

**Issue by apychan** [luyadev/luya#1518]
### What steps will reproduce the problem?
Edit page title which is not ASCII.

### What is the expected result?
The words that entered.

### What do you get instead? (A Screenshot can help us a lot!)
![image](https://user-images.githubusercontent.com/1445817/30846536-042f5ac2-a2d3-11e7-9ade-4b7232e83e19.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  dev
| PHP Version      | 7.0.17
| Platform         | Apache+nginx
| Operating system | Centos7

**Comment by nadar** [comment]
What was your input? What is written in Database?

**Comment by apychan** [comment]
I was input 即將開放
And database record is ????

I find a solution
Set cms_nav_item.title collation to utf8_general_ci, and edit the title again
LUYA can display normally

**Comment by nadar** [comment]
That would have been my next guessing. always use utf8_general_ci for database charset.

So we can close this issue?

**Comment by apychan** [comment]
Agree to close
