### ISSUE TITLE
zaaSelect empty entry

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#1520]
First entry should always be `<option disabled selected value>-- select an option --</option>`.

If the select has no value or the user clicks the "remove selection" button (cross icon on the right) the select should show the first entry.

**Comment by nadar** [comment]
> If the select has no value or the user clicks the "remove selection" button (cross icon on the right) the select should show the first entry.

@TheMaaarc i don't think this should be the default behavior, as long as initValue is **not** provided, it would not be possible to reset a selected state (like reset model to null). Maybe if there **is** an initValue it should always reset to the given initValue.

**Comment by TheMaaarc** [comment]
True story, makes sense.
