### ISSUE TITLE
NgRest Text and Textarea auto encoding

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1522]
The text and textarea plugins will now auto encode html output on after find, this may cause into problems with existing implentations are handing json trough textarea or text plugin!

In order to fix that use 

```php
['text', 'encoding' => false], // ['textarea', 'encoding' => false]
```

in order to disable encoding

**Comment by dev7ch** [comment]
Does this mean that an <a href="">blah</a> would work anymore in the textarea block too?

**Comment by dev7ch** [comment]
i guess it would be possible for particular cases with `['textarea', 'encoding' => true]`

- in some cases it it usefull to use html in a textarea block instead of adding an extra html block
- even in some title field where one word is bold is html needed in a text field

**Comment by nadar** [comment]
Yes ngrest plugins text and  textarea will encode the html output, but before parsing the markdown syntax.

you can either disable this behavior with `'encoding' => false` or us the Html plugin.

The implementation of such a feature helps us prevent xss attacks when working with user input.

**Comment by dev7ch** [comment]
ok thank you.
