### ISSUE TITLE
IE10 optimization

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#1529]
Current IE10 view:

![image](https://user-images.githubusercontent.com/3450438/31067545-b9e5590a-a753-11e7-8fbd-ba802fdce0bb.png)

Will try to add some small fixes to restore usability in IE10.

**Comment by dev7ch** [comment]
@theMaaarc there was a quite similiar behaviour on Safari.

https://github.com/luyadev/luya/blob/cbb0bc8164f5c310639fcc035f4225272e9fee53/modules/admin/src/resources/js/controllers.js#L904

There is a small script already for browser detection, this may could help you

**Comment by TheMaaarc** [comment]
**General**
- [ ] Page scrolls horizontal (because of mainnav)

**Mainnav**
- [ ] Middle section floats over top section
- [ ] Footer section is below the entire page (and uses full width)
- [ ] If open: Labels floats over icons

**CMS**
- [ ] Blocks floats over Blockholder
- [ ] Drag'n'Drop doesn't work
- [ ] Auto-Preview has no height and floats over page toolbar

**CRUD**
- [ ] Toggler height is wrong

**Fileadmin**
- [ ] Folder toggler not on same line as label
- [ ] No edit / delete icons (probably being forced on a new line)
- [ ] Labels do not break if too long
- [ ] Big spacing between folders, probably because of the edit / delete icons

**Directives**
- [ ] zaaDateTime: hours and minute have different heights

**Comment by nadar** [comment]
Customer Input:
![ieerror](https://user-images.githubusercontent.com/3417221/31880659-7d8e7312-b7e1-11e7-8d89-3943edd77fdf.jpg)

(waiting for ie version informations, will udpate this comment asap)

**Comment by dev7ch** [comment]
https://github.com/luyadev/luya/blob/master/modules/admin/src/resources/scss/components/_mainnav.scss#L426

Browser specific adjustments for Safari has been made here, but i looks like that this isn´t used anymore? 

```html
<body flow-prevent-drop="" class="safari-11.0 mac-os-10.12.6 " ng-class="{'debugToolbarOpen': showDebugBar}"> ... </body>
```

**Comment by nadar** [comment]
@TheMaaarc i assume u have introduce the browser detect change, maybe adjust the above mentioned problem?

**Comment by dev7ch** [comment]
I was just wondering where are the browser specific styles are and why those from above aren´t used or adjusted.

**Comment by TheMaaarc** [comment]
All IE related issues mentioned here are resolved.
