### ISSUE TITLE
How edit template in cms-module

### ISSUE THREAD

**Issue by Wofik29** [luyadev/luya#1533]
### What steps will reproduce the problem?
Admin panel -> pages -> Create new page -> set "As template" is "yes",  "Use Template" is "No", select my layout and click "Save new page".
I go to Admin panel -> pages -> Templetes and click on new page "Edit".

### What is the expected result?
I expected to see the selected layout same in edit something page.
Example:
![luya1](https://user-images.githubusercontent.com/15027768/31211811-95fe5320-a9b5-11e7-9829-3513c7f4f022.png)

### What do you get instead? (A Screenshot can help us a lot!)
But I see the blank page, layout does not render: 
![luya2](https://user-images.githubusercontent.com/15027768/31211822-a10837b8-a9b5-11e7-941b-f297689c82ee.png)

Layout in the second screenshot is same as in the first screenshot.

I'm doing something wrong?  How do I fill a template?
Or the template is edited differently?

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))
1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] '1'
3: [ini_get('error_reporting')] '22527'
4: [phpversion()] '7.0.22-0ubuntu0.16.04.1'
5: [php_ini_loaded_file()] '/etc/php/7.0/apache2/php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.18 (Ubuntu)'

### Additional infos
I looked debug tool in chromium, and I see, that data layout has come, but not render. And nothing error in console.

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.0-RC4
| PHP Version      | PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

**Comment by nadar** [comment]
hi @Wofik29 thanks for the report, this is indeed a bug. You have to choose the version (first version) in the version dropdown inside the draft page, then you can add blocks and edit the draft and re used it later.

**Comment by nadar** [comment]
@Wofik29 i just pushed a fix, if you like you can install the latest dev-master in order to test. thanks for the report
