### ISSUE TITLE
Invalid path alias: @vendor\luyadev\installer.php

### ISSUE THREAD

**Issue by kakadanhem** [luyadev/luya#1537]
Trying to install Luya on Windows. When run `php index.php migrate` it show error message: `Invalid path alias: @vendor\luyadev\installer.php`

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  LUYA RC4
| PHP Version      | 7.1.9
| Platform         | Wampserver
| Operating system | Windows

**Comment by nadar** [comment]
hi @kakadanhem could you please try to use the latest dev-master? https://luya.io/guide/install-problems#require-the-dev-master remove the vendor file and run composer update again?

**Comment by kakadanhem** [comment]
It's working now after change the require

**Comment by nadar** [comment]
perfect, yes i assume we fixed that already, so i am going to close this issue. thanks for the report
