### ISSUE TITLE
Installing latest RC4 version on windows generates errors

### ISSUE THREAD

**Issue by jerryasih** [luyadev/luya#1539]
### What steps will reproduce the problem?
Follow the setup instructions for windows

### What is the expected result?
A working kickstarter app

### What do you get instead? (A Screenshot can help us a lot!)
First, at the end of the installation there is an error exception. "Cannot create symlink, error code 1314"
Then when I try to run any console command "health, migrate etc," I get another exception "Invalid path alias"

![screenshot 7](https://user-images.githubusercontent.com/21135654/31392759-fcccae60-add1-11e7-842f-97c2d70446ac.png)

![screenshot 8](https://user-images.githubusercontent.com/21135654/31392304-d4ac8e06-add0-11e7-9a78-44bdedd565d0.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.0-RC4
| PHP Version      | 7.0.10
| Platform         | WAMP
| Operating system | Windows

**Comment by nadar** [comment]
hi @jerryasih this is already fixed, please try to install the latest dev-master.

1. https://luya.io/guide/install-problems#require-the-dev-master
2. remove vendor folder
3. composer update
4. run migrate and import again.

**Comment by jerryasih** [comment]
Works now. Thank you.
