### ISSUE TITLE
Admin UI: improve page version dropdown content view

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1545]
### What steps will reproduce the problem?

head over to the page editing section in the admin and toggle the page version dropdown when the blockholder is collapsed.

### What is the expected result?

Version infos inside the viewport

### What do you get instead? (A Screenshot can help us a lot!)

![admin_ui_page_version](https://user-images.githubusercontent.com/15183757/31455527-21a51d94-aeb8-11e7-82ae-97a758af46f1.gif)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev master

**Comment by dev7ch** [comment]
maybe a solution would be the to make the content right aligned to the dropdown button instead of left?

**Comment by nadar** [comment]
Yes, like the crud settings button (right top) does as well.
