### ISSUE TITLE
Close CMS Menus after Save

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1562]
After saving forms in the cms nav & cms nav item settings, the modal should be closed afterwards.

+ cms nav settings
+ cms nav item settings

**Comment by dev7ch** [comment]
or maybe just add new a Button "Save and exit"?

**Comment by nadar** [comment]
I was thinking about this as well, personally i don't like to much buttons, but yes maybe "Save and Close" would be good solution as well.
