### ISSUE TITLE
Sortable Plugin Arrows

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1563]
When using the Sortable Plugin, the first down key should float right as well. 

(This was already done in RC3 but i assume the css and html markup got lost in RC4)

![screenshot from 2017-10-23 17-15-35](https://user-images.githubusercontent.com/3417221/31897235-0aef1aa2-b816-11e7-9a3b-45caf27177f0.png)

**Comment by dev7ch** [comment]
Where is  this find in the Admin UI?
Please provide a link or detailed location description.

**Comment by nadar** [comment]
sure! 

https://github.com/luyadev/luya/blob/master/modules/admin/src/ngrest/plugins/Sortable.php#L26-L27
