### ISSUE TITLE
sortRelationModel directive design

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1570]
The html markup for sortRelationModel plugin / and directive is gone since RC4

**Comment by dev7ch** [comment]
@nadar please provide a link or screenshot where this is to find

**Comment by nadar** [comment]
@dev7ch you can setup the sort relation plugin (https://github.com/luyadev/luya/blob/master/modules/admin/src/ngrest/plugins/SortRelationModel.php) on the ngrest test table module which is shipped with `envs/dev` env.

**Comment by dev7ch** [comment]
Sorry i tried several time to reproduce the error find the missing thigs, with no succes:

- please provide a screenshot what is missing and show where ( gif of jpg)

I not able to find an error, all tables work fine for me

**Comment by nadar** [comment]
@dev7ch i just restored very very basic view of sort relation array. You can now take a look at the directive at the ngrest test (envs/dev) table.
