### ISSUE TITLE
Extend CMS front-end spacing block 

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1580]
### What steps will reproduce the problem?
The `SpacingBlock` can only be used with predefined spaces, in several conditions it is needed to provide a unique space in pixels. 

### What is the expected result?

Therefore an option ( e.g. number input field) to overwrite the the predefined value by hand would be very useful.

### What do you get instead? (A Screenshot can help us a lot!)

only predefined values.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev master
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
This makes only sense for "developers"/"designers" and should not be visible for customers, as this is far to complex. Maybe it could be a CFG value, but if such situations are requested, maybe it makes more sense to create custom, project related block. 

As we plan to remove (move) the default blocks, we should maybe not add even more data.

@luyadev/coredev Inputs?

**Comment by martinpetrasch** [comment]
I also think this shouldn't be available for a normal CMS user. The frontend designer should be the one who defines the exact amount of space which fits the layout/design.

**Comment by rolandschaub** [comment]
I think it's a good idea to make it a CFG value. I also think it is a good idea to add it to the default spacing block as it makes it more flexible for special situations.

**Comment by dev7ch** [comment]
I believe there have to be a smooth way to add special spaces in some cases,
but its also right that not everyone who can move blocks should be able to use this feature.

What´s about role based access to CFG default fields? is this a possible way?

**Comment by rolandschaub** [comment]
This would be overly complicated. "Hiding" the option as a CFG value is enough. It's not a "dangerous" value that could mess ab the website.

**Comment by nadar** [comment]
Maybe we can close this is issue, as we well move this block to https://github.com/luyadev/luya-generic-blocks?

**Comment by nadar** [comment]
I am going to close this issue. We can add a new boostrap 4 spacing block with mt- mb- bs4 classes.
