### ISSUE TITLE
CLI: Turn password input during setup into hidden input

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1594]
### What steps will reproduce the problem?

In the LUYA setup during the user creation you have to enter a password wich is visible on the screen.

### What is the expected result?

The password input should not be readable and validated by a double input.

### What do you get instead? (A Screenshot can help us a lot!)

Password on the screen.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev master
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
Currently there is no such function in yii console helper, maybe create an issue here github.com/yiisoft/yii2 so other people know how to do, have already knowledge or someone could even integrate this function into the framework as it would be a good function in general.

(i just did a very quick research and could not find any good solution to fix that `password input prompt` problem)

**Comment by nadar** [comment]
Currently i have no idea how to solve and its not a security issue as your only installing/running the admin/setup command once.
