### ISSUE TITLE
Admin Javascript does not seem compatible with Firefox

### ISSUE THREAD

**Issue by cebe** [luyadev/luya#1600]
### What steps will reproduce the problem?

Using Firefox 52.4.0 on debian 8, I see the following problems:

- Login page shows E-Mail and Password over the text I type:

   ![bildschirmfoto von 2017-11-07 09-19-23](https://user-images.githubusercontent.com/189796/32483614-1887bbdc-c39d-11e7-8586-1e3c123622f0.png)

- The Admin Layout does not allow scrolling down when the content is longer than the page:

   ![bildschirmfoto von 2017-11-07 09-20-16](https://user-images.githubusercontent.com/189796/32483638-2bbc3d04-c39d-11e7-975c-24906af0aefb.png)

- Drag and Drop is not working in CMS.

When I use Chromium 57.0.2987.98 its working as expected.

I do not see any messages in Javascript console.

Do you have some minimum requirements of browser capabilities, if so which are these?

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | happens on https://demo.luya.io/ as well as 1.0.0-RC4 locally
| PHP Version      | 7.1
| Platform         | Apache, Firefox  52.4.0
| Operating system | Debian GNU/Linux

**Comment by nadar** [comment]
@cebe The Firefox (#1512) and floating label problem should be fixed in dev-master. Could you please try with `^1.0@dev` constraint?

Thank your for the report.

**Comment by cebe** [comment]
Oh sorry, have not seen these issues. Its all working with on master. Thanks for the quick response!
