### ISSUE TITLE
Admin UI: add favicon for admin interface

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1615]
### What steps will reproduce the problem?

the chrome error console shows that the favicon in the admin view is missing

### What is the expected result?

no erros

### What do you get instead? (A Screenshot can help us a lot!)

error

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev master

**Comment by nadar** [comment]
Favicon is available in kickstarter project (https://github.com/luyadev/luya/blob/master/envs/kickstarter/public_html/favicon.ico) and not a problem of admin module, i assume we can close this issue. Or did i missed something?

**Comment by dev7ch** [comment]
I mean the favicon after login into the admin area.

I tried to reproduce the console error without success but i remember in some circumstances there was an error in my chrome console.

However, the question is can we just use the LUYA logo as favicon for the admin UI to avoid emptiness?

**Comment by nadar** [comment]
I am not very used to favicons, but as far as i know: the favicon should be stored in the web accessable root folder of the domain (which is, as i mentioned above the public_html folder). Some browser are heavily caching those favicons and it could get a mess when having two favicons for the same domain.

Maybe its possible to store an admin favicon in the resources folder a define the favicon path like:

```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">
```

We can try of course. Maybe someone knows more about this? @luyadev/coredev

**Comment by dev7ch** [comment]
+ add favicon to admin/login page as well

**Comment by dev7ch** [comment]
as I understood now the favicon is project related, so i am going to close this.
