### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by coderovich** [luyadev/luya#1637]
Hello!

How to add a custom fields like "link" for my "Slider Block" that uses "image-array-upload"? I think that there is any way to combine two blocks, but how to do this for iterable objects like "image-array-upload"...
![image](https://user-images.githubusercontent.com/11044347/32646079-d40c7bbc-c5fb-11e7-921a-630f9d299dd3.png)

**Comment by nadar** [comment]
hi @coderovich 

In this case, you should use multiple input types: https://luya.io/guide/app-block-type-multiple-inputs.

**Comment by coderovich** [comment]
@nadar thx, so simply :)

**Comment by nadar** [comment]
Don't forget to use image-upload instead of image-array-upload as the iteration is now done by the multiple-inputs
