### ISSUE TITLE
"PageProperties"

### ISSUE THREAD

**Issue by coderovich** [luyadev/luya#1638]
Hello!

I can't understand how to set the PageProperties

### What steps will reproduce the problem?
I made a file as mentioned in docs:
![image](https://user-images.githubusercontent.com/11044347/32651822-4b5bc26a-c613-11e7-83f4-1622f15c24ce.png)

then import via composer...

### What do you get instead? (A Screenshot can help us a lot!)
But when i click on 3-dots button
![image](https://user-images.githubusercontent.com/11044347/32652045-171a5cfe-c614-11e7-8195-cb812ae4d4e6.png)
no properties are shown
![image](https://user-images.githubusercontent.com/11044347/32651997-e643d8ee-c613-11e7-9633-1977f8adc32f.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0 RC4
| PHP Version      | 7.1
| Platform         | Apache
| Operating system | Windows

**Comment by nadar** [comment]
run the import command

**Comment by coderovich** [comment]
@nadar of course i make the import after any changes in code, but properties still not visible

**Comment by nadar** [comment]
+ Could you please post the import command output?
+ Maybe try the dev-master by using`^1.0@dev` for the luya entries in your composer.json file.

**Comment by coderovich** [comment]
Yes, import screenshot at your disposal above :) 

I updated the CMS up to ^1.0@dev and got the error exception after the import command
![image](https://user-images.githubusercontent.com/11044347/32652697-35f593c6-c616-11e7-96e5-fc016aea0460.png)

**Comment by nadar** [comment]
i did not see the screenshot :-) sorry

Yes, there are some updates and api breaks due to very close 1.0.0 release, https://github.com/luyadev/luya/issues/1505

In your case change enableCompression to contentCompression in your config, run migrate, and import again.

**Comment by coderovich** [comment]
this screenshot is probably no longer needed :) 

I made all the steps (forgot about migration). So the last import output was:
![clip2net_171110131150](https://user-images.githubusercontent.com/11044347/32653375-bf624c60-c618-11e7-91ea-b4e01ae05462.png)
and now my property is available :) Thanks for help

And the last question please.
Is this the only approach to set up the common properties for the site? 
I mean, that if i want to set up the phone number property (globally, but editable using admin area) what is the right way to do this?

**Comment by nadar** [comment]
Currently, there is no such feature, you could use the global config params (http://www.yiiframework.com/doc-2.0/guide-structure-applications.html#params) method in your config file, or the use config model (https://luya.io/api/luya-admin-models-Config which implements registry trait) so you could do like `Config::set('phonenr', '123123123')` and `Config::get('phonenr')` which then stores data in the database, but there is CURRENTLY no ui to change those values in the admin, but we will add this in feature.

**Comment by coderovich** [comment]
Got it! Thanx for you time and help! I wish a success to your great project!

**Comment by nadar** [comment]
Inspired by your input, i am going to add this feature.

Thank you, i hope you can build your website with it, and report all bugs and feature ideas ;-)

**Comment by nadar** [comment]
https://github.com/luyadev/luya/issues/1639

**Comment by coderovich** [comment]
Of course, I will help to look for bugs in the process of developing my current project.

**Comment by nadar** [comment]
Hi @coderovich the ability to store configuration values in the admin ui is now available on dev-master. And you can retrieve them by Config::get('youridentifier');

**Comment by coderovich** [comment]
oh, cool. thx!  i'll test it )))
