### ISSUE TITLE
Containers Name

### ISSUE THREAD

**Issue by coderovich** [luyadev/luya#1640]
Hello again!
I think that in Admin UI at "Pages Section" container's roots should be named by their "Names" instead of aliases. 

In my case: 
![image](https://user-images.githubusercontent.com/11044347/32657669-a5c7142a-c627-11e7-89ec-cd28a232766a.png)

Now i have see: 
![image](https://user-images.githubusercontent.com/11044347/32657512-137c8168-c627-11e7-9480-45e48e5b6087.png)

Containers roots should be "Main menu" and "Top menu"... that would be right.

**Comment by nadar** [comment]
Fixed, thanks!
