### ISSUE TITLE
Assets: Put all web assets into a resources/dist folder instead of mapping the whole resources folder

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1641]
### What steps will reproduce the problem?

For now, the complete resources folder (including node_moduels, scss, not minified files, etc) is copied into the public Assets. This is not needed and turns your local machine into a "smoking machine" during development ( e.g. if you use assetManager -> linkAssets => true it almost burns)

### What is the expected result?

compile all needed files and folder ( e.g. local, dev, prod)  into `resource/dist` via gulp and load only the dist folder in`assets\ResourceAssets.php`

### What do you get instead? (A Screenshot can help us a lot!)

smoking mac ;)

### Additional infos

tested and works fine for me.

| Q                | A
| ---------------- | ---
| LUYA Version     | dev-master

**Comment by nadar** [comment]
You can ignore files from copy process by adding publish options, like we already did on the kickstarter project. https://github.com/luyadev/luya-kickstarter/blob/master/assets/ResourcesAsset.php#L23-L28

**Comment by dev7ch** [comment]
doesnt work with assetsManager

**Comment by dev7ch** [comment]
and the resources folder is copied anyway

**Comment by nadar** [comment]
i am not sure what it does when u use the symlink method instead, as then it does not matter anyhow. But publish options allows you to ignore files from copy process. But anyhow i assume this is not a luya related problem, its more a problem of your IDE. Or what would you suggest to fix the problem?

**Comment by dev7ch** [comment]
only map one final folder with compiled files from resources to assets, that symlinking is fine as well.

**Comment by nadar** [comment]
We could restructure the resources folder, yes. But there are more files which are required then just the compiled dist files, therefore we just define the whole resources folder so we can pick the required files from inside the folder (like images, vendorlibs, fonts, i18n files).

I assume your only problem is the node_modules folder which gets indexed by your IDE along with the vendor folders.

**Comment by dev7ch** [comment]
yes, sure as you mentioned in the final `dist` folder assets libs fonts, libs etc should be stored as well in this folder.

The problem with excluding `node_modules` from indexing in the IDE is that when symlinking is active it generates often a new folder (with hash as name) in the public assets.

so, you are right, i could or should exclude `public_html/assets` from IDE indexing too.

But i still think we could improve this a bit more so that the pubic_html/assets only contain files which are really needed. (and new luya user don´t stumble over this problem at the 1.0.0 release )

**Comment by nadar** [comment]
if symlinking is enabled, nothing gets copied at all @dev7ch

**Comment by dev7ch** [comment]
@nadar sorry, i mean a symbolic linked folder with a hashname is created in public_html/assest

**Comment by nadar** [comment]
Yes, but what is the problem with that? the node modules folder is gitignored.

**Comment by dev7ch** [comment]
![image](https://user-images.githubusercontent.com/15183757/33090054-f5ab41fe-cef2-11e7-924e-fd7428d6d8ff.png)

**Comment by dev7ch** [comment]
![image](https://user-images.githubusercontent.com/15183757/33090076-0cb5f2ea-cef3-11e7-8a7d-be183001a4b9.png)

**Comment by nadar** [comment]
yes, but what is the problem with that?

**Comment by dev7ch** [comment]
@nadar the problem that at the symlinked folders are a lot of files which are not needed.

**Comment by dev7ch** [comment]
to avoid that i would recommend to symlink a folder with only preselected and needed files.

**Comment by nadar** [comment]
this wont hurt anyone. Its your IDE which makes the trouble.

**Comment by dev7ch** [comment]
mmh, probably yes, i am not using Eclipse ;) I guess it would hurt a few other computers as well until they discover the problem.

However, if you don´t mind about it its fine for me. Maybe just ask @TheMaaarc about this before dropping this completly.
