### ISSUE TITLE
Placeholders in Blocks

### ISSUE THREAD

**Issue by coderovich** [luyadev/luya#1643]
Hello again.

Why i can't manipulate with placeholders in custom Block?

I'm trying for example show only one placeholder in the Admin UI:
![image](https://user-images.githubusercontent.com/11044347/32660946-ff69beb6-c635-11e7-8a0f-58dd2b50e66b.png)

But nothing is changed in Admin UI after import command:
![image](https://user-images.githubusercontent.com/11044347/32661041-52ce527e-c636-11e7-902a-c22bc2e368a5.png)

**Comment by nadar** [comment]
This is expected behavior. You can not change the admin recursive rendering engine, as this is a very complex process. 

The admin() method can just return block data if its not a container / placeholder block. Otherwise you would have to integrate the whole drag&drop logic for blocks.

**Comment by coderovich** [comment]
hmmm, in this way i don't understand how the default block \vendor\luyadev\luya-module-cms\src\frontend\blocks\LayoutBlock.php works... 

and shows the right grid for placeholders:
![image](https://user-images.githubusercontent.com/11044347/32661679-eb1cb9ce-c638-11e7-85e1-49802f45e9a8.png)

what should i do, if i want to make the same behavior for my custom block ?

**Comment by nadar** [comment]
Enable $isContainer (https://github.com/luyadev/luya/blob/master/modules/cms/src/frontend/blocks/LayoutBlock.php#L25). You can also provide rows and cols, in order to display a more similar frontend representation. https://github.com/luyadev/luya/blob/master/modules/cms/src/frontend/blocks/LayoutBlock.php#L71-L74

**Comment by coderovich** [comment]
that's it! 

I did everything like in the default version, but did not pay attention to cols properties...
![image](https://user-images.githubusercontent.com/11044347/32662401-75259878-c63b-11e7-97db-d5885deccc59.png)

thx again!
