### ISSUE TITLE
Javascript error in LuyaToolbar

### ISSUE THREAD

**Issue by coderovich** [luyadev/luya#1644]
Hello.

I found syntax error in frontend being i'm logged in admin.

![image](https://user-images.githubusercontent.com/11044347/32689769-555fb6b6-c6fb-11e7-8d73-6b8789f0dbb4.png)

![image](https://user-images.githubusercontent.com/11044347/32689774-67974bc8-c6fb-11e7-90e8-10cfa4a54305.png)

it's exist only if i'm authorized.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | ^1.0@dev

**Comment by nadar** [comment]
Hi @coderovich 

This is just an error of the LUYA toolbar (the arrow at the top right when logged in). You can ignore this, as its not a problem of your application. But for sure i am going to fix. thanks!

**Comment by coderovich** [comment]
yep, i understand that it's just luya's bug :) just report

**Comment by TheMaaarc** [comment]
Should be fixed. You can test it in your env and then close this issue @coderovich. Thanks. 👍
