### ISSUE TITLE
Admin UI: Login screen extension with particle canvas animation

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1648]
Include particles head animation from the new luya.io website into the login screen to get an idea about look and feel.

- improve JS of particle ( start/stop function, fade out, etc)

**Comment by nadar** [comment]
@dev7ch Maybe skip this idea and just use the new logo (with the new colors).

**Comment by dev7ch** [comment]
@nadar ok i agree, so i ll close this issue
