### ISSUE TITLE
Secure token login success icon

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1649]
When secure login is enabled, the success icon overlaps the form. (currently no screenshot as i was not fast enough to take one ;-))

**Comment by dev7ch** [comment]
sadly i am not able to setup the mail component in the configs with following informations:

        'mail' => [
            'isSMTP' => true,
            'host' => 'mail.cyon.ch',
            'username' => 'luya@dev7.ch',
            'password' => 'HIDDEN_PASWORD',
            'from' => 'you@luya.io',
            'fromName' => 'Luya Admin',
            'altBody' => 'Your HTML ALT BODY',
            'port' => 587,
            'smtpSecure' => 'tls',
            'smtpAuth' => true,
        ],

is there something wrong.
