### ISSUE TITLE
Modal doesn't scroll after two modals get closed

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#1652]
### What steps will reproduce the problem?

1. In luya/env/dev add a new block of type "Multiple Inputs Test"
2. Add enough entries so that you have to scroll (and save)
3. Set a new link on one of the entries and choose "file"
4. Now just close the 2 of the 3 modals that are open and the last one won't scroll anymore

See GIF: http://drop.marcstampfli.ch/vEw7Ey/3wTXl7xs

**Comment by nadar** [comment]
@TheMaaarc I just pushed a fix, could you please try again?

**Comment by TheMaaarc** [comment]
Looks good!
