### ISSUE TITLE
Block Assets not registered when caching is enabled

### ISSUE THREAD

**Issue by dven84** [luyadev/luya#1657]
### What steps will reproduce the problem?
`
class ExampleBlock extends PhpBlock
{
    public $cacheEnabled = true;
...
`
view:
`
CustomAsset::register($this->appView)
`

### What is the expected result?

Resources on the page

### What do you get instead? 

Resources from CustomAsset are not available on the page

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | RC4
| PHP Version      | 7.0
| Platform         | Apache
| Operating system |Linux

**Comment by dev7ch** [comment]
try `CustomAsset::register($this)` in your block view file and don´t forget to set before:
```php use app\assets\CustomAsset; ```

https://luya.io/guide/app-assets

**Comment by nadar** [comment]
@dven84 the problem is because of the caching. Disable caching when register assets (u did it correctly with $appView). Its not working as long as cache is enabled, we should fix this though.
