### ISSUE TITLE
devloping for our use case

### ISSUE THREAD

**Issue by masihfathi** [luyadev/luya#1658]
hi, i have some questions. when the first stable vesrsion release?and another question as a yii developer can i use this cms or template for my projects and add my own or our developer team to project like modules which natively develop for yii2? for example how can we extend user table or ...

**Comment by nadar** [comment]
hi @masihfathi, sorry for the late reply. 

+ first stable release will be at 12.12.2017
+ You can use all your yii widgets, extensions and modules. If you like to embed a module trough cms (like module block or module page) you should change yii\base\Module to luya\base\Module

Let me know if you have any further questions.

**Comment by masihfathi** [comment]
thanks for your reply, i really like to cooperate with your team in this project, if you have specific task for the cms that i can do it, i really like to cooperate.

**Comment by nadar** [comment]
You are very welcome to contribute code (https://github.com/luyadev/luya/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22), make translations, create issues or discuss new features. You can also join the slack team https://slack.luya.io if you have any further questions or ideas.
