### ISSUE TITLE
Hide Block Toolbar on Drag

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1661]
When dragging blocks, the toolbar (edit, delete icons etc.) should be hidden. (layout block toolbars)

**Comment by dev7ch** [comment]
@nadar after having a closer look i ve seen that the edit, delete, etc icons are already hidden on dragging.

![drag_block](https://user-images.githubusercontent.com/15183757/33269646-be1f34f0-d381-11e7-8464-b77c43bda126.gif)

but maybe we should implement a drag & drop cursor if the block toolbar (not icons) is hovered?

**Comment by nadar** [comment]
@dev7ch add a layout block then you will see the toolbar of the layout block.

What do you mean? On hover? on drop? on start dragging? which event do you mean.

**Comment by dev7ch** [comment]
ok, i ll give it a try later.

I mean we should give the user a signal by a cursor that it is draggable block... e.g. on hover the Blocktoolbar (not the icons).

But its not directly related to this issue.

**Comment by nadar** [comment]
Yes, we should use cursor: move (?) when hovering over a block, please create an issue. thanks

**Comment by TheMaaarc** [comment]
To hide the toolbars I need a class on the body that indicates the dragging-status (`dnd-dragging` for example).
