### ISSUE TITLE
LUYA should remember version last worked on

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#1663]
### What steps will reproduce the problem?

Create a version of a page and start to edit this version, click on another menu item and return to the page with the newly created version.

### What is the expected result?

The lastly edited version should still be active.

### What do you get instead? (A Screenshot can help us a lot!)

The published version is active. If you don't notice this and manually switch to the version you were editing, you are editing the published version.

So:
- LUYA should remember the edited version and load it again when accessing the page the next time
- It would make sense to have a signal (e.g. a color code) that changes dependent on the version that is edited: published version shows another color than unpublished version

**Comment by nadar** [comment]
@rolandschaub where would you display the color badge? Could you make an example?

You agree with me, that it makes no sense to store this in html storage? So we could just make service which holds this information until a reload happens.

**Comment by rolandschaub** [comment]
I will have to look at how to implement this visually with @TheMaaarc.

I think the version should also be remembered after a reload (I had occasions where after a reload I was working with the wrong version).

**Comment by nadar** [comment]
Well i don't think this is a good idea, because then you will have probably the same problem described from you at the start of the discussion.

Working on a new version .... switch off computer ... log into administration area after a few days and it will still display the last edited version instead of the live version not recognizing your are working on new version instead of active version.

**Comment by rolandschaub** [comment]
Then forget the version after a logout, but not after a reload, which can happen in the same working session.

**Comment by nadar** [comment]
Hmm. Maybe its more a problem of visualization instead of the point in time where the data is lost/stored. 

![image](https://user-images.githubusercontent.com/3417221/33177204-164d9b3a-d062-11e7-90e3-1039472a86ab.png)

**Comment by rolandschaub** [comment]
Yes, the visualization is important, but the edited version should still not be left.
