### ISSUE TITLE
Admin UI: Enhance login loading spinner browser support

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1665]
### What steps will reproduce the problem?

IE 10 doesn´t support svg `animateTransform`.

### What is the expected result?

See a loading spinner in IE as well, better use CSS ( keyframes) animiations

### What do you get instead? (A Screenshot can help us a lot!)

Sometimes is the loading spinner missing in IE.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev-master

**Comment by nadar** [comment]
@dev7ch This is already on the list of #1529
