### ISSUE TITLE
Deleting page doesn't close modal

### ISSUE THREAD

**Issue by ilbassa** [luyadev/luya#1680]
### What steps will reproduce the problem?
1. Create a page /public_html/admin#!/template/cmsadmin~2Fdefault~2Findex/create
2. Delete the page

### What is the expected result?
The page is deleted and the modal is closed.

### What do you get instead? (A Screenshot can help us a lot!)
The page is deleted but the modal is still open

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))
1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] '1'
3: [ini_get('error_reporting')] '32767'
4: [phpversion()] '5.6.30-0+deb8u1'
5: [php_ini_loaded_file()] '/etc/php5/apache2/php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.10 (Debian)'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.0-RC4
| PHP Version      | 5.6.30-0+deb8u1
| Platform         | Apache
| Operating system | Linux Server

**Comment by nadar** [comment]
Please try latest dev-master, this is already fixed. there are few things which has been fixed ;-)

**Comment by ilbassa** [comment]
Ok thanks, it is enough set the require section of composer?
`"require": {
        "luyadev/luya-core" : "@dev",
        "luyadev/luya-module-admin" : "@dev",
        "luyadev/luya-module-cms" : "@dev",
        "luyadev/luya-module-news": "@dev"
    },`
with this configuration I have an error related to Api change #1505

**Comment by nadar** [comment]
just set the packages to `1.0@dev`

+ composer update
+ ./vendor/bin/luya migrate
+ ./vendor/bin/luya import

Now you have to change the API changes. I assume you only have to change "enableCompression" to "contentCompression" in your config, unless you have not made modules.

**Comment by ilbassa** [comment]
Sorry but i don't understand very well composer configuration.

> "require": {
        "luyadev/luya-core" : "1.0@dev",
        "luyadev/luya-module-admin" : "1.0@dev",
        "luyadev/luya-module-cms" : "1.0@dev",
        "luyadev/luya-module-news": "1.0@dev"
    },

create this error
>The requested package luyadev/luya-core 1.0@dev exists as luyadev/luya-core[1.0.0-RC1, 1.0.0-RC2, 1.0.0-RC3, 1.0.0-RC4, 1.0.0-beta6, 1.0.0-beta7, 1.0.0-beta8, dev-master, 1.0.x-dev] but these are rejected by your constraint.

It seems there is some configuration that doesn't allow the installation...

**Comment by nadar** [comment]
sorry, my fault its `^1.0@dev` => https://luya.io/guide/install-problems#require-the-dev-master

**Comment by ilbassa** [comment]
Ok thanks, I had to change
>  'cms' => [
            'class' => 'luya\cms\frontend\Module',
            'contentCompression' => true, // compressing the cms output (removing white spaces and newlines)
        ],
in my configs/env-local.php before run migrate ad import.
Thanks for the support.
