### ISSUE TITLE
Junction table with value ngRest Plugin

### ISSUE THREAD

**Issue by ilbassa** [luyadev/luya#1682]
Hi, I'm trying to develop a ticketing system for events.
I have events that have some prices labeled with categories, so I need that the event CRUD shows the prices and relative category associated to the event with the possibility to add and delete prices.

**Comment by nadar** [comment]
So its junction table with a value field. CheckboxRelation Plugin with option to add values for one or more fields.

**Comment by nadar** [comment]
you can now achieve this by using the https://luya.io/guide/ngrest-model#crud-relation-tabs

![tab-relations](https://user-images.githubusercontent.com/3417221/33517741-a0b23906-d789-11e7-8cb8-b2ac12ca6add.gif)

**Comment by ilbassa** [comment]
Hi, when I try to edit the price it gives me a 404 error, the request is 
`/admin/api-events-price/Name%20of%20the%20event,CATEGORY%20OF%20THE%20PRICE?ngrestCallType=update&fields=event_id%2Ccat_price_id%2Cprice`
It uses the name of the event and the name of the category instead of the ids.
The ngRestAttributesTypes of the Price Model is this:
` return [
        	'event_id'=>[
                    'selectModel',
                    'modelClass' => Event::className(),
                    'valueField' => 'id',
                    'labelField' => 'title'
                ],
        	'cat_price_id'=>[
                    'selectModel',
                    'modelClass' => PriceCategory::className(),
                    'valueField' => 'id',
                    'labelField' => 'descr'
                ],
            'price' => 'decimal',
        ];`
to show the title and the descr of both fields

**Comment by nadar** [comment]
Are you using a composite primary key? The temp. solution would be to use an AI PK. like 'id' => $this->primaryKey() instead of composite keys.

**Comment by ilbassa** [comment]
The solution is correct, now works.
