### ISSUE TITLE
Admin UI: Drag & Drop cursor for blocks on hover

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1684]
### What steps will reproduce the problem?

Hover a block which you want to drag.

### What is the expected result?

Having a cursor on hover which notices that this is a draggable block.

### What do you get instead? (A Screenshot can help us a lot!)

No move or drag cursor.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev master

**Comment by nadar** [comment]
I think we can add this small improvement to 1.0.0 milestone ;-)
