### ISSUE TITLE
Admin UI: Optimized alert if file or selection is empty

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1714]
![image](https://user-images.githubusercontent.com/15183757/33618450-e67d8566-d9e2-11e7-8823-e5165f4b3755.png)

create an alert class for a smoother one, with outline only maybe

**Comment by nadar** [comment]
+ less padding
+ smaller font
+ no background-color

alert-sm for example

**Comment by nadar** [comment]
If such a class is available. please check all zaa-directives for this alert-info class as there are a few more elements using such a "no content" option.

**Comment by dev7ch** [comment]
ok, i ll do it
