### ISSUE TITLE
Proposal to replace <? with <?php

### ISSUE THREAD

**Issue by ogheo** [luyadev/luya#1715]
### What steps will reproduce the problem?

Run a server without support of php short open tag...

### What is the expected result?

Tag <? should be replaced with <?php to work smoothly on all servers because <? is a shortcut for <?php and is not always on by default on some servers (depends on php.ini setting).

### What do you get instead? (A Screenshot can help us a lot!)
![luya](https://user-images.githubusercontent.com/6599359/33635152-86aae5ce-da1f-11e7-91a2-742a5fc4a879.png)

**Comment by nadar** [comment]
Hi @ogheo thanks for the report. This issue has been fixed already and was a bug in RC4. If you like, you can either install the latest dev-master or wait until 12.12.2017 when version 1.0.0 will be released.
