### ISSUE TITLE
Make full name of files in selector buttons and lists available

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#1718]
File names are shortened on selector buttons and in list views of the file manager. The user should still have the possibility to see the complete file name, e.g. by showing a tooltip when hovering over the abbreviated file name:

![file name button](https://user-images.githubusercontent.com/3786245/33676273-9db0a902-dab5-11e7-8898-3e077f13d38e.png)

<img width="411" alt="file name list" src="https://user-images.githubusercontent.com/3786245/33676275-a15e2610-dab5-11e7-8915-8b49ff845268.png">

As for the button: Maybe the file names shouldn't be shown as button labels – it's just too short in many situations. Why not use something like this:

File:
No file selected  [Select]

File:
This-is-my-very-long-file-name.pdf  [Clear]  [Change]

**Comment by nadar** [comment]
@rolandschaub @TheMaaarc i would suggest to set alt="" and title="" tags, as this is a very rare case!

**Comment by rolandschaub** [comment]
This would be a good solution, but showing more of the name by default would be an additional help. It's *not* a very rare case – many customers use (too) long file names.

**Comment by nadar** [comment]
Ok, scheduled for 1.0.1
