### ISSUE TITLE
luya rtl support

### ISSUE THREAD

**Issue by masihfathi** [luyadev/luya#1722]
is it possible to support RTL direction in luya?
something should be done for example, text and text editor block in the CMS should support RTL direction and the navbar menu should be mirrored to right and breadcrumbs text should start from right. see this RTL bootstrap.
![1](https://user-images.githubusercontent.com/13271510/33794061-60ec18be-dcd9-11e7-846a-534d43e39a44.png)
for more about RTL support see this:
https://www.upwork.com/hiring/for-clients/web-design-for-rtl-languages-basics/

| Q                | A
| ---------------- | ---
| LUYA Version    | 
| PHP Version      |
| Platform         | 
| Operating system |

**Comment by nadar** [comment]
@masihfathi Yes the editor should use RTL.

About the frontend views (breadcrumbs, nav): I don't think we will add this, as you as a developer can easy change this in your application. So this is a question of design and is not directly related with LUYA.
