### ISSUE TITLE
create a better a grid view and detailview

### ISSUE THREAD

**Issue by masihfathi** [luyadev/luya#1732]
is it good idea to create a better a grid view and detail view natively for luya framework like "https://github.com/kartik-v/yii2-grid" (kartik extensions)?

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.x
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
Do you mean for the frontend or admin? Because we have ngrest crud (https://luya.io/guide/ngrest-concept), which is grid view with api and angular (as everything is done in angular and rest apis).

**Comment by masihfathi** [comment]
can we use this crud for the frontend?

**Comment by nadar** [comment]
You can use whatever grid view you like in the frontend. It has nothing to do with LUYA.

**Comment by masihfathi** [comment]
i mean luya crud for the frontend.

**Comment by nadar** [comment]
No its not possible, its built with angular. You could call the apis from the admin, but we never done this cause it requires auth. 

you can use yii2 grid view in the frontend if you like.

**Comment by masihfathi** [comment]
thanks for answering.

**Comment by nadar** [comment]
u're welcome
