### ISSUE TITLE
JsonLd / Schema abstraction layer

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya#1736]
As JsonLd is an important feature in Luya, I have a question about it.

I think some small structure adjustments could improve it. Currently, it looks like this:

- luya/web/JsonLd is used to set the JsonLd-Elements onto the page
- All JsonLd-Elements (which are in namespace luya\web\json) extend from luya/web/jsonld/BaseThing (also Thing itself, which is the most basic element from schema.org context)
- This means, that it's not truly divided to jsonld itself and it's context like schema.org. 

What I mean, is that we change it to something like the following:

- luya/web/JsonLd doesn't really change. The general case will use Schema.org as @context, so it can stay with the preset methods for Schema.org-like structured data. This will stay the main class to set JsonLd elements on pages. There's more or less only the change, that `Yii::$app->view->params['@context'] = 'https://schema.org';` will be removed from here. 
- luya/web/jsonld/BaseThing becomes luya/web/BaseJsonLdElement. It will mainly stay the same, but without ThingTrait and not implementing ThingInterface. Here, JsonLd fields will be set, like @context, @id, etc. in the same manner like the others inside the traits.
- Namespace jsonld will become schemaorg (or something like this)
- luya/web/jsonld/Thing (which then becomes luya/web/schemaorg/Thing) implements ThingInterface and uses ThingTrait. @context will be set to "schema.org" in here.
- All other Schema.org elements will extend from luya/web/schemaorg/Thing

Differences:

- There's no big difference in kind of how it's used currently or afterwards. 
- Afterwards, it's not only focused on schema.org, but easily allows other @context types, if for any reason somebody needs that.
- But more important: I think it makes logically more sense to differentiate between the two things. It's also a little bit more flexible, which could help at a later moment, if something changes in regard of json-ld structured data.

What do you think about it?

**Comment by nadar** [comment]
Thanks for your thoughts. I am not 100% sure to understand why moving to schemaorg abstraction. Sure it would allow to have something else then jsonld, but is there any similiar projects like schmeaorg? 

What i can say for now: we can not change the class signature. Your changes would mean we have to switch to version 1.1.0 - if i understand right.

**Comment by JohnnyMcWeed** [comment]
> A context definition defines a local context in a node object. 
https://json-ld.org/spec/latest/json-ld/#context-definitions

> context: A a set of rules for interpreting a JSON-LD document as specified in The Context of the [JSON-LD] specification. 
https://json-ld.org/spec/latest/json-ld/#dfn-contexts

I found **some smaller projects**, but I have no idea whether and how they are used or not. My main point is that we're save for such things and more important, yet **ready for future changes, if for any reason there will be a new important vocab**.

_**Fictional** example: Schema.org is sponsored by Google, Inc., Yahoo, Inc., Microsoft Corporation and Yandex, so these companies are playing a big role here. What happens, if Amazon comes and says "Ohh, schema.org is not structured enough, let's build our own vocab so that people can chose even more things and our services can gather even more information to give better results" (E. g. to improve the IoT access to websites or whatever)_

**Comment by nadar** [comment]
@JohnnyMcWeed currently i think this could only be done in a version 2.0 of LUYA which will be far aways in future. So you can either create a pull request, close the issue or we will label this with 2.0 feature. What do you think?

**Comment by JohnnyMcWeed** [comment]
@nadar I think it can be labeled as 2.0 feature, as it's working now for schema structured data, which is the mail goal. Apart of that it is not very important at the moment I think.

**Comment by nadar** [comment]
i will close this issues:

+ currently no one can spent so many time to change all the classes
+ defintion of new structured is not yet clear
+ jsonld feature should be developed in a separate library  (luya-json for example)
