### ISSUE TITLE
NgRest time field support

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1742]
### What steps will reproduce the problem?

Add time field via NgRestPlugins ( Not as text field or whatever)

### What is the expected result?

have a field like `datetime` which lets you select a time ( e.g. hour:minute) only

### What do you get instead? (A Screenshot can help us a lot!)

No time field supported in NgRestPlugins currently

| LUYA Version     |  dev-master

**Comment by nadar** [comment]
why then not using datetime as you suggested? https://luya.io/api/luya-admin-ngrest-plugins-Datetime

**Comment by dev7ch** [comment]
In particular cases only time is required, without date.
Datetime ist not suitable for that case!
-------- Ursprüngliche Nachricht --------Von: Basil <notifications@github.com> Datum: 02.01.18  08:36  (GMT+01:00) An: luyadev/luya <luya@noreply.github.com> Cc: Silvan <silvan@dev7.ch>, Assign <assign@noreply.github.com> Betreff: Re: [luyadev/luya] NgRest time field support (#1742) 
why then not using datetime as you suggested? https://luya.io/api/luya-admin-ngrest-plugins-Datetime

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/luyadev/luya","title":"luyadev/luya","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/luyadev/luya"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nadar in #1742: why then not using datetime as you suggested? https://luya.io/api/luya-admin-ngrest-plugins-Datetime"}],"action":{"name":"View Issue","url":"https://github.com/luyadev/luya/issues/1742#issuecomment-354714563"}}}
