### ISSUE TITLE
The account dashboard  js error

### ISSUE THREAD

**Issue by baqianxin** [luyadev/luya#1743]
### What steps will reproduce the problem?
https://demo.luya.io/en/admin#!/template/admin~2Faccount~2Fdashboard

### What is the expected result?
javascript error

### What do you get instead? (A Screenshot can help us a lot!)

![image](https://user-images.githubusercontent.com/6780391/34477353-8e2b1dd0-efd4-11e7-94e4-7c73e5f6e6af.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.0
| PHP Version      |7.0.1
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by baqianxin** [comment]
it's here.
![image](https://user-images.githubusercontent.com/6780391/34477434-343ca37e-efd5-11e7-958b-7e6e951e0c50.png)
and now:
![image](https://user-images.githubusercontent.com/6780391/34477451-4bad7ae2-efd5-11e7-8b82-7a39a074be9d.png)

**Comment by nadar** [comment]
@baqianxin thanks! yes we should provide an unique id  for those fields as well. i moved the issue to the admin module.
