### ISSUE TITLE
WYSIWYG editor alternative

### ISSUE THREAD

**Issue by Misavan** [luyadev/luya#1758]
Right now there is no WYSIWYG editors integrated and it will not be [https://github.com/luyadev/luya/issues/950](url). But it is very usefull to have it. As example in News module. News content should have option to add images, links and etc. 
So if developers do not wont to integrate WYSIWYG editors, lets have option to manage content(some field in any module) as it is done in 'Pages' section. There is all needed to have nice and flixible content management. What you thinks?

**Comment by nadar** [comment]
Hi @Misavan - your issue contains no information. You not even removed the default template. What do you expect? whats is your problem? What do you want? How can we help?

**Comment by Misavan** [comment]
check now.

**Comment by nadar** [comment]
I think i know what you mean. So you want to have a "block editor" as ngrest plugin type?

**Comment by Misavan** [comment]
yes, something like that.

**Comment by nadar** [comment]
@Misavan I was still thinking about how to solve this, and maybe we could this very easy by "fake hidden cms pages". I am going to move this to cms module section.
