### ISSUE TITLE
InstanceOf error with php 5.6

### ISSUE THREAD

**Issue by JDL747** [luyadev/luya#1765]
### What steps will reproduce the problem?
When activating a new module in admin group

### What is the expected result?
Active Window with list of modules

### What do you get instead? (A Screenshot can help us a lot!)
<img width="1437" alt="screen shot 2018-02-07 at 11 00 29" src="https://user-images.githubusercontent.com/3844254/35912054-cf884850-0bfb-11e8-8f6e-dc4a3b1b66b3.png">

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.3
| PHP Version      | 5.6
| Platform         | Apache/Ampps.
| Operating system | OSX

**Comment by JohnnyMcWeed** [comment]
Did you migrate and import?

`./vendor/bin/luya migrate`

`./vendor/bin/luya import`

**Comment by TheMaaarc** [comment]
Please update you PHP Version to 7.0 - thats the minimum requirement for LUYA and should fix your issue.

See `Server Requirements` on [https://luya.io/guide/install-problems](https://luya.io/guide/install-problems).

**Comment by nadar** [comment]
Altough the min requirement is php 7.0, maybe i can fix the bug, i'll check later.
