### ISSUE TITLE
yii\base\ViewNotFoundException toolbar.css

### ISSUE THREAD

**Issue by makroxyz** [luyadev/luya#1768]
### What steps will reproduce the problem?
Use latest dev
Use for example news module (or every other added module)

login to cms admin
go to frontend news

### What is the expected result?
news page

### What do you get instead? (A Screenshot can help us a lot!)
The view file does not exist: /path/to/myapp/luyadev/luya-module-news/src/frontend/views/inline/toolbar.css

This is related to ModuleReflection
```php
$this->controller->view->on(View::EVENT_BEFORE_RENDER, function ($event) {
    Yii::$app->controller = $this->controller;
});
```
which is perfect for urls, but it raises this issue

**Comment by nadar** [comment]
@makroxyz Thanks! I will take care of this

**Comment by nadar** [comment]
@makroxyz i just pushed a fix for the core and cms module, could you please try again?

**Comment by makroxyz** [comment]
it works now!
Thanx
