### ISSUE TITLE
Issues with controller switching

### ISSUE THREAD

**Issue by makroxyz** [luyadev/luya#1771]
### What steps will reproduce the problem?
in a view
```php
<?= ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_product',
    'layout' => "<div class=\"text-right\">{pager}</div>\n<div class=\"row animated fadeInLeft\">{items}</div>\n<div class=\"text-right\">{pager}</div>",
    'pager' => [
        'class' => LinkPager::class,
        'options' => ['class' => 'pagination pagination-sm'],
    ],
]) ?>
```

### What is the expected result?
The 2 pagers (top and bottom) should work in the same way

### What do you get instead? (A Screenshot can help us a lot!)
Second pager has wrong urls inside button (cms/default)

The problem is:
ListView renders a page for each item, so the render() method is called for every item.

This fires EVENT_BEFORE_RENDER/View::EVENT_AFTER_RENDER and ModuleReflection.php (rows 244, 253)  switches controller at every event. So after the last item controller is switched to original, and the bottom pager creates urls with wrong controller.

Hope it helps

**Comment by nadar** [comment]
I assume this is part of a module which is implemented into a cms page as module block or as page type module.

**Comment by makroxyz** [comment]
Yes it is

Il 16 feb 2018 15:51, "Basil" <notifications@github.com> ha scritto:

**Comment by nadar** [comment]
@makroxyz thank you for the report!

**Comment by nadar** [comment]
@makroxyz are you running the latest dev-master?

**Comment by nadar** [comment]
On my system it seem to work with the latest dev-master. Your example

```php
<?= ListView::widget(['dataProvider' => $provider,
	'itemView' => '_product',
    'layout' => "<div class=\"text-right\">{pager}</div>\n<div class=\"row animated fadeInLeft\">{items}</div>\n<div class=\"text-right\">{pager}</div>",
    'pager' => [
        'class' => LinkPager::class,
        'options' => ['class' => 'pagination pagination-sm'],
    ],
]); ?>
````
(i used the news module)

here a screenshot from the links generated from the pagination (the bottom one)

<img width="568" alt="bildschirmfoto 2018-02-18 um 09 04 00" src="https://user-images.githubusercontent.com/3417221/36349581-afa2755a-148a-11e8-94f8-5712fe32b741.png">

the example setup:

<img width="941" alt="bildschirmfoto 2018-02-18 um 09 04 48" src="https://user-images.githubusercontent.com/3417221/36349585-cd98bec0-148a-11e8-9095-e631e97da37b.png">

**Comment by nadar** [comment]
This is what the ActiveDataProvider looks like:

```php
$provider = new ActiveDataProvider([
            'query' => Article::find()->andWhere(['is_deleted' => false]),
            'sort' => [
                'defaultOrder' => $this->module->articleDefaultOrder,
            ],
            'pagination' => [
                'route' => $this->module->id,
                'params' => ['page' => Yii::$app->request->get('page')],
                'defaultPageSize' => $this->module->articleDefaultPageSize,
            ],
        ]);
```

**Comment by makroxyz** [comment]
I'm using lastest dev-master

My ActiveDataProvider doesn't have route attribute defined in pagination.
Try to comment that line and you'll see it will generate 2 different urls for top and bottom pager... and this is not good in my opinion.
Hope it helps


```php
$provider = new ActiveDataProvider([
            'query' => Article::find()->andWhere(['is_deleted' => false]),
            'sort' => [
                'defaultOrder' => $this->module->articleDefaultOrder,
            ],
            'pagination' => [
                'route' => $this->module->id, // <--- THIS "FIXES"
                'params' => ['page' => Yii::$app->request->get('page')],
                'defaultPageSize' => $this->module->articleDefaultPageSize,
            ],
        ]);
```

**Comment by nadar** [comment]
ok, now i see the problem.

**Comment by nadar** [comment]
@makroxyz i pushed a fix which should fix the problem. Could you please try? Thanks

**Comment by makroxyz** [comment]
It works now! Thanx!
