### ISSUE TITLE
Database indexes - almost none?

### ISSUE THREAD

**Issue by lubosdz** [luyadev/luya#1775]
Hi guys,
I just evaluated luya first install and I would like to suggest optimizing DB performance by adding indexes on at least ID-related columns. There are so many missing ... e.g. did you stress tested `admin_user_group` with 100.000 users and few tens of groups? This table will become slow query without indexes. Same for many other tables ... or is there some extra SQL to add indexes? I executed all migrations ...

**Comment by nadar** [comment]
Hi @lubosdz indeed you are right. We should make a list of all tables, and what indexes should be added for admin and cms modules at least.

**Comment by nadar** [comment]
## Admin

|table|index keys
|---|---
|admin_user_group|user_id,group_id


## CMS

|table|index keys
|---|---

**Comment by nadar** [comment]
@lubosdz we have to issue to https://github.com/luyadev/luya-module-admin/issues/74 maybe you can find some time to maybe provide some basic ideas of what indexes we should set. where do you think it makes sense? what tables with which field combination?

**Comment by lubosdz** [comment]
@nadar Hi, I would need to study the luya code and figure out which columns/joins are used heavily. Or populate tables and use SQL profiler ... unfortunately this is currently out of my time scope due to ongoing intensive development on another large project. I may take a look in the future once I get some free time.
