### ISSUE TITLE
Setup: Adding permission check of assets directory to luya health command

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1777]
In composer.json file permissions are set for the public_html/assets directory.

However i experienced on several machines the `The directory is not writable by the Web process` exception on a fresh setup or after git clone to another machine.

Is it possible to check if the folder permission and user group is set correctly?  and if not just set it?

Run and show result In this area after `./luya health` command would be good i think

```sh
public_html/assets: directory exists already
public_html/storage: directory exists already
migrations: directory exists already
vendor: directory exists already
runtime: successfully created directory
configs/env.php: file exists.
public_html/index.php: file exists.
O.K.
````

**Comment by nadar** [comment]
cli command is run by yourself, web process by the web server. Therefore different permissions and not detectable.
