### ISSUE TITLE
Adding CSS-Class fields to blocks

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya#1780]
I think it would be good if some default blocks get the possibility to have CSS classes added to them.
E.g. Layout row & column, texteditor...
(Something similar to "Heading" block)

**Comment by dev7ch** [comment]
@JohnnyMcWeed I agree, it would be very useful to have some wrapper classes.

Currently the are block variations able to define in configs, but this is not very  handy:

https://luya.io/guide/app-blocks (page bottom)

```php

'cmsadmin' => [
    'class' => 'luya\cms\admin\Module',
    'blockVariations' => [
        TextBlock::variations()
            ->add('bold-flavor', 'Bold font with Markdown')->cfgs(['cssClass' => 'bold-font'])->vars(['textType' => 1])
            ->add('italic-flavor', 'Italic Font')->cfgs(['cssClass' => 'italic-font'])
            ->register(),
    ]
],

````

**Comment by nadar** [comment]
We encourage people to make their own blocks or use the bootstrap flavored blocks, therefore we don't want to make blocks for developers where every class and attribute can be changed, it should be for the end-user which can just drag and drop without configuration.

If you have a more specific request about a configuration, please make an issue in the refered repository with an example what you like to change and why. thanks.

**Comment by nadar** [comment]
I am going to close this due to:

> If you have a more specific request about a configuration, please make an issue in the referred repository with an example what you like to change and why. thanks.
