### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by makroxyz** [luyadev/luya#1783]
in \luyadev\luya-core\base\Boot.php
```php
if (!array_key_exists('timezone', $config)) {
    $config['timezone'] = 'Europe/Berlin';
}
```
timezone must be timeZone otherwise a timeZone configured in env*.php will be always overwritten

**Comment by nadar** [comment]
I think we will remove this in general as it should be depending on webserver configuration.

**Comment by makroxyz** [comment]
Good!

Il ven 30 mar 2018, 12:01 Basil <notifications@github.com> ha scritto:

**Comment by nadar** [comment]
@makroxyz could you please try the latest dev-master?
