### ISSUE TITLE
admin redirects to logout page

### ISSUE THREAD

**Issue by peatrevo** [luyadev/luya#1785]
### What steps will reproduce the problem?
After successful deployment (./vendor/bin/dep luya prod)
And ./vendor/bin/luya admin/setup

✔ Executing task deploy:prepare
✔ Executing task deploy:release
✔ Executing task deploy:update_code
✔ Executing task deploy:vendors
➤ Executing task deploy:luya
Import result:
luya\admin\importers\StorageImporter:
 - files_missing_in_table: 0
 - files_missing_in_file_table: 0
Importer run successful.

The directory the health commands is applying to: /var/www/htdocs/releases/20180404164640
public_html/assets: directory exists already
public_html/storage: directory exists already
migrations: directory exists already
vendor: directory exists already
runtime: directory exists already
configs/env.php: file exists.
public_html/index.php: file exists.
O.K.

✔ Ok
✔ Executing task deploy:symlink
✔ Executing task deploy:shared
✔ Executing task cleanup
✔ Executing task cleanup:deployfile

### What is the expected result?
Frontend and Admin pages should work.

### What do you get instead? (A Screenshot can help us a lot!)
Frontend is OK, but when I try to log in, looks like login is successful because admin page starts to load  but at some point admin is redirecting me to /admin/login?logout=1

![screen shot 2018-04-04 at 18 49 43](https://user-images.githubusercontent.com/1027778/38322972-4b9f75e6-383c-11e8-8ba8-f77d7d0a5a22.png)

![screen shot 2018-04-04 at 18 50 00](https://user-images.githubusercontent.com/1027778/38323020-67482f40-383c-11e8-81e3-2d3f2c9beb4c.png)

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

1: [ini_get('short_open_tag')] '1'
2: [ini_get('error_reporting')] '22527'
3: [phpversion()] '7.0.29-1~dotdeb+8.1'
4: [php_ini_loaded_file()] '/etc/php/7.0/fpm/php.ini'
5: [php_sapi_name()] 'fpm-fcgi'
6: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'nginx/1.12.2'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | luya-core 1.0.5
| PHP Version      | 7.0.29-1~dotdeb+8.1
| Platform         | nginx php-fpm
| Operating system | Linux Server

**Comment by nadar** [comment]
@peatrevo i assume this is a problem with php fpm try this in your htaccess:

SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0 # php-fastcgi support
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}] # php-fpm support

maybe uncomment fastcgi and enable php-fpm

**Comment by peatrevo** [comment]
Meanwhile I found out, that the site was protected by http auth and that caused the problem. Now admin login works as expected.

**Comment by nadar** [comment]
Ok. If you want to protected your site you can also use the luya basic auth module: https://github.com/luyadev/luya-module-basicauth

**Comment by peatrevo** [comment]
Yes, this is what I'm checking. Thanks for the quick response.

**Comment by nadar** [comment]
you'r welcome, let me know if you have any further question.
