### ISSUE TITLE
luya console doesn't show commands if called outside project folder

### ISSUE THREAD

**Issue by makroxyz** [luyadev/luya#1799]
in vendor/luyadev/luya-core/bin/luya row 20 should be
```php
$boot->configFile = __DIR__ . '/../../../../configs/env.php';
```
otherwise it doesn't load configured modules with relative commands

**Comment by nadar** [comment]
@makroxyz could you make an example where the current defintion does not work? We could also make an array of defintions in order to check if any of the files are available (https://github.com/luyadev/luya/blob/master/core/bin/luya#L5-L10) like we did for the autoload.php

**Comment by makroxyz** [comment]
Add a module with console commands.
Call ./luya (inside project folder) --> shows all commands
Call /var/www/project/luya (outside project folder) --> shows only luya commands

**Comment by makroxyz** [comment]
Hi any news about this issue?

**Comment by nadar** [comment]
Hi @makroxyz We could make an array of configs to check, maybe you like to send a PR? But in general its not recommend to call the bin file from the vendor folder, its always meant to be called from project folder or do you have a concrete use case?

**Comment by makroxyz** [comment]
I'm not calling bin from the vendor folder...
try this
create a console command in a custom module.

Call ./luya (inside project folder) --> shows all commands (included your module)
Call /var/www/project/luya (outside project folder) --> shows only luya commands

**Comment by nadar** [comment]
What would happen if you would call `/var/www/project/vendor/bin/luya`?

**Comment by makroxyz** [comment]
have a look at the commands available

**Comment by nadar** [comment]
@makroxyz sorry for being very (very very) late, but yes indeed i see the problem.
