### ISSUE TITLE
typo in environment docs

### ISSUE THREAD

**Issue by cebe** [luyadev/luya#1812]
### What steps will reproduce the problem?

[configs-luya.jpg](https://github.com/luyadev/luya/blob/master/docs/guide/img/configs-luya.jpg)  on https://luya.io/guide/install-environments shows "env-prep.php" on the prod column.

### What is the expected result?

should be env-prod.php on prod environment.

**Comment by nadar** [comment]
@TheMaaarc hopefully you have the original format of this image somewhere 😄
