### ISSUE TITLE
LazyLoad widget don't work in another widget

### ISSUE THREAD

**Issue by cheerymagicsoftware** [luyadev/luya#1830]
### What steps will reproduce the problem?
Using widget LazyLoad in another widgets (For example ListView).
I add this widget in 'itemView' partial view of ListView widget.

### What is the expected result?
lazyload.js must load.

### What do you get instead? (A Screenshot can help us a lot!)
Don`t load lazyload.js lib.

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

---

### Additional infos
It's happend because static::$counter of class Widget  already has counted +1 in ListView widget. 
In my case, I extended LazyLoad class and add local counter:
```
<?php
...
class LazyLoadExt extends Widget
{
    ...
    public static $localCounter = 0;
    ...
    public function init()
    {
         ...
         static::$localCounter++;
         static::$counter++;

         if (static::$localCounter== 1) {
             LazyLoadAsset::register($this->view);
             $this->view->registerJs("$('.lazy-image').lazyLoad();", View::POS_READY);
             $this->view->registerCss(".lazy-image { display: none; }");
         }
     }
     ...
}
?>
```

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.7
| PHP Version      | 7.1
| Platform         | XAMPP
| Operating system | Windows

**Comment by nadar** [comment]
Maybe there is also another (better) way to check whether an asset is already registered or not (instead if the counter).

**Comment by cheerymagicsoftware** [comment]
Maybe... :)

**Comment by nadar** [comment]
Thanks for the report, will fix it asap
