### ISSUE TITLE
missing edit if config has only cfgs (CMS Admin)

### ISSUE THREAD

**Issue by rainerCH** [luyadev/luya#1835]
### What steps will reproduce the problem?
- Create a Block with only cfgs and no vars

`    public function config()
    {
        return [
            'placeholders' => [
                [
                    ['var' => 'col_1', 'cols' => 6, 'label' => ''],
                    ['var' => 'col_2', 'cols' => 6, 'label' => '']
                ]
            ],
            'cfgs' => [
                    ['var' => 'assetId', 'label' => 'Asset ID', 'type' => self::TYPE_TEXT],
                ]
        ];
    }`

### What is the expected result?
- Edit Icon on Block in CMS Admin

**Comment by nadar** [comment]
Just saw this was reported already today in cms module repo. https://github.com/luyadev/luya-module-cms/issues/121

**Comment by nadar** [comment]
@rainerCH should be fixed in latest dev-master
