### ISSUE TITLE
new created page will under default page (homepage)

### ISSUE THREAD

**Issue by samuelbbtech** [luyadev/luya#1842]
### What steps will reproduce the problem?

- install luya via composer
- migrate
- import 
- admin/setup
- login
- create page

### What is the expected result?
after i creating a new page, i expert i can access via url like http://domain/newpagetitle

### What do you get instead? (A Screenshot can help us a lot!)

http://domain/homepage/newpagetitle

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
Hi @samuelbbtech Thanks for the issue. I am not sure to understand your problem.

If you create a page as subpage from another page, the full path will have the previous page included.

+ page: homepage
+ subpage: newpagetitle

= full path: /homepage/newpagetitle

Why not creating `newpagetitle` on the same (root) level as homepage?

**Comment by samuelbbtech** [comment]
hi @nadar thanks for the reply. I think that was my own problem. i create the page newpagetitle on the same root as homepage, but i didn‘t set the page as “visible“， so when i try to access the page as http://domain_name/newpagetitle it is 404 not found, but when i try to access the page with http://domain_name/homepage/newpagetitle it showed me the content i created for newpagetitle.

**Comment by nadar** [comment]
@samuelbbtech so we can close this issue?
