### ISSUE TITLE
concept clarification about Frontend and Admin module

### ISSUE THREAD

**Issue by samuelbbtech** [luyadev/luya#1845]
hi all, i would like to get some clarification about the fronted module and admin module. what i want to know is when i create a module, for example, it is a module for registration form. This form will be showed on my website front-end. So i create a module with the following command : 
"./vendor/bin/luya module/create registration" , Then i will get a module folder with "registration" in my modules/ folder.  
Now, in my registration folder i get three folders that are admin/, frontend/, and models/. 
So, i need a model file to manipulate my database table `users` that previously created by using ./vendor/bin/luya migrate. 
The question is should i use command "./vendor/bin/luya admin/crud/create" to create a model file for this registration form ?

**Comment by nadar** [comment]
@samuelbbtech In general you are doing everything correctly. If you like to manage the users in the admin, yes we recommend to use `admin/crud` as it will create a full admin view with api, controller and model (NgRestModel, which extends ActiveRecord). When you select the `registrationadmin` module while creating admin/crud, all the apis, controllers and models will belong to this folder.

Does this answer your questions? (here you can read more about ngrest: https://luya.io/guide/ngrest-concept)

In general, if you think the docs are missing some informations, please send us a Pull request with enhanced texts, so everyone can learn from your process.

**Comment by samuelbbtech** [comment]
@luya-bot sorry for posting wrong comment in issue portals, i will move to gitter

**Comment by nadar** [comment]
@samuelbbtech Its not a problem at all. Btw we recommend slack: https://slack.luya.io as gitter has a very stupid notification system ;-)
