### ISSUE TITLE
Luya GII code template

### ISSUE THREAD

**Issue by sahifedp** [luyadev/luya#1846]
Hi
It is very good that adding luya customized code template to Gii
I think it is not difficult
thanks

**Comment by nadar** [comment]
@sahifedp This would require to either fork gii or configure gii with this new luya panel. What would you prefer and why?

**Comment by sahifedp** [comment]
example of a gii template:

https://github.com/yujin1st/gii-templates

it use yii/gii with different template

**Comment by nadar** [comment]
Feel free to create a template for gii if you like. 

Currently we can say extending gii modul by panels is not what LUYA philosophy is all about. Confiugre stuff over and over again for every project is not an expected LUYA behavior. 

If there is a panel, we could fork yii gii and provided "luya gii" or something like this.
