### ISSUE TITLE
Add item to menu navigation

### ISSUE THREAD

**Issue by msoa** [luyadev/luya#1847]
How to add `item` to  `menu navigation`?
I want add item to `Menu navigation` without `childof`. In fact i want the item will be parent in menu navigation. I think have to use `luya\cms\models\Nav`...
```
Yii::$app->menu->injectItem(new InjectItem([
    'childOf' => 123,
    'title' => 'This is the inject title',
    'alias' => 'this-is-the-inject-alias',
]));
```

**Comment by nadar** [comment]
@msoa i think this is somewhat dublicated to: https://github.com/luyadev/luya-module-cms/issues/62
