### ISSUE TITLE
Unique url in Modul-Block context

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya#1855]
### What steps will reproduce the problem?
Create new page with the name `mypage` add a module block to the content and select a module (e.g. `mymodule`). Inside the action/view create a url with `\luya\helpers\Url::toRoute(['/mymodule/other-controller/index', 'id' => 1])` 

### What is the expected result?
Generated url should be `https://example.com/mymodule/other-controller/index/id/1`

### What do you get instead? (A Screenshot can help us a lot!)
But I get `https://example.com/mypage/other-controller/index/id/1`

It is important for SEO to have unique urls. Maybe resolve this with a config option in the module block?

**Comment by nadar** [comment]
sorry for the late reply @boehsermoe 

So you would like to have the url you have defined in the config like `mymodule` - this url still works, so maybe you should not implement the module as part of the cms (module page or module block), maybe just redirect from the navigation to the module `/mymodule` - currently i don't think this is what people expect: placing a module but url points to another page - which not even exsits in the menu tree.

what do you think?

**Comment by boehsermoe** [comment]
I dont mean the target url to the module page (or module block). The problem is that I have a link inside the module page. The url for module page A is `https://example.com/mymoduleA`, that correct. And inside the view I create a anchor like `Html::a("link", ['/mymoduleB/other-controller/index', 'id' => 1])` and the result is currently `https://example.com/mymoduleA/other-controller/index/id/1` but should be `https://example.com/mymoduleB/other-controller/index/id/1`.

**Comment by nadar** [comment]
What does the url for this linke looks like? does https://luya.io/api/luya-cms-helpers-Url toModuleRoute works?

**Comment by boehsermoe** [comment]
`toModuleRoute` doesnt help because the `mymoduleB` is not in the menu.

`Html::a("link", ['/mymoduleB/other-controller/index'])`

**Result**
https://example.com/mypageA/other-controller/index

**Expect**
https://example.com/mymoduleB/other-controller/index


In the UrlManager::urlReplaceModule every module route which exists in the app will be replaced with current context route. But it should only replace the module route if it is the same module class, right?

**Comment by nadar** [comment]
Okay i see, yes i agree on this:

> But it should only replace the module route if it is the same module class
