### ISSUE TITLE
Language Switcher

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#1876]
The changes introduced in https://github.com/luyadev/luya/commit/85b7e132a34c214e5e4697b73890095902a0b69b (via #1855) breaks the ability to generate url rules without current module context.

This is used for the lang switcher: https://github.com/luyadev/luya-module-cms/blob/master/src/widgets/LangSwitcher.php#L201

**Comment by boehsermoe** [comment]
@nadar this could fix it https://github.com/luyadev/luya/pull/1877/commits/15bca4e67395022c1f170e3d65fbe8d31aae3468
We should write a unit test for this.

**Comment by nadar** [comment]
Yes i agree on this. https://github.com/luyadev/luya-module-cms/blob/master/tests/src/widgets/LangSwitcherTest.php
