### ISSUE TITLE
Problem with installing Luya , LINUX OS

### ISSUE THREAD

**Issue by testt23** [luyadev/luya#1878]
After add this command " composer create-project luyadev/lu                                          ya-kickstarter:~1.0.0
" on linux terminal and... visual this error:

>  Problem 1
>     - luyadev/luya-testsuite 1.0.10 requires phpunit/phpunit ~6.0.0 -> satisfiab                                          le by phpunit/phpunit[6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0.3                                          , 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9].
>     - luyadev/luya-testsuite 1.0.11 requires phpunit/phpunit ~6.0.0 -> satisfiab                                          le by phpunit/phpunit[6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0.3                                          , 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9].
>     - luyadev/luya-testsuite 1.0.12 requires phpunit/phpunit ~6.0.0 -> satisfiab                                          le by phpunit/phpunit[6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0.3                                          , 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9].
>     - luyadev/luya-testsuite 1.0.13 requires phpunit/phpunit ~6.0.0 -> satisfiab                                          le by phpunit/phpunit[6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0.3                                          , 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9].
>     - luyadev/luya-testsuite 1.0.13.1 requires phpunit/phpunit ~6.0.0 -> satisfi                                          able by phpunit/phpunit[6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0                                          .3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9].
>     - luyadev/luya-testsuite 1.0.13.2 requires phpunit/phpunit ~6.0.0 -> satisfi                                          able by phpunit/phpunit[6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0                                          .3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9].
>     - luyadev/luya-testsuite 1.0.13.3 requires phpunit/phpunit ~6.0.0 -> satisfi                                          able by phpunit/phpunit[6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0                                          .3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9].
>     - luyadev/luya-testsuite 1.0.5 requires phpunit/phpunit ~6.0.0 -> satisfiabl                                          e by phpunit/phpunit[6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0.3,                                           6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9].
>     - luyadev/luya-testsuite 1.0.9 requires phpunit/phpunit ~6.0.0 -> satisfiabl                                          e by phpunit/phpunit[6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0.3,                                           6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9].
>     - luyadev/luya-testsuite 1.0.8 requires luyadev/luya-module-admin ~1.0.0 ->                                           satisfiable by luyadev/luya-module-admin[1.0.0, 1.0.0-RC1, 1.0.0-RC2, 1.0.0-RC3,                                           1.0.0-RC4, 1.0.0-beta6, 1.0.0-beta7, 1.0.0-beta8, 1.0.1, 1.0.2, 1.0.3, 1.0.3.1,                                           1.0.x-dev] but these conflict with your requirements or minimum-stability.
>     - luyadev/luya-testsuite 1.0.7 requires luyadev/luya-module-admin ~1.0.0 ->                                           satisfiable by luyadev/luya-module-admin[1.0.0, 1.0.0-RC1, 1.0.0-RC2, 1.0.0-RC3,                                           1.0.0-RC4, 1.0.0-beta6, 1.0.0-beta7, 1.0.0-beta8, 1.0.1, 1.0.2, 1.0.3, 1.0.3.1,                                           1.0.x-dev] but these conflict with your requirements or minimum-stability.
>     - luyadev/luya-testsuite 1.0.6 requires luyadev/luya-module-admin ~1.0.0 ->                                           satisfiable by luyadev/luya-module-admin[1.0.0, 1.0.0-RC1, 1.0.0-RC2, 1.0.0-RC3,                                           1.0.0-RC4, 1.0.0-beta6, 1.0.0-beta7, 1.0.0-beta8, 1.0.1, 1.0.2, 1.0.3, 1.0.3.1,                                           1.0.x-dev] but these conflict with your requirements or minimum-stability.
>     - luyadev/luya-testsuite 1.0.4 requires luyadev/luya-core 1.0.0-RC3 -> satis                                          fiable by luyadev/luya-core[1.0.0-RC3] but these conflict with your requirements                                           or minimum-stability.
>     - luyadev/luya-testsuite 1.0.3 requires luyadev/luya-core 1.0.0-RC3 -> satis                                          fiable by luyadev/luya-core[1.0.0-RC3] but these conflict with your requirements                                           or minimum-stability.
>     - luyadev/luya-testsuite 1.0.2 requires luyadev/luya-core 1.0.0-RC3 -> satis                                          fiable by luyadev/luya-core[1.0.0-RC3] but these conflict with your requirements                                           or minimum-stability.
>     - luyadev/luya-testsuite 1.0.1 requires luyadev/luya-core 1.0.0-RC3 -> satis                                          fiable by luyadev/luya-core[1.0.0-RC3] but these conflict with your requirements                                           or minimum-stability.
>     - phpunit/phpunit 6.0.9 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.8 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.7 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.6 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.5 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.4 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.3 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.2 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.13 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.12 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.11 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.10 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.1 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - phpunit/phpunit 6.0.0 requires php ^7.0 -> your PHP version (5.6.38) does                                           not satisfy that requirement.
>     - luyadev/luya-testsuite 1.0.0 requires luyadev/luya-core 1.0.0-RC3 -> satis                                          fiable by luyadev/luya-core[1.0.0-RC3] but these conflict with your requirements                                           or minimum-stability.
>     - Installation request for luyadev/luya-testsuite ~1.0.0 -> satisfiable by l                                          uyadev/luya-testsuite[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.13.1, 1.                                          0.13.2, 1.0.13.3, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].

**Comment by nadar** [comment]
Whats you php version on cli?

**Comment by nadar** [comment]
PHP 7.0 is required for certain components, if you like to disable the platform check maybe try `composer create-project luyadev/luya-kickstarter:~1.0.0 --ignore-platform-reqs`

**Comment by testt23** [comment]
I changed it from 5.6 to 7.0. version and now shows the following error

> 

>   To enable extensions, verify that they are enabled in your .ini files:
>     - /opt/cpanel/ea-php70/root/etc/php.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-ctype.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-dom.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-ftp.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-json.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-phar.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-posix.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-simplexml.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-tokenizer.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-xml.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-xmlwriter.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/20-xsl.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/30-wddx.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/30-xmlreader.ini
>     - /opt/cpanel/ea-php70/root/etc/php.d/zzzzzzz-pecl.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by nadar** [comment]
Where do you get this error then? This does not look like a problem related to LUYA

**Comment by testt23** [comment]
When performing the following installation command:
composer create-project luyadev / luya-kickstarter: ~ 1.0.0

the putty is the top error, and php modules are actually enabled. The server has cPanel installed.

**Comment by nadar** [comment]
What if you try `composer create-project luyadev/luya-kickstarter:~1.0.0 --ignore-platform-reqs` as suggested above? Could you please post the whole composer message regarind `To enable extensions, verify that they are enabled in your .ini files:`

**Comment by nadar** [comment]
You should configure your PHP properly, make sure all the required extensions (like pdo) are installed.
