### ISSUE TITLE
HTTP/2 Server Push

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya#1879]
### Additional infos
With HTTP/2 we have the ability to push files from the server. Like this we can have some better speed.

Here's a guide with more information about it: https://www.smashingmagazine.com/2017/04/guide-http2-server-push/

Could be a nice feature for LUYA to have e.g. a helper or even do it be default.

**Comment by nadar** [comment]
Please make a concrete example of where this should apply and how to integrate. thanks. sounds interesting though.

**Comment by JohnnyMcWeed** [comment]
I've just found two extensions doing this on yii2. Either it could be solved through a helper class, somehow like https://github.com/melbahja/Http2Pusher, or attached to an event, somehow like https://github.com/DevGroup-ru/yii2-http2-server-push/blob/master/src/AutomaticServerPush.php.

- The first approach would need that someone needs to add all pieces individually when creating the views.
- The second would do that automatically, which would make it a really nice solution as nothing has to be done manually.

**Comment by nadar** [comment]
Is there a downside for the second approach? But general i assume this sounds good. Maybe it could be a application configuration in order to enable/disable such a behavior `enableHttp2ServerPush`.

**Comment by JohnnyMcWeed** [comment]
There are some things which should be taken care of or at least should be checked how they impact:

- The resources (css/js) should not be sent on each request, only the first one should do that because of browser caching. I am currently not sure how the browser/cache mechanism is working together with that.
- For big pages it's maybe better to do that only for the top of the page and let the other stuff (like images at the bottom) come in through lazyload. (As a user maybe never scrolls down to them, so it's sent data for nothing.)

**Comment by nadar** [comment]
Could you make a code example how this would look like?

**Comment by nadar** [comment]
Do we have some news on this?
