### ISSUE TITLE
How I can install user registration module and pay after register

### ISSUE THREAD

**Issue by testt23** [luyadev/luya#1882]
How can I install a module for user registration (public, not in the admin panel) and also those users after registration have a billing services module.
in case there is no such thing, at least to install a registration module.
thanks

**Comment by nadar** [comment]
You can attach any yii2 module to your frontend, someone used https://github.com/dektrium/yii2-user and for payment you might use https://github.com/luyadev/luya-module-payment - but non of these services provide subscriptions.

So what you are trying to do has nothing to do with LUYA itself - its your frontend application, you can use LUYA admin to manage the user input data. Maybe joining slack channel to ask other people if someone already has done such a project.

**Comment by testt23** [comment]
I thought there was a product ready for users with privileges / rights that they could install.

but what I found is not what you are looking for https://luya.io/packages/luyadev--luya-module-userauth

**Comment by nadar** [comment]
If you are looking for a system which does already anything for you without doing something, then you might not choose LUYA :-)

**Comment by testt23** [comment]
How u can install this module https://github.com/dektrium/yii2-user

**Comment by nadar** [comment]
I never used it, but maybe take a look at: https://github.com/dektrium/yii2-user/blob/master/docs/getting-started.md
