### ISSUE TITLE
Bootstrap 3, Layout, Texts, Media not see in Groups Management 

### ISSUE THREAD

**Issue by testt23** [luyadev/luya#1886]
I have installed bootstrap 3 (https://luya.io/packages/luyadev--luya-bootstrap3) , but I not see this extensions on my Groups Management **Settings -> Groups Management**

I see on here Settings -> Blocks Management , but not see on Settings -> Groups Management ? Why?

**Comment by nadar** [comment]
Questions should be asked not in the issue tracker :-) join the slack channel please.

Blocks have no CRUD - if you run import command you are ready to use the block inside the cms.

**Comment by testt23** [comment]
> 
> 
> Questions should be asked not in the issue tracker :-) join the slack channel please.
> 
> Blocks have no CRUD - if you run import command you are ready to use the block inside the cms.
Please u see this images.
https://imgur.com/a/Al25cZT

**Comment by nadar** [comment]
The group was deleted in the database - right?

**Comment by testt23** [comment]
Yes, but I don't understand, why?! I have change 1 to 0 and solved problem.
Thanks.
