### ISSUE TITLE
luya homepage

### ISSUE THREAD

**Issue by bsunil47** [luyadev/luya#1890]
### What steps will reproduce the problem?
Opening luya home page

### What is the expected result?
homepage

### What do you get instead? (A Screenshot can help us a lot!)
setBaseYiiFile(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php'); $boot->run(); 

![luya](https://user-images.githubusercontent.com/3174529/49152386-a19ded80-f338-11e8-8aed-6b3722107bae.PNG)

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

when i run luyacheck.php i get the following error
PHP Fatal error:  Uncaught Error: Call to undefined function apache_get_modules() in /var/www/html/luya/luya-kickstarter/luyacheck.php(22)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |PHP 7.2.10-0
| Platform         | Apache2
| Operating system |ubuntu0.18.04.1

**Comment by nadar** [comment]
PHP seems not to run on your webserver. Make sure you configure your webserver properly. this is not luya related.
