### ISSUE TITLE
It always pop up login page (XAMPP)

### ISSUE THREAD

**Issue by ScottHuangZL** [luyadev/luya#1891]
### What steps will reproduce the problem?
I use XAMPP to host the personal website at dev enviroment
I am success install Luya and able go to
http://localhost/luya-kickstarter/public_html/
http://localhost/luya-kickstarter/public_html/admin
successfully.

in http://localhost/luya-kickstarter/public_html/admin, it would have a login page.
I am able login successfully. And then web navigate to dashboard.

However, then the web would continue **pop up a dialog** asking me login http://localhost with username and password. It should be browser itself request after I try Chrome/Firefox/IE.

I think it should be cased by the admin page try ng/js callback some function to get data from server and cause this issue.
However, my existing other web is ok.

### What is the expected result?
I am expect it **not** pop up a dialog again and again after I successful login http://localhost/luya-kickstarter/public_html/admin.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version    latest | 
| PHP Version     7.0 |
| Platform         | XAMPP.
| Operating system | Windows 10 x64.

**Comment by nadar** [comment]
Hi @ScottHuangZL what do you mean by popup? You are not able to login in the admin? Or are you talking about htaccess authentication?

**Comment by nadar** [comment]
basic auth won't work, therefore just use this module: https://github.com/luyadev/luya-module-basicauth

**Comment by ScottHuangZL** [comment]
Hi @nadar , I am try setting up what your say above. 
http://localhost/luya-kickstarter/public_html/ will asking input basic password which I just setting in env-local.php , after that, show home pages, and then I click admin button to go to Luya backend, and this time Luya itself do not asking me input pass since I know I change to basic auth.  But wait a moment, browser itself pop up a dialog again to asking me provide user & pass again**(not Luya itself)**.

**So,  it did not resolve the issue. Btw,  I am also no plan to use basic auth.**
I just need ensure PHP able get windows user name from any request and at the mean time browser do not pop up login dialog(**note, it is not Luya login page**)  when I try navigate Luya website, I am no concern to use the admin module and input user/pass which set by "vendor\bin\luya admin/setup"as normal way, just concern for browser's auto pop up login dialog again and again.

It should be something related to **httpd.conf and .htacess** and may be angularJs.
I will try more tomorrow... 
**And also appreciate you can help to recheck too, thanks.**

**Comment by ScottHuangZL** [comment]
Issue fixed by below steps:

1. Keep my original httpd.conf no change firstly
DocumentRoot "C:/xampp/htdocs"
<Directory "C:/xampp/htdocs">
... the original settings which able auto get window user names...
</Directory>

2. Add below right after above </Directory>. **That means, I specially allow  all under Luya public folder.**
<Directory "C:\xampp\htdocs\luya-kickstarter\public_html">
Require all granted
</Directory>


After that, then both work: my existing website still able get window user names as usual, and Luya admin also able run smoothly.
