### ISSUE TITLE
Problem error with portfolio module

### ISSUE THREAD

**Issue by testt23** [luyadev/luya#1892]
Hello everyone
I installed the portfolio module, activated it through the admin panel, added a group, created a new Item, and when I opened my portfolio page showed the following error

Call to a member function getSource() on boolean
1. in /home/gen/luya-kickstarter/vendor/vavepl/luya-module-portfolio/src/frontend/views/default/index.php at line 26
2. in /home/gen/luya-kickstarter/vendor/yiisoft/yii2/base/View.php at line 336 – require()
3. in /home/gen/luya-kickstarter/vendor/yiisoft/yii2/base/View.php at line 254 – yii\base\View::renderPhpFile('/home/gen/luya-kickstarter/...', ['groups' => [1 => 'WebAPP'], 'items' => [vavepl\portfolio\models\Item]])
4. in /home/gen/luya-kickstarter/vendor/yiisoft/yii2/base/View.php at line 156 –

https://luya.io/packages/vavepl--luya-module-portfolio
https://github.com/vavepl/luya-module-portfolio

Also, the photos from the module are not active for the demo

**Comment by nadar** [comment]
@testt23 you should create the issue in the repo of the owner (which you linked correctly above) and ask for help or report issues there. https://github.com/vavepl/luya-module-portfolio
