### ISSUE TITLE
Touchscreen not working on Pages drag and drop blocks

### ISSUE THREAD

**Issue by testt23** [luyadev/luya#1894]
Hi everyone,
I need your help. I have add blocks (right menu) to paste on content but don't working. This problem is only when I use the admin panel via a mobile phone

I can added http://touchpunch.furf.com/ (touch punch) on resources and added on assets file, but the problem remains

U have idea for fix this on mobile?

**Comment by nadar** [comment]
LUYA cms wont work properly on mobile because drag events are not supported on mobile phone browser. You can create your own module and register assets in admin modules, but not sure this will fix your problem.

https://luya.io/guide/app-admin-module-assets
