### ISSUE TITLE
Uploading image is not working

### ISSUE THREAD

**Issue by eothein** [luyadev/luya#1901]
### What steps will reproduce the problem?

Uploading an image of about 1,8 mb in the files triggers the following error:

````
Allowed memory size is 1234 .... bytes exhausted...
````
### What is the expected result?

The image is uploaded. 

### What do you get instead?

The **Your data is being uploaded and processed. This can take several minutes.** message but no improvement. 

### LUYA Check ouput (run this script and post the result: [luyacheck.php]
````
0 /Users/eothein/equality/projects/jessicacloet/luya-kickstarter/luycacheck.php(22): eval()
#1 {main}
  thrown in /Users/eothein/equality/projects/jessicacloet/luya-kickstarter/luycacheck.php(22) : eval()'d code on line 1
````

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.14.2
| PHP Version      | 7.2
| Platform         | MAMPP
| Operating system |OSX/.

**Comment by nadar** [comment]
The problem with images is that they consume a lot of memory while processing (making thumbnails) - so yes, even 2 mb images take a lot of memory to apply filters.

So sadly i would say you should increase the memory limit of this server.

**Comment by nadar** [comment]
try 512M

**Comment by eothein** [comment]
512 seemed to do the trick!

**Comment by eothein** [comment]
Indeed and thanks!
