### ISSUE TITLE
File tag parentheses

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#1907]
If I use parentheses in the title part of the tag, the inner parentheses will close the link even if escaped.

**Example:**

```
file[1](Example file (PDF))

file[1](Example file \(PDF\))
```

Both examples result in:

`<a href="...">Example file (PDF</a>)`

**Comment by nadar** [comment]
Perfect! Thanks @rolandschaub i will add this regex rule and make some unit tests.

**Comment by rolandschaub** [comment]
Yes, please test it first.

**Comment by nadar** [comment]
@rolandschaub i have made a new branch with the regex and a unit test which should not fail if everything works as expected. 

If you like to test:

1. git clone
2. checkout `issue-1907` branch
3. run `composer install`
4. run php unit test: `./vendor/bin/phpunit tests/core/TagParserTest.php`

**Comment by rolandschaub** [comment]
```/(?<function>[a-z]+)\[(?<value>.*?)\]((?<!\\\)\((?<sub>.*?)(?<!\\\)\))?/mi```is working!

**Comment by rolandschaub** [comment]
```/(?<function>[a-z]+)\[(?<value>.*?)\]((?<!\\\\)\((?<sub>.*?)(?<!\\\\)\))?/mi```

Four backslashes is the correct way to do it, see here:

https://stackoverflow.com/questions/30254174/preg-match-with-backslashes-doesnt-work-as-expected-throws-error

Step 1: PHP turns \\\\ into two literal \\
Step 2: Regex turns \\ into one literal \
