### ISSUE TITLE
RobotsFilter / Contact Form: Argument 2 is not an array.

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya#1918]
### What steps will reproduce the problem?
Adding the contact form as a module to a page.

### What is the expected result?
The module will show up as expected. 
(It did before, but doesn't after the update.)

### What do you get instead?
PHP Warning – yii\base\ErrorException
array_merge(): Argument 2 is not an array

```
vendor\luyadev\luya-core\web\filters\RobotsFilter.php

/**
     * Render Time Setter.
     *
     * @param integer $time Set the last action timestamp.
     */
    protected function setRenderTime($time)
    {
        $merge = Yii::$app->session->get(self::ROBOTS_FILTER_SESSION_IDENTIFIER, []);
        Yii::$app->session->set(self::ROBOTS_FILTER_SESSION_IDENTIFIER, array_merge([$this->getSessionKeyByOwner() => $time], $merge));
    }
```

**Comment by nadar** [comment]
what of you cleanup the session cookie?

**Comment by JohnnyMcWeed** [comment]
Sorry, works, thanks :)
