### ISSUE TITLE
Error Exception 'yii\db\Exception' with message 'Error while sending QUERY packet.

### ISSUE THREAD

**Issue by symssyms** [luyadev/luya#1954]
### What steps will reproduce the problem?
When execute command in console ./vendor/bin/luya admin/setup

### What is the expected result?
create user admin

### What do you get instead? (A Screenshot can help us a lot!)
![image](https://user-images.githubusercontent.com/26095982/64027870-49577e80-cb4a-11e9-9185-c3e57f7d2c81.png)

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] '1'
3: [ini_get('error_reporting')] '22527'
4: [phpversion()] '7.0.33-0+deb9u3'
5: [php_ini_loaded_file()] '/etc/php/7.0/apache2/php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.25 (Debian) mod_fcgid/2.3.9 OpenSSL/1.0.2s'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.21
| PHP Version      | 7.0.33
| Platform         | Apache+Nginx (VestaCP)
| Operating system | Debian 9.9

**Comment by nadar** [comment]
database setup/config?

**Comment by symssyms** [comment]
> database setup/config?

![image](https://user-images.githubusercontent.com/26095982/64065810-2052ee80-cc1b-11e9-9150-cfa0921e36f9.png)

**Comment by nadar** [comment]
i just would say its not a problem with luya, its a problem with your sql instance. maybe check this article or google for the error message (https://stackoverflow.com/questions/30753674/error-while-sending-query-packet) `error while sending query packet`. Let me know if you find out the problem, maybe it will help someone else too. thanks

**Comment by nadar** [comment]
i will close the issue, if its luya related or the problem persists, let me know.
