### ISSUE TITLE
Composer error whilst installing

### ISSUE THREAD

**Issue by ComputingMrEllis** [luyadev/luya#1955]
### What steps will reproduce the problem?

composer create-project luyadev/luya-kickstarter:^1.0

### What is the expected result?

No errors

### What do you get instead? (A Screenshot can help us a lot!)

Installing luyadev/luya-kickstarter (1.0.14)
  - Installing luyadev/luya-kickstarter (1.0.14): Loading from cache
Created project in /var/www/html/luya-kickstarter
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-gii 2.0.8 requires bower-asset/typeahead.js 0.10.* | ~0.11.0 -> no matching package found.
    - yiisoft/yii2-gii 2.0.7 requires bower-asset/typeahead.js 0.10.* | ~0.11.0 -> no matching package found.
    - yiisoft/yii2-gii 2.0.6 requires bower-asset/typeahead.js 0.10.* | ~0.11.0 -> no matching package found.
    - yiisoft/yii2-gii 2.0.5 requires bower-asset/typeahead.js 0.10.* | ~0.11.0 -> no matching package found.
    - yiisoft/yii2-gii 2.0.4 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.3 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.2 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.1 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - yiisoft/yii2-gii 2.0.0 requires bower-asset/typeahead.js 0.10.* -> no matching package found.
    - Installation request for yiisoft/yii2-gii ~2.0.0 -> satisfiable by yiisoft/yii2-gii[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))
1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] ''
3: [ini_get('error_reporting')] '22527'
4: [phpversion()] '7.3.4-2'
5: [php_ini_loaded_file()] '/etc/php/7.3/apache2/php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.38 (Raspbian)'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | current
| PHP Version      | 7.3
| Platform         | Apache .
| Operating system | Rasbian.

**Comment by nadar** [comment]
make sure to install the fxp Plugin

composer global require "fxp/composer-asset-plugin

**Comment by ComputingMrEllis** [comment]
Great thanks that sorted it shame the install guide command does not work.

I now get the following error:
Yii Migration Tool (based on Yii v2.0.25)

Error: Failed to instantiate component or class "db".

I have check the db and login and config files

**Comment by nadar** [comment]
of course they work, but it seems you did not setup your config properly. as the exception says.

**Comment by nadar** [comment]
ensure the config file has a db component, in the luya kickstarter its env-local-db.php which is merge ind env-local.php config

**Comment by ComputingMrEllis** [comment]
Thanks typo in the file looks OK now
