### ISSUE TITLE
Keep basepath while theme loading

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya#1970]
In `loadThemeConfig` the basepath should be keep as relative path and which should also saved into database.

https://github.com/luyadev/luya/blob/849532964e50b96969069adca01d884d9f8ad5e8/core/theme/ThemeManager.php#L57

**Comment by nadar** [comment]
I am not sure this is related, but cmslayouts doe not work with absolute paths:

```
View not Found – yii\base\ViewNotFoundException
The view file does not exist: /app/repos/luya-module-cms/src/frontend/views/app/vendor/nadar/luya-creative-theme/views/cmslayouts/theme.php
```

as by yii defintion the absolute path must start with double slashes:

+ absolute path within application (e.g. "//site/index"): the view name starts with double slashes. The actual view file will be looked for under the view path of the application.
+ absolute path within current module (e.g. "/site/index"): the view name starts with a single slash. The actual view file will be looked for under the view path of the current module.

https://www.yiiframework.com/doc/api/2.0/yii-base-view#render()-detail

Not sure we have to improve this in luya cms cmslayouts importer or theme manager, will do some research.

**Comment by boehsermoe** [comment]
Problem here is, that the imported base path (the theme name) will be stored in the database. And the same base path will be searching in the database. But if the base path is changed while config loading from alias to an absolute path, this theme cannot found.
