### ISSUE TITLE
Guide + Demo: Manage themes in cms settings

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya#1983]
Append the theme section of the guide (https://luya.io/guide/app-themes) with screenshot and some description for the theme management in cms settings

Also the luya demo https://demo.luya.io/ should be contains some example themes.

Based on luyadev/luya-module-cms/pull/211

**Comment by boehsermoe** [comment]
@nadar after new version deployment on demo.luya.io there should be setup two themes.

**Comment by nadar** [comment]
It would be nice to have:

1. The skeleton repo for themes: https://github.com/luyadev/luya-theme-skeleton
2. Provide `luyadev/luya-themes` repo which contains out of the box themes, maybe you like to move your repo into the luyadev org?

**Comment by nadar** [comment]
The skeleton app is more or less ready, also the luya-themes repo. Thinking about using a theme on demo.luya.io sounds good to me but maybe in a later step.
