### ISSUE TITLE
disable multi-lang when save data to db table

### ISSUE THREAD

**Issue by charescape** [luyadev/luya#2001]
Hello, I am new to luya. I want to known how to disable multi-lang when save data to db table, I searched https://luya.io/guide configurtion chepter but no results.

Thanks a lot.

### What steps will reproduce the problem?
Login admin, submit a form.

### What is the expected result?
![image](https://user-images.githubusercontent.com/53265646/76648718-2a768200-659a-11ea-8bf0-a0bef491311b.png)

### What do you get instead? (A Screenshot can help us a lot!)
![image](https://user-images.githubusercontent.com/53265646/76648412-a0c6b480-6599-11ea-82ee-d6a59600d2bb.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.26
| PHP Version      | 7.3.9
| Platform         | Nginx
| Operating system | Linux Server

**Comment by nadar** [comment]
There is an $i18n property in the ngrest model.

**Comment by nadar** [comment]
https://luya.io/guide/ngrest-model

**Comment by charescape** [comment]
👍 Solved. Thank you!
