### ISSUE TITLE
Themes: parentTheme alias resolving

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#2006]
To reproduce: Setup 2 themes and try to reference one as parentTheme with a path alias.  
Example:

```json
{
    "name": "test",
    "parentTheme": "@vendor/example/test/themes/base",
    "pathMap": [
        "views"
    ],
    "description": null
}
```

In the [ThemeManager.php:196](https://github.com/luyadev/luya/blob/master/core/theme/ThemeManager.php#L196) it checks if `$basePath` is a key of `$themes`. The `$themes` array has all themes indexed by basePath. The basePath includes the whole absolute path, for example `/var/www/vendor...`. It would be nice to resolve aliases in `$basePath` to prevent having to write absolute paths into the theme config.

Maybe there is another solution or I did something wrong. In that case, a little nudge in the right direction would be appreciated. :)

**Comment by nadar** [comment]
@boehsermoe maybe at first place we should elaborate the function of parent Themes somewhere first?

**Comment by boehsermoe** [comment]
This is the same problem in luyadev/luya/issues/1970 and should also fixed with luyadev/luya/pull/2002

**Comment by TheMaaarc** [comment]
Okay, in that case I'm gonna close this issue . :)  
Thanks @boehsermoe

**Comment by boehsermoe** [comment]
luyadev/luya/pull/2002 is merged now
