### ISSUE TITLE
Theme create command not working

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya#2010]
### What steps will reproduce the problem?
Run `vendor\bin\luya theme/create` on Windows

### What is the expected result?
Theme creation should work.

### What do you get instead?
`Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @app\themes\thetheme'`

**Comment by nadar** [comment]
Does the exception appear after pressing submit or did you enter informations?

**Comment by JohnnyMcWeed** [comment]
The problem is the "DIRECTORY_SEPARATOR" which takes `\` on windows. This is not working with the alias.
