### ISSUE TITLE
LazyLoad not always loading properly

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya#2037]
### What steps will reproduce the problem?
When using the LazyLoad widget, the images are not always loading as expected. They appear when resizing the window, but that's not a good solution.  

### What is the expected result?
Proper image loading.

### What do you get instead?
[Not loading as expected](https://i.imgur.com/3xzM9BY.png)

**Comment by nadar** [comment]
@JohnnyMcWeed  Could you provide more informations? In which situations is the image NOT loading? @TheMaaarc is there a debug mode or what more infos could he provide to help us improve the lazy loader?

**Comment by TheMaaarc** [comment]
I guess we could add a debug flag.  
We collect the image boundaries on load and on resize – I'm guessing that the offsets we collect on load aren't correct.

@JohnnyMcWeed If you have code that changes the position after load, you can call 
`$.lazyLoad('refetchElements');` to update the elements.

I will take some time and update the whole lazyload script, there are a few things I can improve.

**Comment by JohnnyMcWeed** [comment]
Thanks for your reply. Didn't have the time to look further into this yet.
@TheMaaarc nice, thank you! should probably work with this. I guess it's coming from other JS and the position change. I'll try this :)

**Comment by TheMaaarc** [comment]
Well, that escalated quite a bit. We now use the IntersectionObserver API. It makes the whole thing more performant and responsive.

@JohnnyMcWeed If the HTML validation is an issue for you, you can solve it by adding the `src` attribute in `options`:
```php
<?= LazyLoad::widget([
    'options' => [
        'src' => 'https://url.to/1-pixel.gif'
    ]
]) ?>
```

It shouldn't be visible in the beginning and get replaced as soon as the correct image is loaded.
