### ISSUE TITLE
website resources

### ISSUE THREAD

**Issue by Arhell** [luyadev/luya#2158]
Hello, please tell me where are the resources for the website https://luya.io/, I did not find the repository.
I would like to work on it, fix bugs and much more

**Comment by nadar** [comment]
Hi @Arhell 

Currently, only the docs are available on github: https://github.com/luyadev/luya/tree/master/docs

But we could of course opensource the rest, just takes time to prepare. What would you like to change?

**Comment by Arhell** [comment]
Make these pages mobile first https://luya.io/guide, accessibility, fix any bugs I find.

**Comment by nadar** [comment]
Sounds good. I will discuss this internally. Maybe we could also switch to one of the common open source solutions like https://vitepress.vuejs.org - just no solution for the api reference generator yet.

**Comment by Arhell** [comment]
> Sounds good. I will discuss this internally. Maybe we could also switch to one of the common open source solutions like https://vitepress.vuejs.org - just no solution for the api reference generator yet.

The idea is good, I can help with the transfer and support
like here for example https://github.com/consolidation/website
but here is a slightly different generator, but I think this is not a problem

**Comment by nadar** [comment]
Sadly i could not find a good solution which contains documentation and representation of the code (api) :-(

**Comment by nadar** [comment]
hey @Arhell there you go :-) https://github.com/luyadev/luya.io

**Comment by Arhell** [comment]
> hey @Arhell there you go :-) https://github.com/luyadev/luya.io

Hello, this is great.
If possible, I would like, as I wrote above, to help with the project and keep this repository up to date, dependencies, documentation fixes and more.

I would like to join the organization as a front-end colleague if possible.

Thank you for your attention

**Comment by nadar** [comment]
Here you can read more about the organisation and when people become members (https://luya.io/guide/dev/organisation.html#_4-requirements-for-becoming-a-member).

Looking forward to hear from you.
