### ISSUE TITLE
Active window has no confirmation button

### ISSUE THREAD

**Issue by hwernze** [luyadev/luya#523]
At Kunstmuseum when i added a tag there is only a "speichern" button which refer logical to the new created tags and a red cross "cancel" button in the upper right corner. But no confirmation-button for simple assignments.

**Comment by martinpetrasch** [comment]
We need a frontend design/concept for this ActiveWindow. This includes a concept for editing a tag(inline?) and a button for deleting a tag. After this we'll add the missing functionality in angular/api and finally the window can be styled according to the concept.

@nadar: please assign to @hwernze
