### ISSUE TITLE
Provide demo site with frontend/admin area

### ISSUE THREAD

**Issue by AlexGx** [luyadev/luya#701]
Provide demo site with frontend/admin area

**Comment by nadar** [comment]
We have a demo, we will going to make this public with the new website, im going to write you in gitter so i can send you the link

**Comment by AlexGx** [comment]
thanks for fast reply!

**Comment by nadar** [comment]
Should i send you a mail instead of gitter (https://gitter.im/AlexGx)?

**Comment by nadar** [comment]
Hi @AlexGx , we finally added the demo page to https://luya.io where you can find all informations about demo login.
