### ISSUE TITLE
Rename of server.php

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#806]
rename the current default `server.php` config file which provides the env config to another less confusing name?

+ config.php
+ env.php
+ configProvider.php

As the server.php file should provided the environment configs like

+ local.php
+ dev.php
+ prep.php
+ prod.php (which could be equal to server.php as the prod env is mostly the server environment)

**Comment by nadar** [comment]
@TheMaaarc @rolandschaub @martinpetrasch what do you thinkg? any other suggestions?

**Comment by TheMaaarc** [comment]
I think `env.php` is the way to go. It describes best what the file basically does.

**Comment by rolandschaub** [comment]
env.php sounds good – or maybe, to make it even clearer, setenv.php or include-env.php.

**Comment by nadar** [comment]
@TheMaaarc Could you please update the image to `env.php`

https://raw.githubusercontent.com/luyadev/luya/master/docs/guide1.0/img/configs-luya.jpg

**Comment by nadar** [comment]
@rolandschaub @TheMaaarc @martinpetrasch 

Maybe also change the config names itself to prefix with env-

+ env.php
+ env-local.php
+ env-dev.php
+ env-prep.php
+ env-prod.php
+ localdb.php
+ otherparams.php

**Comment by nadar** [comment]
FINAL DECISIONS:

+ env.php
+ env-local.php
+ env-local-db.php
+ env-dev.php
+ env-prep.php
+ env-prod.php
+ otherparams.php

@TheMaaarc please change the graphics as of the list above.
