### ISSUE TITLE
Development roadmap?

### ISSUE THREAD

**Issue by jepster** [luyadev/luya#811]
Hi,

I've checked out Luya CMS. An amazing CMS. It's great that it's based on Yii 2.0 framework and has such a great editor experience. There's currently more documentation in German than in English, so I'm glad to be from Germany. I could not wait and started to create a website with it. :)

Is there any roadmap for the next steps in the development?

**Comment by nadar** [comment]
Hi @jepster 

We are working very hard to make a first stable release in August 2016. As we are already using the system in production ourself's, we try to describe all the upgrade steps between beta releases (See UGRADE.MD) so it should not be a problem to create websites with LUYA already.

We are still looking for people helping us with translations, guides, modules and other things. We would also love to hear from your website u have made, to understand what we should do better and how to explain the concept of LUYA to other users.

LUYA Roadmap

+ beta6 release (within next days)
+ beta7 release (May 2016)
+ rc1 release (June 2016)
+ rc2 release (July 2016)
+ first stable release (August 2016)

**Comment by jepster** [comment]
Hi @nadar 

Thanks for your answer!

I like the blocks concept a lot. In the editing phase the preview is already visible. That's great. I can setup something like the blocks inside Drupal, but there it needs a lot of time to setup. So far I've worked on a private blog last night. It was going very fast. Additionally I could setup an own block format for syntax-highlighted code quickly. It's not already online. I'll inform you. :)

I'm running Luya on Mac inside a MAMP-setup. There it works well. I've tried to install it inside a Vagrant Box with current stable Ubuntu Server. But there I'm getting weird errors. I'm guessing that it's somehow related to the file and folder permissions. Are you running Luya in a Vagrant Box or any other VM setup to work in a team in that way (e.g. Docker)?

I've seen that Tags can be set, but the Tags cannot be add to any pages - from what I've seen. Is there any hidden module for that?

One interesting thing in Luya is, that you have the content inside one column as a serialized JSON. That can make it difficult to structure the content output in future (e.g. search result pages, page listings).

Have you also a concept for displaying teasers auto-generated teasers from pages or is it today intended to edit the page teaser manually?

Thanks

**Comment by nadar** [comment]
Vagrant/Docker: No, we don't have a vagrant nor docker setup for LUYA yet, but this could be very intresting for the future. We would love to see such a vagrant LUYA box, probably we could debug your issues and create a repository?

Tags: We have made a  Tags ActiveWindow, this is mainly used to attach on NgRest CRUD lists (https://luya.io/de/handbuch/ngrest-activewindow).

Serialisation: Yes, this allows us to create custom blocks with different configs and variables very quickly. In order to search on the websites, we have made a crawler module, which will deliver better results anyway.

What do you mean with "auto-generated teasers"? This could probably done by Cms Page Properties (https://luya.io/de/handbuch/app-cmsproperties) which allows you to add any configuration to a page, even teaser images or other things.

**Comment by nadar** [comment]
@jepster Maybe its better you send me the Vagrant errors via gitter (https://gitter.im/luyadev/luya) and we can talk directly?

**Comment by jepster** [comment]
> Tags: We have made a Tags ActiveWindow, this is mainly used to attach on NgRest CRUD lists (https://luya.io/de/handbuch/ngrest-activewindow).

I cannot understand what it is. The description sounds a bit too abstract to me. I guess it has something to do with AngularJS. Do you have an example for an active window for me?

Auto-generated teasers: I mean a "display format" from my page. So I would have the title, the first block and an image for my page in this context. Afterwards I would be able to list all teaser display formats on an own page as an overview of my pages. This implements that you have many pages and a "format" for all pages. This would implement another layer of complexity. The (https://www.drupal.org/)[Drupal.org] CMS has such a concepts with nodes (as pages).

**Comment by nadar** [comment]
Active Window: Are only used in Administration Context, for example you have the list of users in your administration interface, now edit and delete provided from the basic implemenation, so now you can add an `ActiveWindow` which will be attached and contains custom code you can define and render (like a controller with views), like the "change password" active window in the users list (https://github.com/luyadev/luya/blob/master/modules/admin/src/aws/ChangePassword.php).

Teasers: We understood what you mean by "teasers", but this seems to be far to complex for users to understand, in this case you better make a block and read some properties directly from the menu item and add additonal informations by block configuration, @TheMaaarc has done this a lot of times and he will show you an example. This is absolut easy to understand for the users.
