### ISSUE TITLE
How can one page be loaded (via ID)?

### ISSUE THREAD

**Issue by jepster** [luyadev/luya#813]
I want to load the markup or elements from one page via a controller. Is there any method for this?

**Comment by nadar** [comment]
So you want to access the content of a navigation point? Or do you just want to access menu points?

If you have the nav item id (cms_nav_item table) you can use the `cmsadmin\models\NavItem` model:

```php
$item = NavItem::find($navItemIdYouLikeToGet)->one();

echo $item->getContent();
```

If you have the nav id (cms_nav table) then you us:

```
echo cmsadmin\models\Nav::findContent($navId);
```

(as the nav table needs a language context to find the item)

If you let me know what you try to achieve, maybe there is another solution?

**Comment by nadar** [comment]
Docs:
Yes, as already told we are going to working on the PHPDoc in the RC-Phase - promise! :-) Yii is really a good role model in case of documenation, i totaly agree! (Describe in the class header is what i learned from Yii: https://github.com/luyadev/luya/blob/master/core/web/GroupUser.php)

Guide:
We are working also on the new guide (https://raw.githubusercontent.com/luyadev/luya/master/docs/guide2.0/sitemap_draft2.md), but what you are trying to understand (which i like!) is very "deep" part of the architecture and maybe to heavy to understand for, lets say, casual cms developers. But yes, we should add an image which describes the concept of nav, nav_items, language, nav_item_types and the correlation of those tables.

Markup thing:
```
<div class="row">
    <div class="col-md-12">

    </div>
</div>
```

This is absolute **on purpose**, as it renders the block into its placeholders from the CMSLAYOUT (https://luya.io/de/handbuch/app-cmslayouts) and as you have no blocks added in your page it renders your cmslayout empty. CMSLAYOUT are very powerfull tool to create different layouts for pages, with content from the CMS (blocks) your just add your procedurial code into those files (in beta6, twig is replaced by original php files, so you have more flexibility).
