### ISSUE TITLE
Luya has a lack of good commenting

### ISSUE THREAD

**Issue by jepster** [luyadev/luya#814]
As I can see from the code in Luya, the most composer packages do not have PHPDoc comments. I like Yii 2.0 very much from the fact, that the code is commented in an excellent way. Luya has a lack of good commenting. I would like to encourage you for better commenting, so that other developers can understand your code.

**Comment by nadar** [comment]
Yes, you are right. The LUYA core repository is covered pretty good, but the modules are only covered at complex or newer parts. As part of the release strategy we will ad phpdoc and guides during the RC-phase, so we are sure its not going to change strongly.
