### ISSUE TITLE
Crawler module does not visibly index anything and does not find anything

### ISSUE THREAD

**Issue by jepster** [luyadev/luya#819]
I'm using the Luya CMS in a MAMP setup. After I execute the following command

> ./vendor/bin/luya command crawler crawl

I'm getting the following output.

> Array
> (
>     [new] => Array
>         (
>         )
> 
>     [update] => Array
>         (
>         )
> 
>     [delete] => Array
>         (
>         )
> 
>     [delete_issue] => Array
>         (
>         )
> 
>     [unchanged] => Array
>         (
>             [0] => http://localhost:8888/
>         )
> 
>     [filtered] => Array
>         (
>         )
> 
> )
> 
> Cralwer finished in 0.01 min.

There's not visible that the crawler indexed anything. Only "Array" in command line output which seems to be a bug, because this information does not inform about any indexed documents.

Also I've added the crawler module to my page. If I load the page afterwards, I get the following error in the webbrowser.

> CMS-Module Exception – cms\Exception
> 
> Module Block Exception: Invalid argument supplied for foreach()

It seems that the module is not loaded. But I have added it into the "prep.php" file:

>     'crawler'      => [
>       'class'   => 'crawler\Module',
>       'baseUrl' => 'http://localhost:8888',
>     ],

**Comment by nadar** [comment]
i am going to add a verbose mode tomorrow, are you running the current dev-master?

**Comment by jepster** [comment]
I have the following entry in my composer.json:
> "zephir/luya-module-crawler" : "1.0.0-beta5"

**Comment by nadar** [comment]
I have added verbose output to crawlermodule, but now you have to update your environment to dev-master, so you could use this composer.json for example:

```
{
    "minimum-stability" : "dev",
    "require": {
        "luyadev/luya-core" : "dev-master",
	"luyadev/luya-module-cms" : "dev-master as 1.0.0-beta5",
        "luyadev/luya-module-cmsadmin" : "dev-master as 1.0.0-beta5",
        "luyadev/luya-module-admin" : "dev-master as 1.0.0-beta5",
	"luyadev/luya-module-crawler" : "dev-master as 1.0.0-beta5",
	"luyadev/luya-module-crawleradmin" : "dev-master as 1.0.0-beta5"
    },
    "require-dev": {
        "yiisoft/yii2-gii" : "~2.0.0",
        "yiisoft/yii2-debug" : "~2.0.0"
    },
    "extra": {
        "asset-installer-paths": {
            "bower-asset-library": "vendor/bower"
        }
    }
}
```
Then you have to upgrade your system described in the UPGRADE.md (https://github.com/luyadev/luya/blob/master/UPGRADE.md), in your case i guess you have to do only those steps.

**https://github.com/luyadev/luya-kickstarter, this is already prepared for the beta6 release so you can check the below describes steps in the dev-master of kickstarter project**

1. REPLACE CMSLAYOUTS TWIG FILES WITH PHP FILES:
Due to replacement of twig, cms layout files must be a phpfile instead of a twig file. The following file `main.twig` would be new `main.php`, file content compare:
  old:
  ```twig
  <div>{{placeholders.content}}</div>
  ```
  new:
  ```php
  <div><?= $placeholders['content']; ?></div>
  ```
https://github.com/luyadev/luya-kickstarter/blob/master/views/cmslayouts/main.php

2. **Remove** the LUYA module in your prep.config but **bootstrap the cms module **(you can see the already prepare new beta6 kickstarter as reference, https://github.com/luyadev/luya-kickstarter/blob/master/configs/prep.php)

3. Now run the migrate and import commands (`./vendor/bin/luya migrate` `./vendor/bin/luya import`).

4. As we have newly added page version (under developemnt, you will see) you have to run the upgrade command once: `./vendor/bin/luya command cmsadmin updater/versions`.

Now you will retrieve always the newest luya build with `composer update`, so you can the new luya toolbar for example.

**Comment by nadar** [comment]
(i have also made some phpdocs for the module configuration -> https://github.com/luyadev/luya-module-crawler/blob/master/Module.php)

**Comment by jepster** [comment]
Thanks for the detailed instructions. I could update Luya to the latest dev version (e.g. I see now the new Luya toolbar). The problem with impossible crawler indexing remains. My console output looks like follows:

> ./vendor/bin/luya command crawler crawl
> CRAWLER REPORT:
> 
>  update:
>  - http://localhost:8888/
> 
> Cralwer finished in 0.02 min.

**Comment by nadar** [comment]
Could you run the command with `--verbose` and print the result?

**Comment by jepster** [comment]
> ./vendor/bin/luya command crawler crawl --verbose
> [==================== VERBOSE ====================]
> baseUrl: http://localhost:8888/
> baseHost: localhost
> truncate of table crawerl_builder_index: yes
> Inspect URL Status: http://localhost:8888/
> found in builder index: no
> [================== VERBOSE END ==================]
> CRAWLER REPORT:
> 
>  unchanged:
>  - http://localhost:8888/
> 
> Cralwer finished in 0.02 min.

To be honest, the verbose output tells me nothing about the source of the problem.

**Comment by nadar** [comment]
Wow, yes it real does not tell anything helpfull :-) I am going to change that, but i are you sure when you open `http://localhost:8888/` in the browser (where the crawler is execute) you can see the website? And its not something like: `http://localhost:8888/luya-kickstarter/public_html`?

**Comment by nadar** [comment]
(in order to test the crawler, you could also just put `https://luya.io/` as `$baseUrl` and run the crawler, so we could see if its a problem related to your server, your base url or the connection made from your webserver)

**Comment by jepster** [comment]
Good news: https://luya.io/ as baseUrl works! :+1: 

>     'crawler'      => [
>       'class'   => 'crawler\Module',
>       'baseUrl' => 'https://luya.io/',
>     ],

Bad news is, that all my pages from my website aren't working after the update to dev version. I'm getting a 404. In the logs is "yii\base\InvalidRouteException" mentioned. Do you have an idea what was going wrong during the update?

**Comment by nadar** [comment]
Can you show me the exception trace? Have you bootstraped the cms module?

when you are running the dev-master you could `composer update` to get updates daily.

**Comment by jepster** [comment]
I've ran the "composer update" command. Yes, I'm using the cms module, since I have it in "prep.php":

>     /*
>      * You can use the cms module if you like.
>      */
>     'cms'               => [
>       'class'             => 'cms\Module',
>       'assets'            => [
>         'app\assets\ResourcesAsset'
>       ],
>       'enableCompression' => TRUE,
>       // compressing the cms output (removing white spaces and newlines)
>     ],

If I want to access a sub page from my website (everyhing except the frontpage), I'm getting the following output (all errors and warnings in php turned on):

> Not Found (#404)
> 
> Page not found.
> The above error occurred while the Web server was processing your request.
> 
> Please contact us if you think this is a server error. Thank you.
> 
> 2016-04-11 00:21:12

If I'm running the index command

> ./vendor/bin/luya command crawler crawl --verbose

I'm getting:

> [==================== VERBOSE ====================]
> baseUrl: http://localhost:8888/
> baseHost: localhost
> truncate of table crawerl_builder_index: yes
> Inspect URL Status: http://localhost:8888/
> found in builder index: no
> [================== VERBOSE END ==================]
> CRAWLER REPORT:
> 
>  unchanged:
>  - http://localhost:8888/
> 
> Cralwer finished in 0.01 min.

There are also menu items in the admin area broken now:
![screenshot](http://i.imgur.com/Vj3OAs1.jpg "Screenshot")

**Comment by nadar** [comment]
Original Topic: I guess the crawler works, but he can not access your page. I am going to add more verbose information in order to find out if this is the origin of your problem.

Menu Items translations: Yes, this is already fixed.

Config & Composer: Please write me in gitter so you can dump me the full config, we have also decided to remove all composer packagist dependencies in the beta version in order to solve problems with composer dev-master updates so you can now use in your composer.json (so now we have no stability flag restriction anymore, this will not end up in loading dev-master of package dependencies):

```json
{
    "require": {
        "luyadev/luya-core" : "^1.0@dev",
        "luyadev/luya-module-admin" : "^1.0@dev",
        "luyadev/luya-module-cms" : "^1.0@dev",
        "luyadev/luya-module-cmsadmin" : "^1.0@dev",
	"luyadev/luya-module-crawler" : "^1.0@dev",
	"luyadev/luya-module-crawleradmin" : "^1.0@dev"
    },
    "require-dev": {
        "yiisoft/yii2-gii" : "~2.0.0",
        "yiisoft/yii2-debug" : "~2.0.0"
    },
    "extra": {
        "asset-installer-paths": {
            "bower-asset-library": "vendor/bower"
        }
    }
}
```

**Comment by jepster** [comment]
Isn't then the following part missing?:

```
"extra": {
        "yii\\composer\\Installer::postCreateProject": {
			"setPermission": [
				{
					"public_html/assets": "0777",
					"public_html/storage": "0777"
				}
			]
		},
        "asset-installer-paths": {
            "bower-asset-library": "vendor/bower"
        }
    }
```

Permission setting and bower asset installer path.

**Comment by nadar** [comment]
This is just a relitc of when creating a project with `composer create-project` and is used once on (as you can see): `postCreateProject`

**Comment by jepster** [comment]
There are some news after the latest 

composer update

It seems that we are almost there. The crawler has just a problem with the base url. It seems that port 8888 from MAMP (http://localhost:8888) confuses him:

> ./vendor/bin/luya command crawler crawl --verbose
> [==================== VERBOSE ====================]
> baseUrl: http://localhost:8888/
> baseHost: localhost
> truncate of table crawerl_builder_index: yes
> Inspect URL Status: http://localhost:8888/
> found in builder index: no
> get content for: http://localhost:8888/
> url 'http://localhost/' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/php' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/php/how-to-use-phpunit-fixtures-in-your-yii2-development' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/php/yii2-access-your-services-within-your-module' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/php/yii2-bring-the-assets-from-your-module-to-your-view' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/php/debugging-php-cli-scripts-in-phpstorm-which-are-running-inside-a-vagrant-box-xde' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/mysql' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/mysql/mysql-dump-database-and-compress-it-from-command-line-via-mysqldump' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/git' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/git/git-fixing-error-src-refspec-branchname-matches-more-than-one' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/git/github-not-accepting-public-ssh-key-fix-it-by-switching-from-https-to-ssh-in-the' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/git/git-clean-cleaning-the-git-repository-to-be-able-to-merge-with-remote' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/git/git-fixing-line-ending-problem-at-windows-host-system-and-linux-guest-vagrant' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/rsync' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/rsync/rsync-two-folders-via-ssh-and-exclude-multiple-folders' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/miscellaneous' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/miscellaneous/fix-line-endings-between-various-file-systems' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/miscellaneous/drush-rebuild-the-cache-of-a-single-drupal-8-site-in-a-multi-site-setup-with-the' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/miscellaneous/rsync-sync-two-folders-via-ssh-in-both-directions' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/miscellaneous/ssh-fix-folder-and-file-permissions-for-ssh-folder' does not match baseUrl 'http://localhost:8888/': 
> url 'http://localhost/miscellaneous/sed-another-way-of-fixing-wrong-line-endings-on-linux' does not match baseUrl 'http://localhost:8888/': 
> [================== VERBOSE END ==================]
> CRAWLER REPORT:
> 
>  unchanged:
>  - http://localhost:8888/
> 
> Crawler finished in 0.02 min.

**Comment by jepster** [comment]
@nadar: Do you know a fix?

**Comment by nadar** [comment]
@jepster sorry for not replying. Yes i can see what happens, the crawler verify's if the baseUrl matches the Link on your webpage, and the webpage url does not have a port - so it does not match and skip's the url. Example:

baseUrl `http://localhost:8888/` in your config and the base href in your webpage (`<base href="https://localhost/" />` - as we are NOT using absolut urls (with domain.tld prefix) for the links, the crawler adds the html base href to every link in order to make absolute urls.

So could you not just add the base Url in your config without port 8888, or configure your mamp to use default port 80.

**Comment by nadar** [comment]
hi @jepster as already mentioned, the problem is the base url of your crawler configuration with/without the port. Maybe we can close this issue? Or is there anything i could help on this topic?

**Comment by jepster** [comment]
This issue could not be solved by changing the port in mamp. Luya crawler is just not able to handle urls with a port.

**Comment by nadar** [comment]
If you add the port to your baseUrl it should work. Otherwise it would not make sense to go use a port if it would work without. Am i wrong? Thanks for fast reply

**Comment by jepster** [comment]
Of course I have tried it with the port and it didn't worked.

**Comment by nadar** [comment]
Thank you @jepster i guess i have fixed the problem now, my local tests has been successfull with port:

```
php index.php crawler/crawl --verbose
[==================== VERBOSE ====================]
baseUrl: http://localhost:8080/luya/envs/dev/public_html/
baseHost: localhost
truncate of table crawerl_builder_index: yes
Inspect URL Status: http://localhost:8080/luya/envs/dev/public_html/
memory usage: 3927056
memory usage peak: 4129976
found in builder index: no
get content for: http://localhost:8080/luya/envs/dev/public_html/'http://localhost:8080/luya/envs/dev/public_html/': 
Inspect URL Status: http://localhost:8080/luya/envs/dev/public_html/en/dfsdfsfsdf
memory usage: 6103312
memory usage peak: 6267160
found in builder index: yes
get content for: http://localhost:8080/luya/envs/dev/public_html/en/dfsdfsfsdf
'http://localhost:8080/luya/envs/dev/public_html/': 
Inspect URL Status: http://localhost:8080/luya/envs/dev/public_html/en/234234234234
memory usage: 6117432
memory usage peak: 6267160
found in builder index: yes
get content for: http://localhost:8080/luya/envs/dev/public_html/en/234234234234'http://localhost:8080/luya/envs/dev/public_html/': 
[================== VERBOSE END ==================]
CRAWLER REPORT:

 unchanged:
 - http://localhost:8080/luya/envs/dev/public_html/
 - http://localhost:8080/luya/envs/dev/public_html/en/dfsdfsfsdf
 - http://localhost:8080/luya/envs/dev/public_html/en/234234234234

memory usage: 6.37 MB
memory peak usage: 6.49 MB

Crawler finished in 0 min.
```

**Comment by nadar** [comment]
@jepster so i guess now i can close this issue. Thanks again for your report!

**Comment by jepster** [comment]
You can close it. Thank you for your quick and detailed reply.
