### ISSUE TITLE
Textarea heights

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#830]
Adapt the textarea height to the text.

**Comment by nadar** [comment]
@TheMaaarc i already implemented such a method for testing purposes, but it seems that we have to add a fix line-height or something?

**Comment by nadar** [comment]
I think there are a few things which calculates the height absolut wrong.

![image](https://cloud.githubusercontent.com/assets/3417221/18830136/ab1e65e4-83df-11e6-97ca-60ab35bdbb5c.png)
