### ISSUE TITLE
zaa-checkbox in block

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#835]
Used a zaa-checkbox in cfg of block. It didn't got serialized and sent to the server (cfg json not in db).

```
'cfgs' => [
    ['var' => 'groupCaptions', 'label' => 'Mobil: Legenden Gruppieren', 'type' => 'zaa-checkbox'],
]
```

**Comment by nadar** [comment]
Can't reproduce. I guess this has been fixed by solving another problem (empty array save of in database).
