### ISSUE TITLE
Admin page not found

### ISSUE THREAD

**Issue by MarcosGit** [luyadev/luya#854]
i installed luya in ubuntu and the installed successful page is work fine but when i try admin page i recive: The requested URL /luya-kickstarter/public_html/admin was not found on this server.

**Comment by nadar** [comment]
Could you please run this script and post me the result?

https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e

Things to check:

+ Is mod rewrite enabled on your webserver?
+ is the `.htaccess` file available in public_html folder?
+ When using url ` /luya-kickstarter/public_html/index.php/admin` the admin dialog appears?

**Comment by MarcosGit** [comment]
script output
1: [in_array('mod_rewrite', apache_get_modules());] true
2: [ini_get('short_open_tag');] '1'
3: [ini_get('error_reporting');] '22527'
4: [phpversion()] '5.5.9-1ubuntu4.16'
5: [php_ini_loaded_file()] '/etc/php5/apache2/php.ini'

when i using  url: /luya-kickstarter/public_html/index.php/admin the admin dialog dont appears to.

**Comment by nadar** [comment]
But the admin module is in your composer.json and exists in your configuration file?

**Comment by MarcosGit** [comment]
composer.json:
  "require": {
        "luyadev/luya-core" : "1.0.0-beta6",
        "luyadev/luya-module-admin" : "1.0.0-beta6",
        "luyadev/luya-module-cms" : "1.0.0-beta6",
        "luyadev/luya-module-cmsadmin" : "1.0.0-beta6"
    },

config file:

'admin' => [
            'class' => 'admin\Module',
            'secureLogin' => false, // when enabling secure login, the mail component must be proper configured otherwise the auth token mail will not send.
        ],

**Comment by nadar** [comment]
Config is looking good, and i assume the `luyadev/luya-module-admin` folder exists in your `vendor` directory(?).

> when i using url: /luya-kickstarter/public_html/index.php/admin the admin dialog dont appears to.

1. It still returns `was not found on this server`? Or is there another message? But when you access `/luya-kickstarter/public_html/index.php` you get the start page with the "welcome" dialog - like the same when you run `.../public_html/` without index.php?
2. Could you make sure `AllowOverride` is configure well in your apache config? http://askubuntu.com/a/538212

Its Ubuntu 14.04 server? So i can install a clean server as well for testing purpose.

**Comment by MarcosGit** [comment]
Great i add this code in apache config and its work good:

<Directory "/var/www/html">
    AllowOverride All
</Directory>

Thank you very much for this help and for this great cms.

**Comment by nadar** [comment]
@MarcosGit You'r welcome. Let us know if you have any problems or feature request.

**Comment by MarcosGit** [comment]
i will.
