### ISSUE TITLE
Menu item "News" is missing

### ISSUE THREAD

**Issue by MarcosGit** [luyadev/luya#855]
I can not see the "News" item.

**Comment by nadar** [comment]
I need more informations.

+ Its a module? Have you created the Module?
+ Are u missing the Admin Panel?
+ Its a CMS Page you have added with content? Its a module block? its a page with type module?

Maybe show us some screenshots?

**Comment by nadar** [comment]
@MarcosGit are you trying to install the news module? https://github.com/luyadev/luya-module-news

**Comment by MarcosGit** [comment]
Hi nadar, sorry for the late answer.

Sorry again, I will install this module. The problem is i was thinking that module comes together with Luya because i see it in your videos tutorials.

Thank you again for your time.
