### ISSUE TITLE
CMS Blocks dinamic fields 

### ISSUE THREAD

**Issue by MarcosGit** [luyadev/luya#862]
Hi Nadar, i need your help.

I am trying to see the source code about de Link Button block to understand how you shows dynamically information according to the user choice, but i am not understand how you are doing this.

I am trying to create one slider block and i want to show the user one select to chose the number of image and after i want to show the same number of uploadImage fields.

Tks.

**Comment by nadar** [comment]
Hi @MarcosGit 

So you would like to make a block where to user can upload images and you implement a slider in the frontend view? Do you already have source could show me?

You could create a block with the block wizzard and choosing the `image-array-upload` type.

**Comment by nadar** [comment]
i just created a very quick block with the wizzard

```php
<?php

namespace app\blocks;

use Yii;

/**
 * Block created with Luya Block Creator Version 1.0.0-beta7-dev at 12.05.2016 21:08
 */
class SliderBlock extends \cmsadmin\base\Block
{
    /**
     * @var bool Choose whether block is a layout/container/segmnet/section block or not, Container elements will be optically displayed
     * in a different way for a better user experience. Container block will not display isDirty colorizing.
     */
    public $isContainer = false;

    /**
     * @var bool Choose whether a block can be cached trough the caching component. Be carefull with caching container blocks.
     */
    public $cacheEnabled = false;

    /**
     * @var int The cache lifetime for this block in seconds (3600 = 1 hour), only affects when cacheEnabled is true
     */
    public $cacheExpiration = 3600;

    public function name()
    {
        return 'SliderBlock';
    }

    public function icon()
    {
        return 'extension'; // choose icon from: http://materializecss.com/icons.html
    }

    public function config()
    {
        return [
           'vars' => [
               ['var' => 'images', 'label' => 'Slider Images', 'type' => 'zaa-image-array-upload', 'options' => ['no_filter' => false]],
           ],
        ];
    }

    /**
     * Return an array containg all extra vars. Those variables you can access in the Twig Templates via {{extras.*}}.
     */
    public function extraVars()
    {
        return [
            'images' => $this->zaaImageArrayUpload($this->getVarValue('images')),
        ];
    }

    /**
     * Available twig variables:
     * @param {{extras.images}}
     * @param {{vars.images}}
     */
    public function twigFrontend()
    {
        return '{% for image in extras.images %} {{ dump(image) }} {% endfor %}';
    }

    /**
     * Available twig variables:
     * @param {{extras.images}}
     * @param {{vars.images}}
     */
    public function twigAdmin()
    {
        return '<p>Images Slider</p>';
    }
}
```

**Comment by nadar** [comment]
You may also want to check the other standard blocks in order to understand how they are build: https://github.com/luyadev/luya-module-cmsadmin/tree/master/src/blocks

**Comment by MarcosGit** [comment]
Ok, but in my case for each slider image i want more other vars like "Title, description and button".
So i want to do some thing like linkButton, user can chose internal page or external URl and after user select one he can see diferente form for each one. 

I see in this link a code-source linkButton Block but I can not understand what you do to generate this dynamic form, according to user selection.

I want one slider like this: http://demo.graygrids.com/themes/margo/index.html

I already did one slider and is work good, but for this i create tree block:

**SliderBlock** - just one block with placeholder to get others block
**ItemSliderBlock** - this block is just to put image inside the SliderBlock
**TextBlock** - to put text inside the itemSlideBlock
But i want to reduce this blocks to one Slide Block.


See the image:
![screenshot from 2016-05-13 09 14 09](https://cloud.githubusercontent.com/assets/13893469/15245148/0e74cf0c-18ec-11e6-9459-c2bab8dba665.png)

**Comment by nadar** [comment]
I think the approach you do its pretty good in terms of flexible re-usable code.

SliderContainer: The Block with the Placeholder (Like you already did, but set `$isContainer = true`.
SliderElement: Instead of using several blocks you can make one (1) block with multiple vars. A var for the title, one for the image, one for the link, etc.

```php
return [
'vars' => [
 ['var' => 'title', 'label' => 'Title', 'type' => 'zaa-text',
 ['var' => 'text', 'label' => 'Text', 'type' => 'zaa-textarea',
 ['var' => 'image', 'label' => 'Image', 'type' => 'zaa-image-upload',
],
];
```

*This wy you could also display the images of the slider in the admin view, this way it would be more understandable in the administration area*

@LinkButton:

The link button uses an angular directive called `zaa-link` which is an administration implemenation, you can also write your own angular type plugins if you like to. But its maybe not what you want.

We are working on such "form change behaviors based on several selections", to make block forms more flexible.

**Comment by MarcosGit** [comment]
I will change the SliderElement like you sad.

Thanks.
