### ISSUE TITLE
Template does not remove

### ISSUE THREAD

**Issue by MarcosGit** [luyadev/luya#866]
Hi Nadar.

I create one page as template but when i want to remove it the delete button in the confirmation box not working.

Tks.

**Comment by nadar** [comment]
What do you mean with tempalte? Cms layout? Block? Views? Renders? Could you please show us some screenshots.

**Comment by MarcosGit** [comment]
![screenshot from 2016-05-18 09 25 05](https://cloud.githubusercontent.com/assets/13893469/15355593/cb25e46e-1cda-11e6-899d-74c89c2063c4.png)

**Comment by nadar** [comment]
Thank you @MarcosGit, indeed its not yet possible to remove a template. We are going to add this feature to the list.

**Comment by nadar** [comment]
@MarcosGit I just fixed this problem, you could retrieve the newest version by using the dev-master (https://luya.io/en/guide/install-structures#composer-dev) or wait until beta7 release.

**Comment by MarcosGit** [comment]
Ok. Thanks.
