### ISSUE TITLE
Website not found

### ISSUE THREAD

**Issue by codexdb** [luyadev/luya#868]
After installation (beta6 under jessie) admin connection shows homepage in preview and frontend site access works fine. Without changing anything on next day preview is OK, but site access is refused with error. 

`Not Found (#404) Home item could not be found, have you forget to set a default page?`

**Comment by nadar** [comment]
hi @codexdb i just formated your message a little bit, and i guess the exception already tells you what the error might be: **have you forget to set a default page?**

So i guess you have disabled your "Homepage" in the CMS Module, we know its possible to disabled an existing homepage, so we have fixed that already in the next release (beta7).

So make sure you got that "home" icon somewhere in your navigation tree, or enable it for a page.

![selection_010](https://cloud.githubusercontent.com/assets/3417221/15398838/8534a088-1de5-11e6-80c6-56fc91e092f8.png)

Change the homepage:

![selection_012](https://cloud.githubusercontent.com/assets/3417221/15398853/9e814e2e-1de5-11e6-933f-e32e2292e7a0.png)

**Comment by codexdb** [comment]
@nadar, thanks for the formatting, but i have to confess: I did something: 
After installation i changed (because i am native german speaking) the names and codes for english and german language in menu system. Therefore the cms could not combine the right language id for the home page.
Here is the solution.
In the database table cms_nav_item, i set by hand the value in the column lang_id to the new changed value - in my case from 1 to 2. Perhaps a hint for further development.

And - most important - congratulations to you a well designed designed project. Gruezi

**Comment by nadar** [comment]
I guess you could have done this also in the administration area without touching the database (of course its always better to understand what happens in the database and how you can change things). At least in beta7 we have enhanced the language administration area.

Thank YOU, for using LUYA. We love to hear from people using LUYA making the project better! Gruss aus der Schweiz.

**Comment by nadar** [comment]
@codexdb i assume we can close this issue?
