### ISSUE TITLE
Change base layout

### ISSUE THREAD

**Issue by codexdb** [luyadev/luya#869]
Is there a way to assign to every page in a project a different layout than the base layout main (in @app/views/layouts) other than renaming or write a custom controller?

**Comment by nadar** [comment]
@codexdb The best approach to achieve your goal is by using a very basic layout (maybe just return `$content` inside the body) file but using different cmslayouts, so you can choose different cmslayout and add layout ability to them.

https://luya.io/en/guide/app-cmslayouts

Does this help?

But there is also an issue for choosing different layouts in cms context: https://github.com/luyadev/luya/issues/863

**Comment by nadar** [comment]
@codexdb can we close this issue?
