### ISSUE TITLE
URL path generation: longer dashes to hyphens

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#871]
When automatically generating the URL path for a page based on the page title, em dashes (—) and en dashes (–) should be converted to hyphens (-).

Currently they are deleted:
Page title: Sculpture on the move 1946–2016
URL path: sculpture-on-the-move-19462016

Better would be:
Page title: Sculpture on the move 1946–2016
URL path: sculpture-on-the-move-1946-2016

**Comment by nadar** [comment]
@rolandschaub https://github.com/paulsmith/angular-slugify
