### ISSUE TITLE
How can i use luya-module-contactform

### ISSUE THREAD

**Issue by MarcosGit** [luyadev/luya#872]
Hi.

I finished to install the contact form module but i do not know how use it in my web page.

**Comment by nadar** [comment]
You can setup a page as module, or just drag the "Module block" into a webpage and select your contactform module (make sure you have registered the contact form in your config)

**Comment by MarcosGit** [comment]
ok, very good and very easy.

So i have to create the index file in **"my-project/views/contactform/default/index.php"**

**Comment by nadar** [comment]
Yes exactly. We have to add a better view file example in the documentations, and also provided an variable where you can already retrieve data from.

**Comment by MarcosGit** [comment]
Ok thanks.

**Comment by nadar** [comment]
@MarcosGit There is also a video available on youtube which integrates the news module: 

https://youtu.be/DmMDmTP9oC8?list=PLxGm47O0IpXHrypOnHRxm9qGdvY3pdu-h
