### ISSUE TITLE
Provide CSV/Excel download for ngrest crud list

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#873]
Basic implementation for downloading the crud data based on the ngrest model active record.

**Comment by nadar** [comment]
![image](https://cloud.githubusercontent.com/assets/3417221/15466570/920c1d34-20da-11e6-9ee4-bed410839c8e.png)

@TheMaaarc Styling - maybe put the button on the top right side?

**Comment by TheMaaarc** [comment]
Button's now on the right and styles.

![luya csv button](https://cloud.githubusercontent.com/assets/3450438/15476173/eefd9ec2-210d-11e6-9ff2-da0d26984ecc.gif)

**Comment by nadar** [comment]
@TheMaaarc looks great! Maybe it would take less space when the search and export buttons are next to each other instead of above? col s9 - s3 -- something like this?
