### ISSUE TITLE
Dinamic Edit Luya Layout 

### ISSUE THREAD

**Issue by MarcosGit** [luyadev/luya#884]
Hi.

Nadar Luya has some way to dynamic edit layout in luya admin?
For example i have one site and i need to give user one way to edit header and footer contents from de luya admin side.

Thanks.

**Comment by nadar** [comment]
Well, i am not sure to understand right. But i guess you want an ability to dynamic create *placeholders*? Or is it more a question about permissions?

You could make a layout with

+ header
+ content
+ footer

so you could put contents to those placeholders. A footer is also commonly used as an additional Menu Container where you can return a footer navigation.

Maybe you also want to just return an editable area in the Layout? So you could access a placeholder inside of a page withing the layout:

```php
use \cmsadmin\models\Nav;

echo Nav::findOne(123)->activeLanguageItem->type->renderPlaceholder('placeholder-name-header');
```

**Comment by MarcosGit** [comment]
No, is was not about dynamic placeholders or permission.

You can see this image:
![screenshot from 2016-05-31 09 55 58](https://cloud.githubusercontent.com/assets/13893469/15680708/de02047e-273d-11e6-8ca2-959b2b5d9c78.png)

I want to put one luya block "contact information" on the red box, and user can change the contact information in luya admin side.

**Comment by nadar** [comment]
I understand. Currently there is no such implementation. As this is mostly very static content and not part of the Cms Layouts. But you could do it like described above:

1. create a new cms admin menu Container e.g. `footer`.
2. create a cmslayout which is *blank*, e.g. content `<?= $placeholders['content']; ?>`
3. create a new page *Footer Content* with the cmslayout `blank` and save it into the the footer container.
4. Now create your block and add it into the *Footer Content* Page.
5. Get the content: 

```
use \cmsadmin\models\Nav;

echo Nav::findOne(123)->activeLanguageItem->type->renderPlaceholder('content');
```

*123 is the ID of the page, you can see the id by hovering over the menu in the administration interface.*

**Comment by MarcosGit** [comment]
Worked perfect thank you so much.
