### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by dtpop** [luyadev/luya#886]
When using this command in the terminal on Mac

composer create-project luyadev/luya-kickstarter:1.0.0-beta6

I get the following message:

Reading bower.json of bower-asset/jquery.inputmask (3.1.53)
Could not fetch https://api.github.com/repos/RobinHerbots/jquery.inputmask/commits/1a863a0c9b733444f6766e5500eaf79b7b1d1d03, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+mein-iMac.local+2016-06-02+0804
to retrieve a token. It will be stored in "/Users/ich/.composer/auth.json" for future use by Composer.
Token (hidden): 

The installation is not completed.

**Comment by nadar** [comment]
The error message contains the reason why the installation is not completed:

```
Could not fetch https://api.github.com/repos/RobinHerbots/jquery.inputmask/commits/1a863a0c9b733444f6766e5500eaf79b7b1d1d03, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+mein-iMac.local+2016-06-02+0804
to retrieve a token. It will be stored in "/Users/ich/.composer/auth.json" for future use by Composer.
Token (hidden):
```

This is also mentioned in the Yii2 Guide (http://www.yiiframework.com/doc-2.0/guide-start-installation.html): 

```
Note: During the installation Composer may ask for your Github login credentials. This is normal because Composer needs to get enough API rate-limit to retrieve the dependent package information from Github. For more details, please refer to the Composer documentation.
```

So you just can click on the link provided in the console:

```
https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+mein-iMac.local+2016-06-02+0804
```

Just press submit and create a token, copy paste it into the terminal and continue installation.

**Comment by dtpop** [comment]
Thanks, installation has now completed!

**Comment by nadar** [comment]
Maybe this should be added to the installation guide? https://github.com/luyadev/luya/blob/master/docs/guide1.0/install.md
