### ISSUE TITLE
Some scripts afected by luya block "Module"

### ISSUE THREAD

**Issue by MarcosGit** [luyadev/luya#887]
When i use luya block "Module" and i choose one Module some block of my code don’t work very good.
This image is before i use block "Module" with contactForm:

![screenshot from 2016-06-02 15 14 42](https://cloud.githubusercontent.com/assets/13893469/15752859/32c4d1ae-28d7-11e6-8ce7-9f5134dba35d.png)

This image is after i use block "Module" with contactForm:

![screenshot from 2016-06-02 15 15 53](https://cloud.githubusercontent.com/assets/13893469/15752873/423f91be-28d7-11e6-931d-0a003eaf3785.png)

**Comment by nadar** [comment]
can you see a difference in HTML output? Or are there any asset loading when using the module block?

**Comment by nadar** [comment]
The module block does only render what your view contains. So i don't think this is a problem of LUYA and its module block rendering behavior.

**Comment by MarcosGit** [comment]
ok i will see it.

thanks.

**Comment by nadar** [comment]
Maybe you could create 2 gist (gist.github.com) files with the FULL HTML-DUMP for booth situations, one with module block and one without. So maybe i can see something which could be related to your problem.

**Comment by MarcosGit** [comment]
I see some difference between this two situations in loaded javascript files:

see the two source code in this link: 
https://gist.github.com/MarcosGit/770ec47c4e7c0ccf286476713efb5569

**Comment by nadar** [comment]
Do you have a javascript error in your console? As i can see you have two versions of jquery included, this may lead into problems. You should always depend on `yii\web\JqueryAsset` in your assets files and not include your own jquery files. Active Form widget includes JqueryAsset file. So us:

```
$depends = [
    'yii\web\JqueryAsset',
];
```

in your project asset file.

**Comment by MarcosGit** [comment]
Great, now it's working good. Thank you again for your time.
