### ISSUE TITLE
luya module mailchimp "Invalid MailChimp API key"

### ISSUE THREAD

**Issue by MarcosGit** [luyadev/luya#889]
Hey, Nadar i am trying to subscribe email in mailchimp but its return is this error:

**An error occured.
Invalid MailChimp API key: MailChimp API Key (104)**

**Comment by nadar** [comment]
Well, i would say the error say that your Api Key you use to communicate with Mailchimp seems not valid.

**Comment by MarcosGit** [comment]
Yes in my config file i have this **'mailchimpApi' => 'MailChimp API Key',** 

How i can configure a valid mailchimpApi?

**Comment by MarcosGit** [comment]
Sorry but i see it in the mailchimp web page and i have to generate one API KEY.
