### ISSUE TITLE
Ability to delete a version

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#894]
Add an ability to delete a version if count of version is >1

**Comment by nadar** [comment]
I just added the ability to remove version, we should fix the proplem with the "static width" of the Current Version: $title <edit> <delete> element as now the delete button mostly appears on a new line.

**Comment by nadar** [comment]
@TheMaaarc see previous comment.

**Comment by TheMaaarc** [comment]
@nadar Please fix the click actions for edit and delete of a page version.

`cmsadmin/page/update.php` roughly around line 458

**Comment by nadar** [comment]
![image](https://cloud.githubusercontent.com/assets/3417221/17341185/c6a26822-58f3-11e6-930b-b83f622c501a.png)

align right?

**Comment by nadar** [comment]
![image](https://cloud.githubusercontent.com/assets/3417221/17341283/25d19bce-58f4-11e6-9778-8d414ab9d534.png)

they overlap, but they should not stick open. only on hover.
