### ISSUE TITLE
Luya admin folder

### ISSUE THREAD

**Issue by janilsonlima1** [luyadev/luya#899]
I used the totorial in these link "https://luya.io/en/guide/install" to install Luya but was installed without directory admin

**Comment by janilsonlima1** [comment]
Someone can help me

**Comment by nadar** [comment]
Hi, the admin module is installed via composer into the vendor folder, so there is no admin folder in your application directory. What kind of error message do you get?

**Comment by janilsonlima1** [comment]
The error message is this "The requested URL /luya/public_html/admin was not found on this server".

**Comment by nadar** [comment]
Is mod rewrite enabled on your server? Could you please run this Script and copy the response here: https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e

**Comment by janilsonlima1** [comment]
The reponse was this:
1: [in_array('mod_rewrite', apache_get_modules());] false
2: [ini_get('short_open_tag');] ''
3: [ini_get('error_reporting');] '22527'
4: [phpversion()] '5.5.9-1ubuntu4.17'
5: [php_ini_loaded_file()] '/etc/php5/apache2/php.ini'

**Comment by janilsonlima1** [comment]
1: [in_array('mod_rewrite', apache_get_modules());] true
2: [ini_get('short_open_tag');] '1'
3: [ini_get('error_reporting');] '22527'
4: [phpversion()] '5.5.9-1ubuntu4.17'
5: [php_ini_loaded_file()] '/etc/php5/apache2/php.ini'

**Comment by janilsonlima1** [comment]
Thank's very much. The admin mode opened.

**Comment by nadar** [comment]
Perfect. So maybe we can close this issue?

**Comment by janilsonlima1** [comment]
1: [in_array('mod_rewrite', apache_get_modules());] true
2: [ini_get('short_open_tag');] '1'
3: [ini_get('error_reporting');] '22527'
4: [phpversion()] '5.5.9-1ubuntu4.17'
5: [php_ini_loaded_file()] '/etc/php5/apache2/php.ini'

**Comment by janilsonlima1** [comment]
Yes, doing what now?

**Comment by nadar** [comment]
click the **close issue** button.
