### ISSUE TITLE
Backup and restore of my luya project

### ISSUE THREAD

**Issue by MarcosGit** [luyadev/luya#922]
Good afternoon Nadar.
How are you?

I have one problem and need your help.

I did backup of my luya project and database and now i want to restore it again on ubuntu 16.04 and when i try to access public_html/admin i have this error:

Not Found

The requested URL /NLCVPF_Website/public_html/admin was not found on this server.
Apache/2.4.18 (Ubuntu) Server at localhost Port 80

Cps.

**Comment by nadar** [comment]
Sounds like a mod_rewrite/server specific problem.
Am 08.07.2016 6:56 nachm. schrieb "MarcosGit" <notifications@github.com>:

**Comment by MarcosGit** [comment]
I have set up the mod_rewrite. Frontend is working but when i try to access menu item like contact, I have this error:

Not Found

The requested URL /public_html/aboutus was not found on this server.
Apache/2.4.18 (Ubuntu) Server at localhost Port 80

**Comment by nadar** [comment]
Htaccess file exists?
Am 08.07.2016 7:26 nachm. schrieb "MarcosGit" <notifications@github.com>:

**Comment by MarcosGit** [comment]
If you are talking about the Htaccess inside public_html, yes the file exists.

**Comment by nadar** [comment]
So then its definitly mod rewrite. Admin panel display when using
..../public_html/index.php/admin link? Then luya is working and its an
issue with the server.
Am 08.07.2016 8:08 nachm. schrieb "MarcosGit" <notifications@github.com>:

**Comment by MarcosGit** [comment]
Ok, is working now.

I have added this code:

<Directory "/var/www/html">
   AllowOverride All
</Directory>

 in /**etc/apache2/sites-available/000-default.conf** after **DocumentRoot /var/www/html**

Thanks for your time.
