### ISSUE TITLE
'datetime' plugin doesn't reset correctly

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#927]
1. Open a record with a value in "datetime" field
2. Open another record with no value in "datetime" field: Displays value of previous record set

**Comment by nadar** [comment]
Replaced by using a Datepicker and refactor of Datetime and Date angular directives.

**Comment by nadar** [comment]
@TheMaaarc Styling of Datetime/Date directive and Datepicker.

**Comment by nadar** [comment]
+ problems with `null` values (the datetime is prefilled with todays date but should be null)
+ problems as of server side date response calculation in order to sort the data.
