### ISSUE TITLE
FEATURE IDEAS ADMIN 2.0

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#950]
- compact inline filemanager/file picker
- markdown editor integration
- optimiced filemanager

**Comment by TheMaaarc** [comment]
Filemanager ideas: https://www.behance.net/gallery/14580961/Kudos-File-Manager-Web-App

**Comment by vuongminh** [comment]
I think Luya need add wysiwyg editor for text like ckeditor.

**Comment by nadar** [comment]
@vuongminh We already have a basic wysiwyg editor for bold italic formatting and and creating lists  its the "Texteditor" block.

But a huge editor like CkEditor is not what we want, it just generates ugly code. We have blocks to do all those jobs very easy, like a table block, list and image blocks. We recommend people more to create their own blocks which fits the needs of the websites layout.

**Comment by sokollondon** [comment]
In the wysiwyg editor (TinyMCE, CkEditor), most blocks are created much faster. I would like to be able to add TinyMCE and adjust it.

**Comment by nadar** [comment]
If its really something more people request, i am going to make a repository with those blocks you can add to your project. But as i already told, we strongly do not believe in WYSIWYG editors:

> But a huge editor like CkEditor is not what we want, it just generates ugly code. We have blocks to do all those jobs very **easy**, like a table block, list and image blocks. We recommend people more to create their own blocks which fits the needs of the websites layout.

When you have split your content into blocks you can more easy add functions like OG/LD Tags, Enhance the base blocks with powerfull functions and evolve the internal blocks, move them to another location, etc.
