### ISSUE TITLE
TagParser::convertWithMarkdown wraps output in additional <p>

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#955]
TagParser::convertWithMarkdown creates HTML code like the following, wrapping the output in an additional `<p>` tag:

```html
<p><p>Paragraph 1</p>
<p>Paragraph 2</p>
</p>
```

The correct output would be:

```html
<p>Paragraph 1</p>
<p>Paragraph 2</p>
```

Original textarea content:

```
Paragraph 1
Paragraph 2
```

**Comment by nadar** [comment]
Could you please show me the code where the parser is used? Maybe its an issue with the context. (E.g. block which wrappes the output into a p tag)

**Comment by rolandschaub** [comment]
Stupid me, that was the problem. I noticed the problem in some older code – should have checked beforehand.  :-(
