### ISSUE TITLE
Error on import Filter::identifier

### ISSUE THREAD

**Issue by Misavan** [luyadev/luya#980]
### What steps will reproduce the problem?
./vendor/bin/luya import

### What do you get instead? (A Screenshot can help us a lot!)
Exception while importing: 'Static function admin\base\Filter::identifier() should not be abstract' in file 'D:\www\luya-kickstarter\vendor\luyadev\luya-module-admin\src\base\Filter.php' on line '39'.

**Comment by nadar** [comment]
Yes, its a bug. Sorry to say that. You could change to php7 (as it appears from 5.2 - 5.6l or install the kickstarter from the latest dev master

**Comment by Misavan** [comment]
If it is already solved in master and will be in next beta, then it is fine.

**Comment by nadar** [comment]
@Misavan Thank you for the report and sorry the trouble. Actually the next release will be RC1, as we are very close to a stable version of LUYA. 🎉
