### ISSUE TITLE
Image filters: CMYK > RGB conversion

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya#986]
When applying a filter to a CMYK image, the color space of the resulting image should be converted to RGB color space.

**Comment by nadar** [comment]
http://imagine.readthedocs.io/en/latest/usage/colors.html#palette-class

**Comment by nadar** [comment]
@rolandschaub Well i am not sure how to reproduce this issue? could you provide me an image?

**Comment by rolandschaub** [comment]
![gdn_sw_fz](https://cloud.githubusercontent.com/assets/3786245/18469247/c72120d4-79a7-11e6-9f67-1b80ee2afa55.jpg)

**Comment by rolandschaub** [comment]
Original file:

[GdN_SW_FZ.jpg.zip](https://github.com/luyadev/luya/files/469414/GdN_SW_FZ.jpg.zip)

**Comment by nadar** [comment]
if i add the image to the filemanager, i can not see any difference.
