### ISSUE TITLE
import script error on Windows 10

### ISSUE THREAD

**Issue by kmergen** [luyadev/luya#993]
### What steps will reproduce the problem?
Setup step ```php index.php import``` 

### What do you get instead? (A Screenshot can help us a lot!)
```Exception while importing: 'Static function admin\base\Filter::identifier() should not be abstract' in file 'C:\www\luya1\vendor\luyadev\luya-module-admin\src\base\Filter.php' on line '39'.```

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      | 5.6.24
| Platform         | Wamp64
| Operating system | Windows 10

**Comment by nadar** [comment]
Yes, this is a bug on the beta8 release with php 5.4 - 5.6. Sorry to say that. Rc1 release will be in the next days, so you could temporary just install the dev-master  kickstarter which fixes this problem.

```
composer global require "fxp/composer-asset-plugin:^1.0@dev
```

**Comment by kmergen** [comment]
Thanks.
Have try to install dev-master but get the following error if i try to migrate:
```Exception 'ReflectionException' with message 'Class admin\Module does not exist'```

Before I run migration I have copied the two dist files in configs folder.

**Comment by nadar** [comment]
Yes, i just saw this too, just change in your *env-local.php* config from `'class' => 'admin\Module',` to `'class' => 'luya\admin\Module',`

**Comment by kmergen** [comment]
Thanks. It worked now . I will explore the cms now.

**Comment by nadar** [comment]
all right enjoy, let us know via [gitter](https://gitter.im/luyadev/luya) if you need support or have any questions.
