### ISSUE TITLE
Error in module when set controller action

### ISSUE THREAD

**Issue by kmergen** [luyadev/luya#997]
### What steps will reproduce the problem?
Error if trying to add a controller action to module in admin UI

![screen2](https://cloud.githubusercontent.com/assets/1640101/19021512/ad6470ee-88c3-11e6-929a-3f71c19dbb49.PNG)
![screen3](https://cloud.githubusercontent.com/assets/1640101/19021532/1c04484e-88c4-11e6-9aa2-a5979c3be053.PNG)
![sreen4](https://cloud.githubusercontent.com/assets/1640101/19021533/26817b84-88c4-11e6-8686-b0b289815947.PNG)

### What is the expected result?
A rendered view file with items of a model

### What do you get instead? (A Screenshot can help us a lot!)
following error message:
 
![screen1](https://cloud.githubusercontent.com/assets/1640101/19021500/6aabe908-88c3-11e6-96d0-1442e53e8e35.PNG)

But when I set nothing that I get the result from DefaultController indexAction:
![screen4](https://cloud.githubusercontent.com/assets/1640101/19021555/cdca9bc8-88c4-11e6-8116-435077037040.PNG)
![screen5](https://cloud.githubusercontent.com/assets/1640101/19021557/d2b08d28-88c4-11e6-8d49-82d1174b274e.PNG)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev-master
| PHP Version      |5.6.24
| Platform         | Wamp64.
| Operating system | Windows 10

**Comment by nadar** [comment]
I am trying to reproduce this issue, give me a few hours. 

The problem appears only when using a different action? What happens if you set the action value to `index` (which would be equals to not setting an action value).

(btw: would love to try the `Hippenheimer Arschfurz 2011` wine, sounds delicious.)

**Comment by kmergen** [comment]
I get the same error.
![screen6](https://cloud.githubusercontent.com/assets/1640101/19021834/636610cc-88ca-11e6-9466-99eb9d6e277d.PNG)
![sreen7](https://cloud.githubusercontent.com/assets/1640101/19021838/684b2c08-88ca-11e6-918c-2477b8d4865a.PNG)

**Comment by nadar** [comment]
Are you on dev-master (rc1-dev)? You already have the `env.php` config in your configs folder or is it still `server.php` - if have made a small change, so you could run composer update (but if you are on the old configs structure, then you have to change the those filenames.

**Comment by kmergen** [comment]
Here is my config folder
![screen7](https://cloud.githubusercontent.com/assets/1640101/19041826/f12b551a-8989-11e6-982a-f5cb4e708f3a.PNG)

Here my composer.json
```json
{
    "name": "luyadev/luya-kickstarter",
    "description": "The kickstarter for a new LUYA application project.",
    "type": "project",
    "license":"MIT",
    "require": {
        "luyadev/luya-core" : "^1.0@dev",
        "luyadev/luya-module-admin" : "^1.0@dev",
        "luyadev/luya-module-cms" : "^1.0@dev",
        "luyadev/luya-module-styleguide" : "^1.0@dev"
    },
    "require-dev": {
        "yiisoft/yii2-gii" : "^2.0",
        "yiisoft/yii2-debug" : "^2.0"
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
			"setPermission": [
				{
					"public_html/assets": "0777",
					"public_html/storage": "0777"
				}
			]
		},
		"asset-pattern-skip-version": "(-build|-patch)",
        "asset-installer-paths": {
            "bower-asset-library": "vendor/bower"
        },
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        }
    }
}
```

**Comment by nadar** [comment]
Perfect. Just run composer update

**Comment by kmergen** [comment]
It works now. Thanks

**Comment by nadar** [comment]
glade to help you! I am going to close the issue.
